#!/bin/bash
set -euo pipefail

# Create ipython config directory if it doesn't exist
mkdir -p ${CONDA_DIR}/etc/ipython
cp ipython_config.py ${CONDA_DIR}/etc/ipython/ipython_config.py

# Most software we need isn't packaged in standard ways, so
# we do all installation in postBuild.
# We try to be as fully reproducible as possible here.
LOCAL_BIN=${REPO_DIR}/.local/bin
mkdir -p ${LOCAL_BIN}

# minibar - https://github.com/calacademy-research/minibar
pip install --no-cache-dir edlib==1.2.4.post1
git clone https://github.com/calacademy-research/minibar.git ${REPO_DIR}/minibar
pushd .
cd ${REPO_DIR}/minibar
# pin to a particular version of repo so we are reproducible
git checkout 5db50ee2b67c39baf71820c70ff2898758206605
chmod +x ${REPO_DIR}/minibar/minibar.py
ln -s ${REPO_DIR}/minibar/minibar.py ${LOCAL_BIN}/minibar.py
popd

# porechop - https://github.com/rrwick/Porechop
git clone https://github.com/rrwick/Porechop ${REPO_DIR}/Porechop
pushd .
cd ${REPO_DIR}/Porechop
# pin to a particular version of repo so we are reproducible
git checkout 109e437280436d1ec27e5a5b7a34ffb752176390
python3 setup.py install
popd

# seqtk - https://github.com/lh3/seqtk
git clone https://github.com/lh3/seqtk.git ${REPO_DIR}/seqtk
pushd .
cd ${REPO_DIR}/seqtk
# pin to a particular version of repo so we are reproducible
git checkout ca4785c620d34cf5934b89ae8e00f6dc71a5bf1e
make
mv seqtk ${LOCAL_BIN}
popd

# minimap2 - https://github.com/lh3/minimap2
git clone https://github.com/lh3/minimap2 ${REPO_DIR}/minimap2
pushd .
cd ${REPO_DIR}/minimap2
# pin to a particular version of repo so we are reproducible
git checkout v2.17
make
mv minimap2 ${LOCAL_BIN}
popd

# miniasm - https://github.com/lh3/miniasm
git clone https://github.com/lh3/miniasm ${REPO_DIR}/miniasm
pushd .
cd ${REPO_DIR}/miniasm
# pin to a particular version of repo so we are reproducible
git checkout v0.3
make
mv miniasm ${LOCAL_BIN}
popd

# wtdbg2 - https://github.com/ruanjue/wtdbg2
git clone https://github.com/ruanjue/wtdbg2 ${REPO_DIR}/wtdbg2
pushd .
cd ${REPO_DIR}/wtdbg2
# pin to a particular version of repo so we are reproducible
git checkout v2.4
make
mv wtdbg2 ${LOCAL_BIN}
mv wtpoa-cns ${LOCAL_BIN}
popd

# racon - https://github.com/isovic/racon
git clone --recursive https://github.com/isovic/racon ${REPO_DIR}/racon
pushd .
cd ${REPO_DIR}/racon
# pin to a particular version of repo so we are reproducible
git checkout 1.3.2
mkdir build
cd build
cmake -DCMAKE_BUILD_TYPE=Release ..
make
mv bin/racon ${LOCAL_BIN}
popd