#!/bin/bash
set -euo pipefail

# Create ipython config directory if it doesn't exist
mkdir -p ${CONDA_DIR}/etc/ipython
cp ipython_config.py ${CONDA_DIR}/etc/ipython/ipython_config.py

# Most software we need isn't packaged in standard ways, so
# we do all installation in postBuild
LOCAL_BIN=${REPO_DIR}/.local/bin
mkdir -p ${LOCAL_BIN}

# minibar - https://github.com/calacademy-research/minibar
pip install --no-cache-dir edlib==1.2.4.post1
git clone https://github.com/calacademy-research/minibar.git ${REPO_DIR}/minibar
chmod +x ${REPO_DIR}/minibar/minibar.py

ln -s ${REPO_DIR}/minibar/minibar.py ${LOCAL_BIN}/minibar.py