jupyterhub:
    hub:
        config:
            CanvasOAuthenticator:
                client_id: ENC[AES256_GCM,data:4Aqp1ZLu07LY1LW/6c5Te2M=,iv:xyQZ1EfzMbLLO382Z+EfEasJgLicVcgtFFiNJly4glY=,tag:IO0s2eWeY71DdjH1D+zyQg==,type:str]
                client_secret: ENC[AES256_GCM,data:i3c/vQEUVt32/ln/PTcUjG1QD/PeHx+grkAdafPTNm40au0XzfKdtfdSI9l2Z6dnn/TsYNBYvHgyG06Qu1mGfg==,iv:GXBfTdi0meYthRp4cG89BNcUzzuja/g8sCruVGBqIxU=,tag:Vldvwx9ZDKuVz4/7+0ZTXA==,type:str]
                oauth_callback_url: ENC[AES256_GCM,data:R0WCXLOYKGjxV9hkoEeuCzQ8eeYtSQCXP8wKv1pizei/+o/zUrjV3PZkiRu+7yeYu+be1P8NUnWh,iv:SkBWdXvub2syZAiH+MnzZlAWgTjwYvU4K4AO1njoylY=,tag:l33C0YRMvzFlS4cQ1gskWg==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/ucb-datahub-2018/locations/global/keyRings/datahub/cryptoKeys/sops
          created_at: "2026-05-08T23:32:21Z"
          enc: CiUA67O9ADxHo0vFAl2zhuODbxZ0J8F9+je8o3AUNlsQ6K8OCPYEEkkAdEnSzoNHCMkzUVrRBJUqSl/V3TBTxiyEJ995DngVDOsXJKZOMn5KYLA2W73QROpzFz5ib2iNrrcUEWSVPRitQXwqtnhUv9jv
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-05-08T23:32:22Z"
    mac: ENC[AES256_GCM,data:9zlOJ0CC5uTACNdYPVV2QuDdPa4O3EmTNcnShZcZJBbrpabS/1AsaOVc5apwlfY/PuKPa0yPvb8KSVYfiIOwc2HBnWNDOaBs/CABvpR/cq/fMWhNHNc7eltqtEQ4dMr4H2ccN62iybwZEwiwMqPKLmDfOKtP6aHc0uWWmYugSeA=,iv:TKtKQLqpZDywx9kx4WV3s6RMYGEfyGD3a/pEqk5OrHk=,tag:5YtTxnGPErXMG9OoNQjpBw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
