jupyterhub:
    hub:
        config:
            CanvasOAuthenticator:
                client_id: ENC[AES256_GCM,data:dyobpquB9k94F7NarHx7xIM=,iv:HSUVNDI3YM0qnrOQsdWZWTg93bIApEHthar7vLeELyY=,tag:3owBirvOyZu/rubaS9Uieg==,type:str]
                client_secret: ENC[AES256_GCM,data:hX5yOtxoC1eSH46QTjgOdL9kV2lq6KEeoiAQKnsJPZ1lZmpqmAxyoe4g42FLYaskqU4m/hhzs+br2Y4REbFcAQ==,iv:SWXF2qRMBW4TlLI9jwY/WNhuUukAUpX1hirV9zfZSdY=,tag:tZvWiOaGNdmqVK13ZpoG0w==,type:str]
                oauth_callback_url: ENC[AES256_GCM,data:T1xgORNlaD3+MlYxZwLOFQRCxASu3hkccLXDKTNllIZx8Q2MGJnx2z8UICTu+cr4KfYZ1av3k98TaXc5aRUsooI=,iv:fx+NsGCXU8ZHVvD2XbgDQX18Clf23kg8icr5zD87NgA=,tag:h/7mXIupF3iNIGBQJ/akjg==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/ucb-datahub-2018/locations/global/keyRings/datahub/cryptoKeys/sops
          created_at: "2026-05-08T23:31:52Z"
          enc: CiUA67O9AD5bqKzHun7sMZ81giu0LSCLWgfs2rt5wnstRaIk1MBxEkkAdEnSzuxMHk3plxl5Xu8QZdngQoL9Mw3qPKVPVR43rEpdCDScp7wRUPDuGuKMUPu1o3TLnlvm87qVaOoxJg5MHlQG4mXZmRvF
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-05-08T23:31:53Z"
    mac: ENC[AES256_GCM,data:pchjdLY0W/PrA3xLG2k/UrloZOdhb3fIVFtrxbtv2jN6VN/q9PlRKfQJ1vQ+pp7wW3CY0BBvTbf+h+mXZbqJJTk6TkLGeff+j/Qmg3qGF8SUp8Zhs2ic32NXJetQTjbzRGywBCX9l1TPMkZqfjYCbuMEnjDFJP/pHHZRYMy2hMM=,iv:vJ4/ttXNOCMjYmZfqWlvrYk4hAoPXYW0zVwUGKyI2xY=,tag:MAyxaNjOCYw39nIDlVFWQQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
