jupyterhub:
    hub:
        config:
            CanvasOAuthenticator:
                client_id: ENC[AES256_GCM,data:y5YtnypXUffWaN47QX5zoQE=,iv:PnH7eptOuqjAfaKO/pmFaQWWIb/7LEeLuMhBxX9zFU4=,tag:Cw276nalFClNc/H5nIf3Xw==,type:str]
                client_secret: ENC[AES256_GCM,data:6dnDii9MxE8XXV7xlSZgKUQ6uiDlR/lem/zZvxdiAS5+kDmKXKQZkWa0gY3EC4hVCfjRHshdaw2XgJmDvf+xPQ==,iv:WYi+Q7yotsjRvy8YNok+gD0oZ8jveCfJhP80UBeTVR8=,tag:C0J46ZeixwbJ5zWKHX5BBQ==,type:str]
                oauth_callback_url: ENC[AES256_GCM,data:8CTYeqemaSjpyiw5alGmcj0ILxXch7veoOtAxfzVUvNzms8RXu20AUUrMqQI93HJJZbqx+Dhzg==,iv:5tvgrwN3tvdIFx+5cn23eKjJ/FvycpxnCK8NwGBKwFU=,tag:dSaXpzLI46PhU4Pc2edmuw==,type:str]
        services:
            grouper-sync:
                name: ENC[AES256_GCM,data:3Zws7fQbRi9wNMM5,iv:kLdTfgfw9ENVuvRbL02EMTqhCL4NbfhwR/dPztczTTE=,tag:A+OFM6v0p+Y0kbL0K1jttw==,type:str]
                command:
                    - ENC[AES256_GCM,data:muHbKZXBRxOR5It2,iv:uNoG5qzD0aZttRAuEMic8faJGWxDH4x/QYNq7KJeTX0=,tag:nAfRKtdr8bHAtj9gPmJ3dA==,type:str]
                    - ENC[AES256_GCM,data:p5pZTr0uDLxZ1VP2sPLJxQAp7zVdZvDmP9I=,iv:PuZ7FDVf7X/cU45+EeABaOu2FxJSsC1TGeqwmxv/oYU=,tag:S6vH5hmRz/RSzA9uQNPzGw==,type:str]
                    - ENC[AES256_GCM,data:IWcfuJXp6cHdXxJuSmwTnrWI7+NCAbtKbpYWqgPFaQc=,iv:CqhLBG2ndmKuDK5IkpMXoEPE1TT0XSpGitGfnEazJGQ=,tag:G+/zUcdKSVhGxowaMsI8Hw==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/ucb-datahub-2018/locations/global/keyRings/datahub/cryptoKeys/sops
          created_at: "2026-05-08T23:32:09Z"
          enc: CiUA67O9AAnI+eSPUGIeE7NjD5OqIO51ohI2qUo8lr4h5pb5Ar2+EkgAdEnSzt7bFIk04Q6z2IcR6kcEQfvnwyaUCg4HOQjVrNU3XvCNuJIgiMS649SMhpN1iNDrZL6V0HsDWIwNDQGlIXmhGYQ2zOo=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-05-08T23:32:09Z"
    mac: ENC[AES256_GCM,data:z0m+6bYGHLVotwW7DXd6re66H29jwCmGY+SiQGTur5zgRl/e3V56HwewLgV3mHUG/GWPvfgmnEWcFRSJNPc9boBakhhS+W4JUyK6sLA6+UmwJj2b9EFCTm/mDcrStZ5H4muSQkkrkGn1UxP1LzC3QjNahDWSb040elwpsQf2xU8=,iv:pAzsDlYYP7Xcq0yrDtfEfqHXznHA2w9yV67uda5BAQw=,tag:yKDZuCYOV9v5ZmFw58qrHQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
