jupyterhub:
    hub:
        config:
            CanvasOAuthenticator:
                client_id: ENC[AES256_GCM,data:V/aj7JXbmtNdmC6jUHLgTWQ=,iv:8k1PvxY9ua829XYFTzyxHBxjdtG4atT6VeKjAw8u12s=,tag:FiTMdqVUiUSJOEbAM3f6Qg==,type:str]
                client_secret: ENC[AES256_GCM,data:nstRHwSTgheQ9CCLcvLLcOJDl1QyiVqUhdQ/l/CdYlo7+a/iIvvYQLmglC66fcPDJZNQW8yfuLWE+srlDJVdNg==,iv:cRLurL5qyUp/dhlo/3Rw5aD48GG5MPN/vNiu9VjZFUM=,tag:ru9og+exyqrl7s+cesL2/A==,type:str]
                oauth_callback_url: ENC[AES256_GCM,data:pu3oTEcaRpZ63hIZLvAQSPzDWqjUiA8/8HNrvhkQKMWosNsIjMa41V7DWCW72aIdmhYAiprjhms7kfb9/elv,iv:pUdvia4Rl6qWbIGm9CzOMiYUCh7cFa1YiXv74cjpZ1U=,tag:kUz+InOmUiMbyRW0tBha4g==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/ucb-datahub-2018/locations/global/keyRings/datahub/cryptoKeys/sops
          created_at: "2026-05-08T23:31:39Z"
          enc: CiUA67O9ADuko3gUpfVebUmkOShjfdFH/QL5OT8nj8uCSFZUhiH2EkkAdEnSzi0V0wjHK2aWW3W83rlpNyrHPTPLR+bWWTPJPqboqMbd/lWfvdXlaYpaV/BoyxTHB7ggo2PH93x56dc22p9utSF2AksW
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-05-08T23:31:40Z"
    mac: ENC[AES256_GCM,data:HrFV9ULOPjQxUcvvMuCa0iZNXiDsX/cYCxOdz9du6ANTVe9cJ06CnyQrayDZke1WHxUNaI1O1AeCpFe9rt9ZH69zjvL9c45Bfjz1esY3SQxk+PFTkNrzFWp+zkselJNriN4uHS6d1YJPBkWqymqi2gRH8i9PPUmlngNFFUAD4jo=,iv:VjIsCKlioGBCXVTe9oAd5oqesTGlk6nZaPY2DacvxGg=,tag:L090JIBygKPbBXChZY46wg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
