nfsPVC:
  nfs:
    shareName: shares/stat/prod

jupyterhub:
  ingress:
    enabled: true
    hosts:
      - stat.datahub.berkeley.edu
    tls:
      - secretName: tls-cert
        hosts:
          - stat.datahub.berkeley.edu
  hub:
    db:
      pvc:
        storage: 4Gi
    loadRoles:
      grouper-sync:
        name: grouper-sync
        scopes:
          - list:users
          - read:users
          - admin:auth_state
        services:
          - grouper-sync
    services:
      grouper-sync:
        name: grouper-sync
        environment:
          JUPYTERHUB_API_URL: http://localhost:8081/hub/api
          GROUPER_BASE_URL: https://calgroups.berkeley.edu/gws/servicesRest/json/v2_2_100
          GROUPER_ID_PATH: edu:berkeley:app:datahub:datahub-stat-users
