jupyterhub:
    hub:
        config:
            CanvasOAuthenticator:
                client_id: ENC[AES256_GCM,data:EC8jF8Lbu43ZhcHy7MDg3Mg=,iv:CHpX6JTxmtcM6QA04Hou2zSHb/zs34/GJ5hHM7JEER8=,tag:nh8QpPMgNFjTQgEhtgOg5g==,type:str]
                client_secret: ENC[AES256_GCM,data:hEAL1ndcR4kPMmlCmsZ2fQPrQJJFjdpKl3UO+C1un+Xa0XoyK5+nIhTA8Q/xM4O/HgM5vuFHWvqizfazUwJ0/w==,iv:fh/nm6FoVJsXV2423UE60g50068zs/v5t0RAjNS0VSA=,tag:9XwzayH9fiSAlC4oej1Oxg==,type:str]
                oauth_callback_url: ENC[AES256_GCM,data:iq040o78R3MLkXBWbOdknpLv828rKX8t4tAL+K9ILlfoj/AMTLj7dSN6aov+fCHZQQcX/H5S,iv:S0tMz2PpU4IPzcYLjq5wtVSpn4Ea4V7G6/e0FKPcuSI=,tag:hOPUvPCnRAk7qUqlbvmB3A==,type:str]
        services:
            grouper-sync:
                name: ENC[AES256_GCM,data:qYkd5zVtnaDEWD+M,iv:wLBKThUlMTSnxq174hLCJgMJ7u4cHTaVILVbFyO0vUg=,tag:E9z6unwUCboqfoHBugqn2A==,type:str]
                command:
                    - ENC[AES256_GCM,data:mih4R3OijV26719T,iv:IGHkh/AmSfnq85eD8+TuKfy/0lmNuToEGsR9/lxwfSI=,tag:8X7oNGG2dX/wOsoM8hXpxg==,type:str]
                    - ENC[AES256_GCM,data:ldgjYgU3KhkevHDDDCb6xPM+pPFpkba3TTU=,iv:50XrQxqMdRxtrKJhHOC34X6YCGCeZBrTGzMzf7aLwgg=,tag:V3kvQVnADsUAydLX6dd3+w==,type:str]
                    - ENC[AES256_GCM,data:CKaPQkoTkHsmjB9Tqbxb7iK5bPn6504+4nW3jNX5jH4=,iv:e2c/WujaEjWpj22K0JJiswwYo6U+R6z72WUdkscMrQM=,tag:TEWW8Ej8xKUNSNpZe2Hyng==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/ucb-datahub-2018/locations/global/keyRings/datahub/cryptoKeys/sops
          created_at: "2026-05-08T23:32:03Z"
          enc: CiUA67O9AA6HuGl504d3Zxcz7ZotlhSjcXYtPmbvCf+rBbr+aMXCEkkAdEnSzj0G+m8eW+qtiOaYYX+ZzbWeRzr+2Il5xAVIB5d3/211XdaIw+ArhCKxs0ojuNg8UDSnU1G32w2CsxJZmf7acVa51m2G
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-05-08T23:32:03Z"
    mac: ENC[AES256_GCM,data:EBp9KAO+NnsojciLiFWnb/h0ml7vyKx4CuK0rC+oTuq5iwnqNnuA/6kRC8b7eN+uOpbrwIPmPuRd5rC05Za5MBFhj1+l1AwJosuIS6hJZaW5g88OsQmM/eMijvGkVCHfvMCFESj52ep69G5C8lDSuTk3UxpvzeGjBwXMBTAYNLk=,iv:bh4lJqfoyjOHzj7gI2e2lsJz+PtlBQYqpUHwbo+Hlls=,tag:+LrJzlQTMjNt1hoYnyvUqg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
