jupyterhub:
    hub:
        config:
            CanvasOAuthenticator:
                client_id: ENC[AES256_GCM,data:QSJqt9ONBY4QUzeLqfmJLog=,iv:qQqRlAvVZa2cAOUS+zNYc1ya/K6Dlttt+a9WyH7qL1k=,tag:Wg1ssNUsNv33bBTegrFdhw==,type:str]
                client_secret: ENC[AES256_GCM,data:HdbleVMboMbyczTvJz2miLoe++sxrm+Eqzq8WhdKxPzNYqhh9pOoJ6FjYbERTsGd0kKN5WldJVwW2ZGY7MhZLg==,iv:QK9mW3k30LCYEVvB0WVfDJFXwN94ke9Wy/Zn15fhJPg=,tag:X8OyE+TiXqsITi+ZgPi7XQ==,type:str]
                oauth_callback_url: ENC[AES256_GCM,data:VnaGs0DSgv7/F8ZmqnMnvv6VNgogtTQadwqR4/M34DQxUZiZMioqAT/K9r1aCgqvEBBjwD2+xg2lAXKaJmw=,iv:+KsQOp292qoznH171nh2dwtJ5XfRHvtI6+A54szMgkI=,tag:rMZoR0M2WxsWTUdyqQJVXQ==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/ucb-datahub-2018/locations/global/keyRings/datahub/cryptoKeys/sops
          created_at: "2026-05-08T23:31:33Z"
          enc: CiUA67O9AEI4iDH2vACM6SUrMmSj5GygzGYYyfTk8zbkPW0XtSxVEkkAdEnSzjEES8Yk6s20q39iVq+LX4NbXLE7VTvnl4OPLIGnDAP+4WxvYNbQ6AnJ9U+uV1Vr7gAVjlG8XcqtsQG+sGDhW0eBPHAn
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-05-08T23:31:34Z"
    mac: ENC[AES256_GCM,data:ZZ/zaMYQpgP/VT13b+p79ceOvT2mvL034rkB62MMQNIjQoIqgUBwXBqf01RBJWJ6WbeKy+xssK0rUyQJ54c6mNnsvufCwtgqcEZRli1e1YDjnVWemiU4KaXZAP3FzTjcS/FxAX4Rw4bm0VdrcvUzBzE8cFe1g0R0e2oMQjgyxiU=,iv:c+FhCNNa97tqq1lMGvMeLbeRutZfdZJp+rQMdwCObcg=,tag:dmjZOci2Skd6mvVEPS82uA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
