jupyterhub:
    hub:
        config:
            CanvasOAuthenticator:
                client_id: ENC[AES256_GCM,data:vHwdvrMVKq7V80ANKpEteio=,iv:qKx+8Eb9K3dNMx3TgThhBD1PN4VVgDpVkPoJI6twXXU=,tag:02h30SelpUHq2+nF6l68bQ==,type:str]
                client_secret: ENC[AES256_GCM,data:SFSp0LgLeGD9XQDQ6s/cYskT2UDOyZOBNSpvy0rk/jThLOgWMkLxirbHcb+4vlHYtteBY852LgP1e7Yu5XfYqQ==,iv:jLmwnaA1Y2Thrxcy4Iie9u2m62C7M3gPZnpvYW7x/zs=,tag:3JoIX6pT4s7Ktj2UOnUdMw==,type:str]
                oauth_callback_url: ENC[AES256_GCM,data:h5oy/EXNrJ8jdnOhOmxIhOasCD70YDoo8URpmvz3uZGEJJWwAWarM322z0YWijosPuzmmwE=,iv:FkbiGLTCaeSfyjcGQhxMzjqeC5hIIb16e6t1EJE3Q7I=,tag:vYWhk7hpKtbmM3EpGnYzpQ==,type:str]
        services:
            grouper-sync:
                name: ENC[AES256_GCM,data:BGQkL/yuEoha6qS6,iv:h27c3Svc3pE+l0WRQ6nYsXHQdObftC/0lr38vuskfK0=,tag:2qN6Iioix+YITGsWeli/lQ==,type:str]
                command:
                    - ENC[AES256_GCM,data:K4r2i5Sjrm3wn92+,iv:LSxG3qGCCkdOc4B3hMtUWC6tlfFADYtEpAMWrSbhGo4=,tag:Oz/Qwa0UzDmVvf2OIGhqvg==,type:str]
                    - ENC[AES256_GCM,data:WFqjAAZgI3cIuffXFd4SQXO+Oiy0oTOslCs=,iv:ehAxZWzBj0GfMDOLaZDqVVI3S2MmuDSjc9a8ShFdrIs=,tag:cWE1tcWdIUAjtzvXMBXgXw==,type:str]
                    - ENC[AES256_GCM,data:B2WkjDNUQzdCLc+Rp6H3eYAgGchsqdnRoUQm9igIdiU=,iv:jlckwGCYWwk8fhtSyQLASAJDpuzuNUgL7brs2Unpq64=,tag:AzWZUatRjJOdWRYiC4Bs2Q==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/ucb-datahub-2018/locations/global/keyRings/datahub/cryptoKeys/sops
          created_at: "2026-05-08T23:32:28Z"
          enc: CiUA67O9AKomRPeKu82cB5XVgU6E98Bj+xVayogNJe2ZuaaGeL9YEkkAdEnSzkVaeF06XeNCKT0nvLlTnJQkKvoQjYHy5RbSE7EutsdDahj5gSmiu4KfM5s+ZLpwIDObCpSXmEPUhqznm5/lCc74TzeQ
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-05-08T23:32:29Z"
    mac: ENC[AES256_GCM,data:HEcxCHPua0qIgFWOky6qNIMHXJ3Oaox0ecIld/Lpf7Ig2bZsPhFijGRKAEd4/4G3i36m9MXLs4fFq/JIZBq8m4D5cw6xdKEXvGyMM4oY2BAXAoGj+4yMQwBHZo2ecjV7SGKu52TZOE0sUEeEEzjuhKEiuFzLlWmG0FRjVOSCEKU=,iv:Hxo277R3QNTyZIN6wX04qutt5OZuKTYk5Wm6881rnjY=,tag:4W2zUKzKBwn796dov1fAQw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
