jupyterhub:
    hub:
        config:
            CanvasOAuthenticator:
                client_id: ENC[AES256_GCM,data:v9Iy4FxLvQ0jU3M/d2iWPsQ=,iv:498mKpZYdZdTRDOmZeucRu5A2F8LNNHXxCWunG9USEs=,tag:3qnw/HzymDXXG9f2SzyoeA==,type:str]
                client_secret: ENC[AES256_GCM,data:lln3mPCx9Igw3Yqr3Pog3+ZXkcBuiwRqXqcrDzCpf5p7oM6VcY6rZ7vUyZSqKBSRVB4NH52LNm8NRB8YUH7Qlg==,iv:Lq6a1TJXPu9JR32Kod2Qx2PMvwPuXv8cKk8RgC58RwM=,tag:CF6/zDuzHyVrrCn8UxAekw==,type:str]
                oauth_callback_url: ENC[AES256_GCM,data:XZokJeaHoUgW9hS0AGsZbqwxYsH0ZDgdvhoaYhZbq39zj4HuXYaBHlNdkIVYhXnJEtrihSZCz2H9f8jAWw==,iv:8qXhQfcywcQbKVKMc9Z2ucaetL067i2GfFhNwC+QdTY=,tag:AsYvev5NaOSMNQC9TmVFgQ==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/ucb-datahub-2018/locations/global/keyRings/datahub/cryptoKeys/sops
          created_at: "2026-05-08T23:31:59Z"
          enc: CiUA67O9AGFeLfAGqUhNchpVzG2K9NYUY0UKkLDX+Z+COg0sHWe/EkkAdEnSzlcAizjFKcAgRqxkj6mBTiepW5MzJcFAnhANHnC+y7HwBjzkp8aHig/D6blIgZ/+NlRMmDXgdaBSxiYbUMCBSqXWQTps
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-05-08T23:32:00Z"
    mac: ENC[AES256_GCM,data:8E3P9xYTg/7MxgnPQPOJHO5JtyJPCiLsFqZ4Gy2hqCVvG9i/LWK2QgjK3Lcn9LeAkorDobVBPnDFNftAahLwT/APd9CcxRQRp15610sj2AfVLzRluOctzcAtzuv0vdhgi2qwsltJ50mCTzFWGr4cAwpmhNKl/NIK9hCS7goSOHg=,iv:RxK8k7NiPvelqp2mj3QDBpAb351DF5nNKO1SW2Crai0=,tag:KP8GiTr+QZrUromAtlxSrA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
