jupyterhub:
    hub:
        config:
            CanvasOAuthenticator:
                client_id: ENC[AES256_GCM,data:9Eq0aOpt2PiY72UJgzc0alA=,iv:lUuiI++9UuTdsUhLHuTSmu/UItohDi9kEQKi0EsYSoY=,tag:26Dnpsg+vu2ESl/Be6Kepg==,type:str]
                client_secret: ENC[AES256_GCM,data:QkyjSPmF0EmJBIwA9pv0oEhScMn2v1rTl4VH2uYvvTa7zDCQ4e30yr9dKyYia+yU5QwjL2oJLapx0rZDxPFDTQ==,iv:6pMx0tpXvAPzFvzX6DDkzNWd4m/dJek4+OEMU5xk5Rg=,tag:JTDybludwWkPZV/kEkkcEw==,type:str]
                oauth_callback_url: ENC[AES256_GCM,data:4UR4EYlU3P00ggzLrGZmQs5l1bO4muBqGF9Mloegeoupm25FUrjebZ5Dm+qefqrWyXzpLWLd0Q==,iv:98CCfEJvLGzKw2YkQnvkOJJOuCL5hX8yPqPdmkovD20=,tag:rEKyyekSltrwXTJU2PQdBw==,type:str]
        services:
            grouper-sync:
                name: ENC[AES256_GCM,data:D8+ZSXpDLODgNbC+,iv:ahoTbK7MzcLl5z4IDhSCI94JTulbbN41aBSNfdFW/us=,tag:QvJeFkRRck6SUOIx40/9YA==,type:str]
                command:
                    - ENC[AES256_GCM,data:bQERUJFEzXC9OivY,iv:Espsiqf4AgH54XW48mChgu0CaUr3VOEv+dmOo2/X1AI=,tag:dW5jM0Su0Sw4RRHJGdacFw==,type:str]
                    - ENC[AES256_GCM,data:mgUGXqLQCKa4yDk/jkfIcuKB61i3l7HFURU=,iv:EpXmUiHWadW2JZskihp+xRNlR3xRn/MaO5oFL1m8i9s=,tag:fD/d37YYdFsMMIMezo/e6w==,type:str]
                    - ENC[AES256_GCM,data:Pzf8KQid/vCZgJLdbjefo673mEq86yrsvTn4cqh8Ezw=,iv:Atp2O6pCqJDIh1ym1067Ogk2FppKZuesqfex5b/Lc8A=,tag:1JzpUn5s70TurhcFq7ajrw==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/ucb-datahub-2018/locations/global/keyRings/datahub/cryptoKeys/sops
          created_at: "2026-05-08T23:32:17Z"
          enc: CiUA67O9AK/RdMjFTyEaINOx4E56Ucj97u7FeS+qNQfu2Yneop9eEkkAdEnSzqm/UzQ+YL1Md52+UY5fzx2IP5EM5O7N21v1ZZFLI2y8dzCkWqxKHdJw73mZT9sJhP0giJy4FfG8Q9mbgh8aSgQUrAsm
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-05-08T23:32:17Z"
    mac: ENC[AES256_GCM,data:It5ae2CvpX3cGZ0uStoLUVLGBo14hnkCuwvSrsvQnEx/BL3KE+7onQk509c0aBxhL/Xm0V009mZLifuewY5oLdcXnyYKq5Gok90Eik3TWU+PzaHr9IijRCfD/fKJb9eCz8N5pwbiU4SrVe54HuMeJvq3mrX+niGEmatjngyyb2M=,iv:4bk9kUuSVw39jIpqZisvpCnNJA/ZWQpnDUunCqcznfE=,tag:ZGVXUTqEIiJwPGlbrUXrgQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
