jupyterhub:
    hub:
        config:
            CanvasOAuthenticator:
                client_id: ENC[AES256_GCM,data:rFWh0wIKWoMKVHeY3hLTXq4=,iv:GJQj0hnGE5Dh43Opc7A7NrQLuCJOLYfKCgyTwvxiB0Y=,tag:Mp5gmlKgxlKZ67lTjqYJzA==,type:str]
                client_secret: ENC[AES256_GCM,data:VnGT3pTGA73GVlW7HmzOgaDadmPW4sPcR+sdZQqXowA281r6eiCOVVb5n1YdEfW4hWezaU3jLXoewltG6C3x+Q==,iv:hi1j2nfFgXIMTqK5Dv3DpL2i7TEDmbML5E0aIwyHr1U=,tag:zoaztOWtzvUGhDuFXdh+jw==,type:str]
                oauth_callback_url: ENC[AES256_GCM,data:5lj7VMwepIXmYGRNnHK1dwg14EH9gnU9CBNzYmflubIb2zdXzxhPMfX5vaUO59jVIaRrih48rf6JkCgR4d7W,iv:M5iyMHi7cwrS6rl8ASgc60MwIZLvA9BOTXd3aWnOE80=,tag:ECb9dTB6WjXIsn1WHBQd8g==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/ucb-datahub-2018/locations/global/keyRings/datahub/cryptoKeys/sops
          created_at: "2026-05-08T23:31:48Z"
          enc: CiUA67O9AEutpB/7l+2Ni0GOiZJG6g+XHcyLqNSFsHRhV+15Ooh5EkkAdEnSzu7nAkgcHdvBhAbSNCq6clLi7VqgrQUH5doK7KNPYfAuPlsoX5wERa66Owm5yc7ph37vfJJX0EwxNWkQOej8uYWDrlH6
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-05-08T23:31:48Z"
    mac: ENC[AES256_GCM,data:NGzNoFaoaGSupppLlsVrII06Kuruc9huzrgdZN10NvovqjXB/PaP7mX1oLeNgptYMPZzGRaTncGG05Hb5XeH38LpKPdit89U5d7fHJ8X9u1CgCv+S+YEtBBAC4RjDxcNTNtcmBCvU6fUrK1LVpPrDZ4znIUjprPjgdixJCAickY=,iv:oYHVuIOpTLmyGyciIB3DAOjDo6JVgHZmVSJwY/2HRUc=,tag:ilKV8zmscnimJDJuO/EIhQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
