jupyterhub:
    hub:
        config:
            CanvasOAuthenticator:
                client_id: ENC[AES256_GCM,data:C2ChkxhzLYXMjes0Sxl0XmQ=,iv:QDLHu3o1NiOR2LMSvNXK2omHqse/N50+fQFAYVfUnic=,tag:i8NFCHQdWEZqxSekLCwp9w==,type:str]
                client_secret: ENC[AES256_GCM,data:gN5U0CUTebZvWkhw+eof4HR88YzbJYxpDEpvDYL7kwsCyXr2XA7bh7+HrSTm7NQKHowusNz+OcqWFeRC1mzV0A==,iv:6IQV8+S3NL87/wTtvOkOD1q98OLTRVeOEsUA27NHK00=,tag:VJr0NW1zRwe7PdZFWIzUoA==,type:str]
                oauth_callback_url: ENC[AES256_GCM,data:epUtitNBzBJB0htRl2JwEaWWIQkRhjJm5/5bRgBM1SpzB8w68pTQHk/+P2jjwufWtsGJouueOw==,iv:UW0XJai6QFaVE6rR/JLphjXDi0mLM7scVI9yUIEwLtA=,tag:rx87UXwVNSUASrhruY4Vow==,type:str]
        services:
            grouper-sync:
                name: ENC[AES256_GCM,data:ov/JyNiF5EVpQ5VK,iv:aHTRa2PdG7b8vSjVTYY+el/5bjauaVpG1HcEwrPYbWQ=,tag:PbhhwS/dqV5+NPtsF6FMbw==,type:str]
                command:
                    - ENC[AES256_GCM,data:xIBwQPoPwRscYM+B,iv:BbJw3p95uWDZHGvGKPl2kWxoTXxPxu68Dp198U2d5TY=,tag:EkJRU81/V7/aQzMp+OP+JQ==,type:str]
                    - ENC[AES256_GCM,data:/FxRJ59QiDIF65dSpbtsdmnpVYZ/6MtTE+o=,iv:PE9mVvkuClL9moR9R6ioDcDRYhhmilD9HQwDZXfPiu4=,tag:/o4xojCLROLQ3DyIWg+N/w==,type:str]
                    - ENC[AES256_GCM,data:wNOF3lNfr2LjVX2PiSZtbOUyfgsv4RSp9uDMsWQxeCs=,iv:splqUVlQYAa5lupoLGUXjxR7tctPfoK1MiL2UKc+axc=,tag:IqI9N0Y8foa5uj2XO0oBgA==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/ucb-datahub-2018/locations/global/keyRings/datahub/cryptoKeys/sops
          created_at: "2026-05-08T23:32:04Z"
          enc: CiUA67O9ALynv7+4ineprRe0OMW9QQA07Rbn6C6oUPz700TA6oLVEkkAdEnSztRNs8U+XaJuX0CPVRLWpyqP0mbMHowck+kHJCAVgErx88FZmIoOI1+HFcGCpARs87cd/aiGFZYkjN5VEFG86uLJBf2a
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-05-08T23:32:05Z"
    mac: ENC[AES256_GCM,data:WkagatOWsqOYqB/nzd4dLJF+krW8Dwx0xeye88fZGx9TmJISxecAQez1uBxKxwPdsM/MHsvX84kiyZjTkRpxALQk+IAZ1LZf7vlwrEjZT6rda2kegx1qv7654Dst4Cv1OPZIR4Tjgt4LzuubkhFIXOLB1ytizklJeRrGwocoOfM=,iv:locdR18AkqaQ7kuSaY2BbQOUJt1rqTii1kggVfrWgog=,tag:W/WVWEn/Iu3JiJGzZ3Smqg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
