jupyterhub:
    hub:
        config:
            CanvasOAuthenticator:
                client_id: ENC[AES256_GCM,data:IrdYAJyiXBL2c6VMFMARVKE=,iv:OKYodNuIx4tNUnquXLNSnZcy/VbP1c4SUbScJBUIKWA=,tag:hOKZfEq/FzWdWeMsHeFtpQ==,type:str]
                client_secret: ENC[AES256_GCM,data:1UbmRHclcCgNfSCV8OmaM1yo3aZQM+J6iDhq5xOTSiNlQkvqAdA2d75buFTAJ9jbPWjOeGvd7KGewsFeuDl7Rw==,iv:lyjyFUYQKovQGjhiqE/mwpvDnTyVaHFpHI/XJ496DUY=,tag:MlSWZAELnxyMJlFDzwBsJQ==,type:str]
                oauth_callback_url: ENC[AES256_GCM,data:u7BQ8isi50Cq4dfDEedWI2dISc2D1fMn+H/9db5nqyKDXnK6oNjX242UyMW8mmo6JTtoj6rnqbDDNwjbBs//,iv:8hAsbiXa8bVeBdwdsF78POD95N5yeh0FEInu2Hghwho=,tag:BOp2z4NjSAhv5kETHbDoFw==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/ucb-datahub-2018/locations/global/keyRings/datahub/cryptoKeys/sops
          created_at: "2026-05-08T23:31:35Z"
          enc: CiUA67O9ANuJVJE2JurbMjTypz+qPc8zQRscMKo3eC2eRMAz+RTXEkkAdEnSzu8q2F2fESGhPm5Gc7V728esigo6t0t259eDgvGFN3vVLW1do58QVD/K8JmVushYy2wpzNESy7H9UqHy1FyzweO91YnS
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-05-08T23:31:35Z"
    mac: ENC[AES256_GCM,data:TMKv1HbsmbnjdNRTUtGhohJwpbjYKm8T9QkGU6S9hhCOwLW5ilqXB8biBS3ftDdx/d65aLC9YZP8pxQdouA8Hblf8MxVNB/viS5DHRG3AqbHaMHBai/8c4df5QE6tgkp2gZfRfMiTvgb3pH/ZlDWMGBTrdXwdenSXS+tJ8hCNxk=,iv:ffxyXpGrRXXv15XiP2oaU9o76RMnEeZ2kZcMoMUnVSg=,tag:dPMkXDAnKyLKdK4Dcg6+Jw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
