jupyterhub:
    hub:
        config:
            CanvasOAuthenticator:
                client_id: ENC[AES256_GCM,data:t2/hvBPSGdmgYXU8DrNKgzU=,iv:RbFAKOmySG99NdEUL4HeoKFnYm0YpoxcmBR2I3vN/TM=,tag:tQjr/dpg5VJn2VFiYRsfjQ==,type:str]
                client_secret: ENC[AES256_GCM,data:SC0X1hU+deyH5RQRVPbXcee8YTUZGQmOzmVIGuSd67HSrB2Q5Bc67y2LjbaRMud/LaFvJ9SFkQdayddKSjHnkg==,iv:jUZwgjMQ4gcmZXHYJr+ZmcMCPzoCZFsIpZuSCKaMDrw=,tag:AXyrc2L9Tup2JfcYUWXC4A==,type:str]
                oauth_callback_url: ENC[AES256_GCM,data:To+V5n9+Y8XY/CoZUl7fBjTVMWRv5axd5O4UA+N7mwkfad66Zbwr7YpOcD9rRqjJKUPkEnwcag==,iv:mwspibN4U99yXlDHUz7OwhZFaAvIyn7fDUhEwWCQjBo=,tag:9+MpYHEI9ZrSL29ZLQhLMA==,type:str]
        services:
            grouper-sync:
                name: ENC[AES256_GCM,data:7jR/Yxpt2qvVYPMv,iv:p4/ZUQU4MDLJ7j9jBwwOwrshVDzyGiIoocsyPUUmohI=,tag:g2D2asZ4x+SL5OIQDZ06tQ==,type:str]
                command:
                    - ENC[AES256_GCM,data:097LRkuZdK/Jvww+,iv:eHkWQ5DaJW3xE53IiY8lUoOQ2TiiaGpztKCNgy/HuQs=,tag:8IKBTjE3XXIpfXn03iBkYQ==,type:str]
                    - ENC[AES256_GCM,data:hq2ACgU/svddO4SbAMb8cnCqL8PsDNN7Fk4=,iv:LK/iwiNmU+rVbSmzP+q/JNEV7BTWfDplsC6uGVuOrMY=,tag:xysArPPSvBkZPPgp6cBzLQ==,type:str]
                    - ENC[AES256_GCM,data:Ryq8za9wzScXXiullICsahiGz+6XEWnXXzDPqemMwoI=,iv:Vcx0cDE3eu1EA0P4SnLKYNP6U83c0+3TL/JAy+ssAIE=,tag:U7QC97+HDODRaBc2htZqiQ==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/ucb-datahub-2018/locations/global/keyRings/datahub/cryptoKeys/sops
          created_at: "2026-05-08T23:32:18Z"
          enc: CiUA67O9AFKrFQlaish8doMuss7fBw0abKxVNgtqyZPOXsCBmAu8EkkAdEnSzqc7E03v3eA0ZWAAG86Xo2G/1obmEtRVLwRI3382+Xif2G0jHJayiCMmUMNnxdCpAZjsAizq4eeVDErjzDYYReT+xos0
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-05-08T23:32:19Z"
    mac: ENC[AES256_GCM,data:ML33WGSBR/ZpX0LYSz6mRS44s7Q/El0DrtIpX9ZTp0fQUETDAugsEvb7acJynp3UpTFcXl1fwIU2IzevDa6kZfu5JhOjKAt2GomXkr1JcqygRbqtogwUYB3gy39fiQ66oB0YV8RyVy385mn5XqGqa01+hzJ2uSNuZgRuh5V+8Z0=,iv:49bbxEeT/kukYbssgNxCgJtCeXpInlX2eDweR7pPj+M=,tag:nNEND2m5MMbotJtBOQHalQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
