jupyterhub:
    hub:
        config:
            CanvasOAuthenticator:
                client_id: ENC[AES256_GCM,data:1uoUt/K+oRzUlvDQtapWnCY=,iv:qk+F+tc6lFKgNjCJC2oGCe7g3WWYVa/yjpiFL7brzNY=,tag:iQ5NpOow+Ccu4hUS5F7pkQ==,type:str]
                client_secret: ENC[AES256_GCM,data:6DuA73ES/fnB85MmuDTP7aZXSutx4AQDnk3PoWSfYeeVrPNDfGpMQ4rNnHk20w59yI3hpegsCHGnzWBWTt2AHA==,iv:s65Fqk5HW7yZtYnTbvjURaw+HaNcAfN0dqCKD9pBJlc=,tag:qRGVkWe9My5aoFlaV/n6bQ==,type:str]
                oauth_callback_url: ENC[AES256_GCM,data:vTXlrreog01u0B5Is6fNGqvHlAghhoP+sjpCLraYQQCP6zD/4R4PsgWUVCUjD5/wTNFgt+VQXZQK3CZIM14U,iv:Jio81yefvdkx7INhAGvBTOMxZ1NGHfzMibEbC1mEXcQ=,tag:ZIgR1b4+bhPSbzotXiKYVw==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/ucb-datahub-2018/locations/global/keyRings/datahub/cryptoKeys/sops
          created_at: "2026-05-08T23:31:49Z"
          enc: CiUA67O9ACUlXy52s9s4RMQovYq8TVd+s26KG78bTe3bf04xVkwjEkkAdEnSzojCvDe1uokW2rv9iYZiI50wACjfEG6JI7oO5vwHNtPj3QAZ2w+l850ak49kgEEbd/dqomcp5XLpYaqwBHadC0x5LHRD
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-05-08T23:31:49Z"
    mac: ENC[AES256_GCM,data:+fDpC+mFFoGJEWnwQP3P73gu2KU1879Z+dRwO3xIx3NKVERvftsk4MhfLomqxqLklIsdhWrEDzghqC+LeDhVcBl+MQmylAqkrlhEhnVihduZ7Y3Lk0n2Oy3ea4GuqPjMT1mExSxfc1qA+QP/uknE8q/UjrdqxNNkqQZ0H60Q7ek=,iv:jxINf7kWgB7OQ8MGfzxzVr58zI3tHbMIv46uEOK6+48=,tag:7Ppvr9v8icr3hLjtwhxxuw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
