#!/usr/bin/env bash
set -euo pipefail

# 2024-01-13 sknapp: incompatible due to notebook 7
# jupyter contrib nbextensions install --sys-prefix --symlink
# jupyter nbextensions_configurator enable --sys-prefix

# installing chromium browser to enable webpdf conversion using nbconvert
export PLAYWRIGHT_BROWSERS_PATH=${CONDA_DIR}
playwright install chromium
