# A melding of https://ucsd-prp.gitlab.io/userdocs/jupyter/values.yaml and
# datahub-based deployment configuration.

# Nautilus does not use an NFS server.
nfsPVC:
  enabled: false

# Nautilus does not let cluster admins set this.
node-placholder:
  priorityClass:
    create: false

jupyterhub:
  # Nautilus uses haproxy for ingress
  ingress:
    enabled: true
    ingressClassName: haproxy
    annotations:
      cert-manager.io/issuer: letsencrypt
    pathSuffix: ''

  scheduling:
    podPriority:
      enabled: false
    userScheduler:
      enabled: false
    userPlaceholder:
      enabled: false

  prePuller:
    hook:
      enabled: false
    continuous:
      enabled: false

  # We set this in hub/values, but we are forbidden from setting
  # net.ipv4.ip_local_port_range at Nautilus, and the proxy replicaset will
  # fail to deploy without this. This setting might not be relevant for
  # Nautilus since their proxy might not be leaky.
  proxy:
    chp:
      extraPodSpec:
        securityContext:
          sysctls: null

  hub:
    image:
      name: gitlab-registry.nrp-nautilus.io/ryanlovett/datahub-nrp-hub-image
      tag: "69193871"
    # Nautilus uses rook-ceph-block for hub db storage.
    db:
      type: sqlite-pvc
      pvc:
        accessModes:
          - ReadWriteOnce
        storage: 1Gi
        # https://docs.nrp.ai/userdocs/storage/intro/
        #storageClassName: rook-ceph-block
        # https://docs.nrp.ai/userdocs/storage/linstor/
        storageClassName: linstor-igrok
    nodeSelector:
      "topology.kubernetes.io/region": "us-west"
      "nautilus.io/linstor": "true"
    resources:
      limits:
        cpu: "2"
        memory: 1Gi
      requests:
        cpu: 100m
        memory: 512Mi
    # We set this in hub/values, but we should unset it on Nautilus
    networkPolicy:
      enabled: false
      egress: null
    config:
      OAuthenticator:
        allow_all: False
        allowed_groups:
          # CDSS Discovery 2026 Fall
          - "course::1557896"
          # CDSS Discovery 2026 Spring
          - "course::1552431"
          ## CDSS Discovery Partners
          - "course::1549362"
          # DataHub staff
          - "course::1524699::group::all-admins"
          # People who want to see what the hub can do
          - "course::1524699::group::cdss-discovery-observers"
      Spawner:
        spawn_launcher_timer_message: "Server launch is waiting for available resources."
    loadRoles:
      # datahub staff
      datahub-staff:
        description: Enable admin for datahub staff
        # this role provides permissions to...
        scopes:
          - admin-ui
          - admin:groups
          - admin:users
          - admin:servers
          - read:roles
          - read:hub
          - access:servers
        # this role will be assigned to...
        groups:
          - course::1524699::group::all-admins

  singleuser:
    image:
      pullPolicy: IfNotPresent
    #  name: gitlab-registry.nrp-nautilus.io/berkeley-cdss/cdss-discovery-user-image
    #  tag: latest

    # Nautilus-specific configuration
    uid: 0
    fsGid: 100
    extraEnv:
      GRANT_SUDO: "yes"
      # Unset NotebookApp from hub/values. Necessary for recent lab versions.
      JUPYTERHUB_SINGLEUSER_APP: "jupyter_server.serverapp.ServerApp"
    defaultUrl: /lab
    extraPodConfig:
      securityContext:
          fsGroupChangePolicy: "OnRootMismatch"
          fsGroup: 100
    cloudMetadata:
      blockWithIptables: false
    networkPolicy:
      enabled: false
    # /Nautilus-specific configuration
    extraFiles:
      # DH-216
      remove-exporters:
        mountPath: /etc/jupyter/jupyter_notebook_config.py
        stringData: |
          c.QtPDFExporter.enabled = False
          c.QtPNGExporter.enabled = False
          c.WebPDFExporter.enabled = False

    # Nautilus-specific configuration
    storage:
      type: dynamic
      extraLabels: {}
      extraVolumes: {}
      extraVolumeMounts: {}
      capacity: 20Gi
      homeMountPath: /home/jovyan
      dynamic:
        storageClass: rook-ceph-block
        pvcNameTemplate: claim-{username}{servername}
        volumeNameTemplate: volume-{username}{servername}
        storageAccessModes: [ReadWriteOnce]
    # /Nautilus-specific configuration

    startTimeout: 3600

    # Policy on interactive limits
    # https://docs.nationalresearchplatform.org/userdocs/start/policies/#interactive-use-vs-batch
    cpu:
      guarantee: 2
      limit: 10
      #limit: 16
    memory:
      guarantee: 10G
      limit: 10G
      #limit: 32G
    extraResource:
      # The gpu request must equal the limit
      guarantees:
        nvidia.com/gpu: "1"
      limits:
        nvidia.com/gpu: "1"

    profileList:
    # CPU-only profile
    - display_name: "CPU Server"
      description: "Choose your region, CPU cores, memory, and container image (no GPU)"
      slug: "cpu-server"
      kubespawner_override:
        mem_limit: "10G"
        cpu_guarantee: 1
        cpu_limit: 1
        extra_resource_guarantees:
          nvidia.com/gpu: "0"
        extra_resource_limits:
          nvidia.com/gpu: "0"
        image: gitlab-registry.nrp-nautilus.io/nrp/scientific-images/python:latest
      profile_options:
        region: &region_option
          display_name: "Region"
          description: "Note: Storage is located in us-west. Other regions may have slower I/O performance."
          choices:
            any:
              default: true
              display_name: "Any"
              kubespawner_override: {}
            west:
              display_name: "West"
              kubespawner_override:
                node_affinity_required:
                  - matchExpressions:
                    - key: topology.kubernetes.io/region
                      operator: In
                      values: ["us-west"]
            mountain:
              display_name: "Mountain"
              kubespawner_override:
                node_affinity_required:
                  - matchExpressions:
                    - key: topology.kubernetes.io/region
                      operator: In
                      values: ["us-mountain"]
            central:
              display_name: "Central"
              kubespawner_override:
                node_affinity_required:
                  - matchExpressions:
                    - key: topology.kubernetes.io/region
                      operator: In
                      values: ["us-central"]
            east:
              display_name: "East"
              kubespawner_override:
                node_affinity_required:
                  - matchExpressions:
                    - key: topology.kubernetes.io/region
                      operator: In
                      values: ["us-east"]
        cpu_cores: &cpu_cores_option
          display_name: "CPU Cores"
          choices:
            cpu_1:
              default: true
              display_name: "1"
              kubespawner_override:
                cpu_guarantee: 1
                cpu_limit: 1
            cpu_2:
              display_name: "2"
              kubespawner_override:
                cpu_guarantee: 2
                cpu_limit: 2
            cpu_4:
              display_name: "4"
              kubespawner_override:
                cpu_guarantee: 4
                cpu_limit: 4
            cpu_8:
              display_name: "8"
              kubespawner_override:
                cpu_guarantee: 8
                cpu_limit: 8
        image: &image_option
          display_name: "Container Image"
          description: "Select a container image (You can also enter a custom image below)"
          choices:
            discovery:
              default: true
              display_name: "NRP Python"
              kubespawner_override:
                image: "gitlab-registry.nrp-nautilus.io/nrp/scientific-images/python:latest"
            cuda:
              display_name: "NRP CUDA (GPU optimized)"
              kubespawner_override:
                image: "gitlab-registry.nrp-nautilus.io/nrp/scientific-images/python:cuda-latest"
            tensorflow:
              display_name: "NRP Tensorflow (GPU optimized)"
              kubespawner_override:
                image: "gitlab-registry.nrp-nautilus.io/nrp/scientific-images/python:tensorflow-latest"
            tensorflow_cuda:
              display_name: "NRP Tensorflow CUDA (GPU optimized)"
              kubespawner_override:
                image: "gitlab-registry.nrp-nautilus.io/nrp/scientific-images/python:tensorflow-cuda-latest"
            pytorch:
              display_name: "NRP PyTorch"
              kubespawner_override:
                image: "gitlab-registry.nrp-nautilus.io/nrp/scientific-images/python:fall25_updates"
            rstudio:
              display_name: "NRP RStudio"
              kubespawner_override:
                image: "gitlab-registry.nrp-nautilus.io/nrp/scientific-images/rstudio:v1.6.0"
            desktop:
              display_name: "NRP Desktop"
              kubespawner_override:
                image: "gitlab-registry.nrp-nautilus.io/nrp/scientific-images/desktop/selkies:v1.6.0"
          unlisted_choice:
            enabled: true
            display_name: "Publicly Accessible Container Image (e.g. quay.io/my-project/my-image:tag)"
            display_name_in_choices: "Custom Image"
            validation_regex: "^.+:.+$"
            validation_message: "Must be a publicly available container image"
            kubespawner_override:
              image: "{value}"
        mem_limit: &mem_limit_option
          display_name: "Memory Limit"
          choices:
            mem_10g:
              default: true
              display_name: "10G"
              kubespawner_override:
                mem_limit: "10G"
            mem_16g:
              display_name: "16G"
              kubespawner_override:
                mem_limit: "16G"
            mem_24g:
              display_name: "24G"
              kubespawner_override:
                mem_limit: "24G"
            mem_32g:
              display_name: "32G"
              kubespawner_override:
                mem_limit: "32G"
    
    # GPU-enabled profile
    - display_name: "GPU Server"
      description: "Choose your region, GPU type, CPU cores, memory, and container image"
      slug: "gpu-server"
      kubespawner_override:
        mem_limit: "10G"
        cpu_guarantee: 1
        cpu_limit: 1
        extra_resource_guarantees:
          nvidia.com/gpu: "1"
        extra_resource_limits:
          nvidia.com/gpu: "1"
        image: gitlab-registry.nrp-nautilus.io/nrp/scientific-images/python:cuda-latest
      profile_options:
        region: *region_option
        gpu_type:
          display_name: "GPU Type"
          choices:
            any:
              default: true
              display_name: "Any general"
              kubespawner_override:
                node_affinity_required:
                  - matchExpressions:
                    - key: nvidia.com/gpu.product
                      operator: NotIn
                      values:
                        - "NVIDIA-A40"
                        - "NVIDIA-RTX-A6000"
                        - "Quadro-RTX-8000"
                        # Exclude A100 variants
                        - "NVIDIA-A100-80GB-PCIe"
                        - "NVIDIA-A100-PCIE-40GB"
                        - "NVIDIA-A100-SXM4-80GB"
            l40:
              display_name: "NVIDIA L40 (48GB)"
              kubespawner_override:
                node_affinity_required:
                  - matchExpressions:
                    - key: nvidia.com/gpu.product
                      operator: In
                      values: ["NVIDIA-L40"]
            v100:
              display_name: "NVIDIA V100 (32GB)"
              kubespawner_override:
                node_affinity_required:
                  - matchExpressions:
                    - key: nvidia.com/gpu.product
                      operator: In
                      values: ["Tesla-V100-SXM2-32GB"]
        gpu_count:
          display_name: "GPU Count"
          choices:
            gpu_1:
              default: true
              display_name: "1 GPU"
              kubespawner_override:
                extra_resource_guarantees:
                  nvidia.com/gpu: "1"
                extra_resource_limits:
                  nvidia.com/gpu: "1"
        cpu_cores: *cpu_cores_option
        image:
          display_name: "Container Image"
          description: "Select a container image (You can also enter a custom image below)"
          choices:
            cuda:
              default: true
              display_name: "NRP CUDA (GPU optimized)"
              kubespawner_override:
                image: "gitlab-registry.nrp-nautilus.io/nrp/scientific-images/python:cuda-latest"
            discovery:
              display_name: "NRP Python"
              kubespawner_override:
                image: "gitlab-registry.nrp-nautilus.io/nrp/scientific-images/python:latest"
            tensorflow:
              display_name: "NRP Tensorflow (GPU optimized)"
              kubespawner_override:
                image: "gitlab-registry.nrp-nautilus.io/nrp/scientific-images/python:tensorflow-latest"
            tensorflow_cuda:
              display_name: "NRP Tensorflow CUDA (GPU optimized)"
              kubespawner_override:
                image: "gitlab-registry.nrp-nautilus.io/nrp/scientific-images/python:tensorflow-cuda-latest"
            pytorch:
              display_name: "NRP PyTorch"
              kubespawner_override:
                image: "gitlab-registry.nrp-nautilus.io/nrp/scientific-images/python:fall25_updates"
            rstudio:
              display_name: "NRP RStudio"
              kubespawner_override:
                image: "gitlab-registry.nrp-nautilus.io/nrp/scientific-images/rstudio:v1.6.0"
            desktop:
              display_name: "NRP Desktop"
              kubespawner_override:
                image: "gitlab-registry.nrp-nautilus.io/nrp/scientific-images/desktop/selkies:v1.6.0"
          unlisted_choice:
            enabled: true
            display_name: "Publicly Accessible Container Image (e.g. quay.io/my-project/my-image:tag)"
            display_name_in_choices: "Custom Image"
            validation_regex: "^.+:.+$"
            validation_message: "Must be a publicly available container image"
            kubespawner_override:
              image: "{value}"
        mem_limit: *mem_limit_option
  #custom:
  #  group_profiles:
      ## CDSS Discovery 2025 Fall, Stellar group
      #course::1549326::group::2025-fall-stellar:
      #  extraVolumes:
      #    - name: 2025-fall-stellar
      #      persistentVolumeClaim:
      #        claimName: 2025-fall-stellar
      #  extraVolumeMounts:
      #    - name: 2025-fall-stellar
      #      mountPath: /home/jovyan/_shared/2025-fall-stellar
      #      readOnly: true
      ## CDSS Discovery 2025 Fall Partners, Stellar group
      #course::1549362::group::2025-fall-stellar:
      #  extraVolumes:
      #    - name: 2025-fall-stellar
      #      persistentVolumeClaim:
      #        claimName: 2025-fall-stellar
      #  extraVolumeMounts:
      #    - name: 2025-fall-stellar
      #      mountPath: /home/jovyan/_shared/2025-fall-stellar
      #      readOnly: true
      # CDSS Discovery 2025 Fall, instructors
      #course::1549326::enrollment_type::teacher:
      #  extraVolumes:
      #    - name: 2025-fall-stellar
      #      persistentVolumeClaim:
      #        claimName: 2025-fall-stellar
      #  extraVolumeMounts:
      #    - name: 2025-fall-stellar
      #      mountPath: /home/jovyan/_shared/2025-fall-stellar
      #      readOnly: false
      ## DataHub staff
      #course::1524699::group::all-admins:
      #  extraVolumes:
      #    - name: 2025-fall-stellar
      #      persistentVolumeClaim:
      #        claimName: 2025-fall-stellar
      #  extraVolumeMounts:
      #    - name: 2025-fall-stellar
      #      mountPath: /home/jovyan/_shared/2025-fall-stellar
      #      readOnly: false
