nfsPVC:
  enabled: true
  nfs:
    serverIP: 10.85.53.250

jupyterhub:
  ingress:
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
  scheduling:
    userScheduler:
      nodeSelector:
        hub.jupyter.org/pool-name: core-pool-2024-05-08
  proxy:
    chp:
      nodeSelector:
        hub.jupyter.org/pool-name: core-pool-2024-05-08
      resources:
        requests:
          # FIXME: We want no guarantees here!!!
          # This is lowest possible value
          cpu: 0.001
          memory: 3Gi
        limits:
          memory: 3Gi

  hub:
    nodeSelector:
      hub.jupyter.org/pool-name: core-pool-2024-05-08
    config:
      OAuthenticator:
        allow_all: False
        allowed_groups:
          # Data 100, Summer 2025
          # https://bcourses.berkeley.edu/courses/1545289
          - "course::1545289"
          # Data 100, Fall 2025
          # https://bcourses.berkeley.edu/courses/1547854
          - "course::1547854"
          # Data 100, Spring 2026
          # https://bcourses.berkeley.edu/courses/1551658
          - "course::1551658"
          # DataHub staff
          - "course::1524699::group::all-admins"
    loadRoles:
      # datahub staff
      datahub-staff:
        description: Enable admin for datahub staff
        # this role provides permissions to...
        scopes:
          - admin-ui
          - admin:groups
          - admin:users
          - admin:servers
          - read:roles
          - read:hub
          - access:servers
        # this role will be assigned to...
        groups:
          - course::1524699::group::all-admins
  singleuser:
    image:
      name: us-central1-docker.pkg.dev/ucb-datahub-2018/user-images/data100-user-image
      tag: 583857c00b57
    extraFiles:
      # DH-544
      jupyter-lab-overrides:
        mountPath:  /srv/conda/envs/notebook/share/jupyter/lab/settings/overrides.json
        stringData:  |
          {
            "@jupyterlab/notebook-extension:tracker": {
              "windowingMode": "defer"
            }
          } 
      # DH-305
      remove-exporters:
        mountPath: /etc/jupyter/jupyter_notebook_config.py
        stringData: |
          c.QtPDFExporter.enabled = False
          c.QtPNGExporter.enabled = False
          c.WebPDFExporter.embed_images = True
    defaultUrl: "/lab"
    extraEnv:
      GH_SCOPED_CREDS_CLIENT_ID: Iv1.f79b4903c7ea2847
      GH_SCOPED_CREDS_APP_URL: https://github.com/apps/data100-berkeley-datahub-access
      # Unset NotebookApp from hub/values. Necessary for recent lab versions.
      JUPYTERHUB_SINGLEUSER_APP: "jupyter_server.serverapp.ServerApp"
    nodeSelector:
      hub.jupyter.org/pool-name: data100-pool
    storage:
      type: static
      static:
        pvcName: home-nfs-v3
        subPath: "{username}"
    memory:
      guarantee: 2G
      limit: 4G
    
  # custom:
    # bcourses_shared:
      # 2026-spring:
        # - "course::1551658"
