nfsPVC:
  enabled: true
  nfs:
    serverIP: 10.170.213.154

jupyterhub:
  ingress:
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
  scheduling:
    userScheduler:
      nodeSelector:
        hub.jupyter.org/pool-name: core-pool-2024-05-08
  proxy:
    chp:
      nodeSelector:
        hub.jupyter.org/pool-name: core-pool-2024-05-08
      resources:
        requests:
          # FIXME: We want no guarantees here!!!
          # This is lowest possible value
          cpu: 0.001
          memory: 3Gi
        limits:
          memory: 3Gi

  hub:
    nodeSelector:
      hub.jupyter.org/pool-name: core-pool-2024-05-08
    config:
      OAuthenticator:
        allow_all: False
        allowed_groups:
          # Data 100, Spring 2025
          # https://bcourses.berkeley.edu/courses/1541798
          - "course::1541798"
          # Data 100, Fall 2025
          # https://bcourses.berkeley.edu/courses/1547854
          - "course::1547854"
          # DataHub staff
          - "course::1524699::group::all-admins"
    loadRoles:
      # datahub staff
      datahub-staff:
        description: Enable admin for datahub staff
        # this role provides permissions to...
        scopes:
          - admin-ui
          - admin:groups
          - admin:users
          - admin:servers
          - read:roles
          - read:hub
          - access:servers
        # this role will be assigned to...
        groups:
          - course::1524699::group::all-admins
      course-staff-1547854:
        ## Course: Data C100 Bcourses ID: 1547854 End Date: 01/01/2026 
        ## See issue https://github.com/berkeley-dsep-infra/datahub/issues/7497 for more details.
        description: Enable course staff to view and access servers.
        scopes:
          - admin-ui
          - list:users!group=course::1547854
          - admin:servers!group=course::1547854
          - access:servers!group=course::1547854
        groups:
          - course::1547854::enrollment_type::teacher
          - course::1547854::enrollment_type::ta

# This configuration block is used to enable elevated privileges for teachers and TAs in Data100 hub
       #Data 100, Semester/Year, https://github.com/berkeley-dsep-infra/datahub/issues/6458
      #course-staff-1537664:
      #  description: Enable course staff to view and access servers.
        # this role provides permissions to...
       # scopes:
        #  - admin-ui
        #  - list:users!group=course::1537664
        #  - admin:servers!group=course::1537664
        #  - access:servers!group=course::1537664
        # this role will be assigned to...
        #groups:
         # - course::1537664::group::Admins

#  prePuller:
#    extraImages:
#      postgres:
#        name: gcr.io/ucb-datahub-2018/jupyterhub-postgres
#        tag: 0.0.1-n3657.h4f7f88c

  singleuser:
    image:
      name: us-central1-docker.pkg.dev/ucb-datahub-2018/user-images/data100-user-image
      tag: e42566aba1dd
    extraFiles:
      # DH-544
      jupyter-lab-overrides:
        mountPath:  /srv/conda/envs/notebook/share/jupyter/lab/settings/overrides.json
        stringData:  |
          {
            "@jupyterlab/notebook-extension:tracker": {
              "windowingMode": "defer"
            }
          } 
      # DH-305
      remove-exporters:
        mountPath: /etc/jupyter/jupyter_notebook_config.py
        stringData: |
          c.QtPDFExporter.enabled = False
          c.QtPNGExporter.enabled = False
          c.WebPDFExporter.embed_images = True
    defaultUrl: "/lab"
    extraEnv:
      GH_SCOPED_CREDS_CLIENT_ID: Iv1.f79b4903c7ea2847
      GH_SCOPED_CREDS_APP_URL: https://github.com/apps/data100-berkeley-datahub-access
      # Unset NotebookApp from hub/values. Necessary for recent lab versions.
      JUPYTERHUB_SINGLEUSER_APP: "jupyter_server.serverapp.ServerApp"
    nodeSelector:
      hub.jupyter.org/pool-name: data100-pool
    storage:
      type: static
      static:
        pvcName: home-nfs-v3
        subPath: "{username}"
    memory:
      guarantee: 2G
      limit: 4G
    image: {}

# The below section is for adding shared directories in Data100 Hub.

# custom:
#   group_profiles:
#     # Teacher Configuration
#     # This configuration sets up directory access for teachers in the course.
#     course::1541798::enrollment_type::teacher:
#       extraVolumeMounts:
#         - name: home
#           # Path where teachers have read/write access.
#           mountPath: /home/jovyan/_shared/data100-readwrite
#           # Sub-path within filesystem for teacher access.
#           subPath: _shared/2025-spring/courses/1541798
#           # Set to false to enable write access for teachers.
#           readOnly: false

#     # Teaching Assistant (TA) Configuration
#     # This configuration sets up directory access for TAs in the course.
#     course::1541798::enrollment_type::ta:
#       extraVolumeMounts:
#         - name: home
#           # Path where TAs have read/write access.
#           mountPath: /home/jovyan/_shared/data100-readwrite
#           # Sub-path within filesystem for TA access.
#           subPath: _shared/2025-spring/courses/1541798
#           # Set to false to enable write access for TAs.
#           readOnly: false

#     # Student Configuration
#     # This configuration sets up directory access for students in the course.
#     course::1541798::enrollment_type::student:
#       extraVolumeMounts:
#         - name: home
#           # Path where students have read-only access.
#           mountPath: /home/jovyan/_shared/data100-readonly
#           # Sub-path within filesystem for student access.
#           subPath: _shared/2025-spring/courses/1541798
#           # Set to true to restrict write access for students.
#           readOnly: true
  custom:
    group_profiles:
      course::1547854::enrollment_type::teacher:
      ## Course Name: bcourses-1547854 Bcourses ID: 1547854 End Date: 12/19/2025
      ## See issue https://github.com/berkeley-dsep-infra/datahub/issues/7542 for details.
        extraVolumeMounts:
          - name: home
            mountPath: /home/jovyan/_shared/bcourses-1547854-readwrite
            subPath: _shared/2025-fall/courses/1547854
            readOnly: false
          - name: home
            mountPath: /home/jovyan/_shared/bcourses-1547854-readonly
            subPath: _shared/2025-fall/courses/1547854
            readOnly: true
      course::1547854::enrollment_type::ta:
      ## Course Name: bcourses-1547854 Bcourses ID: 1547854 End Date: 12/19/2025
      ## See issue https://github.com/berkeley-dsep-infra/datahub/issues/7542 for details.
        extraVolumeMounts:
          - name: home
            mountPath: /home/jovyan/_shared/bcourses-1547854-readwrite
            subPath: _shared/2025-fall/courses/1547854
            readOnly: false
          - name: home
            mountPath: /home/jovyan/_shared/bcourses-1547854-readonly
            subPath: _shared/2025-fall/courses/1547854
            readOnly: true
      course::1547854::enrollment_type::student:
      ## Course Name: bcourses-1547854 Bcourses ID: 1547854 End Date: 12/19/2025
      ## See issue https://github.com/berkeley-dsep-infra/datahub/issues/7542 for details.
        extraVolumeMounts:
          - name: home
            mountPath: /home/jovyan/_shared/bcourses-1547854-readonly
            subPath: _shared/2025-fall/courses/1547854
            readOnly: true
