nfsPVC:
  enabled: true
  nfs:
    serverIP: 10.85.53.250

jupyterhub:
  ingress:
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
  scheduling:
    userScheduler:
      nodeSelector:
        hub.jupyter.org/pool-name: core-pool-2024-05-08
  proxy:
    chp:
      nodeSelector:
        hub.jupyter.org/pool-name: core-pool-2024-05-08
      resources:
        requests:
          # FIXME: We want no guarantees here!!!
          # This is lowest possible value
          cpu: 0.001
          memory: 3Gi
        limits:
          memory: 3Gi

  hub:
    nodeSelector:
      hub.jupyter.org/pool-name: core-pool-2024-05-08
    config:
      OAuthenticator:
        allow_all: False
        allowed_groups:
          # Data 100, Summer 2025
          # https://bcourses.berkeley.edu/courses/1545289
          - "course::1545289"
          # Data 100, Fall 2025
          # https://bcourses.berkeley.edu/courses/1547854
          - "course::1547854"
          # Data 100, Spring 2026
          # https://bcourses.berkeley.edu/courses/1551658
          - "course::1551658"
          # DataHub staff
          - "course::1524699::group::all-admins"
    loadRoles:
      # datahub staff
      datahub-staff:
        description: Enable admin for datahub staff
        # this role provides permissions to...
        scopes:
          - admin-ui
          - admin:groups
          - admin:users
          - admin:servers
          - read:roles
          - read:hub
          - access:servers
        # this role will be assigned to...
        groups:
          - course::1524699::group::all-admins
      course-staff-1551658:
        ## Course: Data C100 Bcourses ID: 1551658 End Date: 05/31/2025 
        ## See issue https://github.com/berkeley-dsep-infra/datahub/issues/7857 for more details.
        description: Enable course staff to view and access servers.
        scopes:
          - admin-ui
          - list:users!group=course::1551658
          - admin:servers!group=course::1551658
          - access:servers!group=course::1551658
        groups:
          - course::1551658::enrollment_type::teacher
          - course::1551658::enrollment_type::ta
  singleuser:
    image:
      name: us-central1-docker.pkg.dev/ucb-datahub-2018/user-images/data100-user-image
      tag: 6cc6511c9fde
    extraFiles:
      # DH-544
      jupyter-lab-overrides:
        mountPath:  /srv/conda/envs/notebook/share/jupyter/lab/settings/overrides.json
        stringData:  |
          {
            "@jupyterlab/notebook-extension:tracker": {
              "windowingMode": "defer"
            }
          } 
      # DH-305
      remove-exporters:
        mountPath: /etc/jupyter/jupyter_notebook_config.py
        stringData: |
          c.QtPDFExporter.enabled = False
          c.QtPNGExporter.enabled = False
          c.WebPDFExporter.embed_images = True
    defaultUrl: "/lab"
    extraEnv:
      GH_SCOPED_CREDS_CLIENT_ID: Iv1.f79b4903c7ea2847
      GH_SCOPED_CREDS_APP_URL: https://github.com/apps/data100-berkeley-datahub-access
      # Unset NotebookApp from hub/values. Necessary for recent lab versions.
      JUPYTERHUB_SINGLEUSER_APP: "jupyter_server.serverapp.ServerApp"
    nodeSelector:
      hub.jupyter.org/pool-name: data100-pool
    storage:
      type: static
      static:
        pvcName: home-nfs-v3
        subPath: "{username}"
    memory:
      guarantee: 2G
      limit: 4G
    

# The below section is for adding shared directories in Data100 Hub.

# custom:
#   group_profiles:
#     # Teacher Configuration
#     # This configuration sets up directory access for teachers in the course.
#     course::1541798::enrollment_type::teacher:
#       extraVolumeMounts:
#         - name: home
#           # Path where teachers have read/write access.
#           mountPath: /home/jovyan/_shared/data100-readwrite
#           # Sub-path within filesystem for teacher access.
#           subPath: _shared/2025-spring/courses/1541798
#           # Set to false to enable write access for teachers.
#           readOnly: false

#     # Teaching Assistant (TA) Configuration
#     # This configuration sets up directory access for TAs in the course.
#     course::1541798::enrollment_type::ta:
#       extraVolumeMounts:
#         - name: home
#           # Path where TAs have read/write access.
#           mountPath: /home/jovyan/_shared/data100-readwrite
#           # Sub-path within filesystem for TA access.
#           subPath: _shared/2025-spring/courses/1541798
#           # Set to false to enable write access for TAs.
#           readOnly: false

#     # Student Configuration
#     # This configuration sets up directory access for students in the course.
#     course::1541798::enrollment_type::student:
#       extraVolumeMounts:
#         - name: home
#           # Path where students have read-only access.
#           mountPath: /home/jovyan/_shared/data100-readonly
#           # Sub-path within filesystem for student access.
#           subPath: _shared/2025-spring/courses/1541798
#           # Set to true to restrict write access for students.
#           readOnly: true
