nfsPVC:
  enabled: true
  nfs:
    serverIP: 10.185.238.42

jupyterhub:
  prePuller:
    continuous:
      # Same image as datahub, so no continouus pre-puller needed
      enabled: false
  cull:
    # Cull after 30min of inactivity
    every: 300
    timeout: 1800
    # No pods over 12h long, no workshop is gonna be more than that :)
    maxAge: 43200
  ingress:
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod

  scheduling:
    userScheduler:
      nodeSelector:
        hub.jupyter.org/pool-name: core-pool-2024-05-08
  hub:
    # No more than 200 users at any given time
    activeServerLimit: 200
    nodeSelector:
      hub.jupyter.org/pool-name: core-pool-2024-05-08
    config:
      JupyterHub:
        admin_access: true
        authenticator_class: dummy
      Authenticator:
        manage_groups: false
        admin_users:
          # infrastructure
          - rylo
          - sknapp
          - felder
          - balajialwar
          - gmerritt
          - eric_vandusen@berkeley.edu
          - yijunge
  proxy:
    chp:
      nodeSelector:
        hub.jupyter.org/pool-name: core-pool-2024-05-08
    traefik:
      nodeSelector:
        hub.jupyter.org/pool-name: core-pool-2024-05-08
  singleuser:
    image:
      name: us-central1-docker.pkg.dev/ucb-datahub-2018/user-images/datahub-user-image
      tag: 7f6ed21913b9
    extraEnv:
      # Unset NotebookApp from hub/values. Necessary for recent lab versions.
      JUPYTERHUB_SINGLEUSER_APP: "jupyter_server.serverapp.ServerApp"
    nodeSelector:
      # Co-locate with datahub, since workshop shares its image
      hub.jupyter.org/pool-name: datahub-pool
    storage:
      type: static
      static:
        pvcName: home-nfs-v3
        subPath: "{username}"
    memory:
      # As low a guarantee as possible
      guarantee: 512M
      limit: 512M
