#!/usr/bin/env bash
set -eux

# install mongosh for DH-160

mkdir -p /tmp/mongosh
cd /tmp/mongosh
wget https://downloads.mongodb.com/compass/mongosh-2.0.2-linux-x64.tgz
tar xvfz mongosh-2.0.2-linux-x64.tgz
cp -v mongosh-2.0.2-linux-x64/bin/mongosh ${CONDA_DIR}/bin/
cp -v mongosh-2.0.2-linux-x64/bin/mongosh_crypt_v1.so ${CONDA_DIR}/lib/
chmod 775 ${CONDA_DIR}/bin/mongosh
chmod 775 ${CONDA_DIR}/lib/mongosh_crypt_v1.so
cd /
rm -rf /tmp/mongosh

# install mongodb-tools for DH-165
whoami
mkdir -p /tmp/mongodb-tools
cd /tmp/mongodb-tools
wget https://fastdl.mongodb.org/tools/db/mongodb-database-tools-ubuntu2204-x86_64-100.9.0.deb
sudo apt install ./mongodb-database-tools-ubuntu2204-x86_64-100.9.0.deb
cd /
rm -rf /tmp/mongodb-tools
