nfsPVC:
  enabled: true
  nfs:
    serverIP: 172.16.174.58

jupyterhub:
  ingress:
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
  scheduling:
    userScheduler:
      nodeSelector:
        hub.jupyter.org/pool-name: core-pool-2024-05-08
  proxy:
    chp:
      nodeSelector:
        hub.jupyter.org/pool-name: core-pool-2024-05-08
    traefik:
      nodeSelector:
        hub.jupyter.org/pool-name: core-pool-2024-05-08

  hub:
    nodeSelector:
      hub.jupyter.org/pool-name: core-pool-2024-05-08

    config:
    loadRoles:
      # datahub staff
      datahub-staff:
        description: Enable admin for datahub staff
        # this role provides permissions to...
        scopes:
          - admin-ui
          - admin:groups
          - admin:users
          - admin:servers
          - read:roles
          - read:hub
          - access:servers
        # this role will be assigned to...
        groups:
          - course::1524699::group::all-admins
      # biology admins
      biology-admins:
        description: Enable departmental folks to view and access all servers.
        # this role provides permissions to...
        scopes:
          - admin-ui
          - list:users
          - admin:servers
          - access:servers
        # this role will be assigned to...
        groups:
          - course::1524699::group::biology-admins
  custom:
    group_profiles:
      # DataHub Infrastructure staff
      # https://bcourses.berkeley.edu/courses/1524699/groups#tab-80607
      course::1524699::group::all-admins:
        mem_limit: 4096M
        mem_guarantee: 4096M
        extraVolumeMounts:
          - name: home
            mountPath: /home/jovyan/shared-readwrite
            subPath: _shared

      course::1547808::enrollment_type::teacher:
      ## Course Name: bcourses-1547808 Bcourses ID: 1547808 End Date: 01/15/2026
      ## See issue https://github.com/berkeley-dsep-infra/datahub/issues/7382 for details.
        extraVolumeMounts:
          - name: home
            mountPath: /home/jovyan/_shared/bcourses-1547808-readwrite
            subPath: _shared/2025-fall/courses/1547808
            readOnly: false
      course::1547808::enrollment_type::ta:
      ## Course Name: bcourses-1547808 Bcourses ID: 1547808 End Date: 01/15/2026
      ## See issue https://github.com/berkeley-dsep-infra/datahub/issues/7382 for details.
        extraVolumeMounts:
          - name: home
            mountPath: /home/jovyan/_shared/bcourses-1547808-readwrite
            subPath: _shared/2025-fall/courses/1547808
            readOnly: false
      course::1547808::enrollment_type::student:
      ## Course Name: bcourses-1547808 Bcourses ID: 1547808 End Date: 01/15/2026
      ## See issue https://github.com/berkeley-dsep-infra/datahub/issues/7382 for details.
        extraVolumeMounts:
          - name: home
            mountPath: /home/jovyan/_shared/bcourses-1547808-readonly
            subPath: _shared/2025-fall/courses/1547808
            readOnly: true
      course::1547808:
        ## Course Name: 2025 Fall, MCELLBI 201B Bcourses ID: 1547808 End Date: 12/05/2025
        ## See issue https://github.com/berkeley-dsep-infra/datahub/issues/7395 for details.
        mem_limit: 5G
        mem_guarantee: 5G
  singleuser:
    image:
      name: us-central1-docker.pkg.dev/ucb-datahub-2018/user-images/biology-user-image
      tag: ee6766b2c326
    extraEnv:
      # Unset NotebookApp from hub/values. Necessary for recent lab versions.
      JUPYTERHUB_SINGLEUSER_APP: "jupyter_server.serverapp.ServerApp"
    extraFiles:
      # DH-305
      remove-exporters:
        mountPath: /etc/jupyter/jupyter_notebook_config.py
        stringData: |
          c.QtPDFExporter.enabled = False
          c.QtPNGExporter.enabled = False
          c.WebPDFExporter.embed_images = True
      git-credential-helper:
        mountPath: /srv/conda/etc/gitconfig
        stringData: |
          [credential "https://github.com"]
            helper = !git-credential-github-app --app-key-file /srv/conda/etc/github/github-app-private-key.pem --app-id 229235
            useHttpPath = true
      git-credential-helper-private-key:
        mountPath: /srv/conda/etc/github/github-app-private-key.pem
        # data in secret file

    nodeSelector:
      hub.jupyter.org/pool-name: biology-pool
    storage:
      type: static
      static:
        pvcName: home-nfs-v3
        subPath: "{username}"
      extraVolumeMounts:
        - name: home
          mountPath: /home/jovyan/shared
          subPath: _shared
          readOnly: true
    memory:
      guarantee: 2056M
      limit: 4G
    cpu:
      # Biology hub users can consume quite a bit of CPU at times, starving out other
      # users on the nodes. So we reduce the max amount of CPU available to them, from 7
      # (defined in hub/values.yaml) to 4.
      limit: 4
