jupyterhub:
    hub:
        config:
            CanvasOAuthenticator:
                client_id: ENC[AES256_GCM,data:Tq1rKfa5PqBcX4G/1Kdx0XQ=,iv:9+gmQN5ibaUtms2xPDtyFHh4OhMLkSl2rzHYyYjHsyo=,tag:C4iQIJwnsBKXdvu+nOtPBQ==,type:str]
                client_secret: ENC[AES256_GCM,data:WkinTxMrcqcvgc/NUsVPN8WtUa1q6tcQZoGra7y8pjoHaMQyFP7N3zOOPuj4bHInZ1DeeYx3bnF3WGbfJq+ADQ==,iv:5r04ltrviwkblPl2WheNgC3KCSgAVVmFzPxu/T/s3gA=,tag:7vH/Fcs8hHuAxo+fPXthmg==,type:str]
                oauth_callback_url: ENC[AES256_GCM,data:4bDqXOmeX4ie38yGkjpvncl7o47DXUHFm7hnuadRI/jLXUszcUbmB6laPgIB3qj+T9omvQ==,iv:+x3TIbCVn39GvLjWtTqpcpoTeoTS8O5ZfRqzyo+WVgQ=,tag:nDaHNf/7uMZ2gVAm1HS7DQ==,type:str]
        services:
            grouper-sync:
                name: ENC[AES256_GCM,data:c+siqqZw+FuO/gLo,iv:W7ogWPU+oIA4b9NazqlhvsOTzsmIlJx8022tqQIxn9s=,tag:YdgsiKmCkMhwQ4hjdleq+w==,type:str]
                command:
                    - ENC[AES256_GCM,data:kUDO8xwuKdB3aX65,iv:hT91tiYtiXS3HdPdE3vg+/ckeD7F4CcvexONlqmiGIk=,tag:U0iTbYdv5fNKl+Aytcn/KQ==,type:str]
                    - ENC[AES256_GCM,data:Kr6txHqNpL2b2JliAwVTKlQDwGrCfu2a15k=,iv:j/Pz9lwLAFRK3ag1witr1kmDHKTsMKEQJ56dZ6PaK2Y=,tag:y4AUYgEqt60EmmTCZP7Tyw==,type:str]
                    - ENC[AES256_GCM,data:a5pJ5a0yUzvBuBPH4W/oU60ZeDvmwiBrcmXQcH8lcU0=,iv:wRhIpUZPgRXdwoP5hC4qzeIT2+MRFrfP4aVZf3ob5B4=,tag:kvep3TDZYIblFrrTNjI5bg==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/ucb-datahub-2018/locations/global/keyRings/datahub/cryptoKeys/sops
          created_at: "2026-05-08T23:32:25Z"
          enc: CiUA67O9AOli6+qPT4HfeDHwcSvN2/eqw/NiJhHb2DLC6tTMJ31gEkkAdEnSzgN+WtFQtD7PDq9W39kpoAc0eetPpnMAm/dm/kwcNh/zkEvm3BDle/reTmHzzlUyaqyAL95DV0YoXMsfRQnQM7Ht0O2F
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-05-08T23:32:25Z"
    mac: ENC[AES256_GCM,data:SGgTv95or2PMfD5LvP22YFc6+FzRnO2YkqnVVAMBk+zHVpWEEG8t9PT3k5J8jsWp4X2Rg0qQeC53rKd+wQ0qp6ZWUFBx3d+Tz44wTKWz5pkS1ikUENW+CcnuvJYY/BfzJ5oY8hzNzxG5iPSon/R0urUYzPID1EyFu+QbYzYOu0g=,iv:gPZ4no4/0EDN9r893CPjDVp1e+EBDhPanEtCpafuKFg=,tag:h5DGPo9o2K6lqNn8wxAjeA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
