jupyterhub:
    hub:
        config:
            CanvasOAuthenticator:
                client_id: ENC[AES256_GCM,data:yi0yoiNScpTo3CfCAzeq70s=,iv:3wtv6qBxwDfpPlhNytEFBcgiBK/O3fXtsux7XLYYBlQ=,tag:z4qRLLQVrOCANbGkF3UKqw==,type:str]
                client_secret: ENC[AES256_GCM,data:IP41M8yOpWFNlalr2ewzP/Hmx2TCORXPKVA7cbYcAO+b+hyRUKrZogHCZedz/FBCRPClhnSrzZDReWN76TW4eg==,iv:ep43OjM8WNulcTx9aWLN7lb3bgx0sJAu19whQZBgJBs=,tag:6BIPxusz9l3uwtNby1CF9w==,type:str]
                oauth_callback_url: ENC[AES256_GCM,data:MU/qzWGqvBBTcJoXm2bKMi6ULniwUJufu5ptNtk1hPwh9JzdpngQ6itb+t0oupdSh/t6J+5W5wJFbSLV,iv:Ig3v6GUQtvDPQYP6nN86W0vJUuxlWIAIlf6xl+2d824=,tag:xTF/DEtPU/khRDPibmVHUw==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/ucb-datahub-2018/locations/global/keyRings/datahub/cryptoKeys/sops
          created_at: "2026-05-08T23:31:56Z"
          enc: CiUA67O9ALd2S51gTGCdXMVG1KHSjxqO3J7RqLmoa9gfmQvxHfahEkgAdEnSztOhYu7RJGlUj8cGdPPvOjtgr9Lv+rsW9UhNmGfIYOLjzj5kQetltasjmXBKNFbPPiRPVC1BZVZ5dbtVYFIEb8087Y8=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-05-08T23:31:56Z"
    mac: ENC[AES256_GCM,data:MlIWBjb0sa3MllGdjIAOAPedAdrw+8G2R3yRk9+t1gBEns37MM0/4xJ8AX2zPCVCtd4tnfj/B+69zeu2m42rq79GQpLDj2a7yxli+p9i8W5JW9GDclalZX4yETg0LLPt9R1wwYplobC1qRLT7xLuo7bKjepz0qZCJUsEIvZ9JuM=,iv:baibRnlZ8SRkWwbg9Gp9ibYBMkFU+I5npQj8ICx+e74=,tag:5Pcju6UP/idNjHB3ZYy5tg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
