#!/bin/bash
set -euo pipefail

mkdir -p ${CONDA_DIR}/etc/ipython ${CONDA_DIR}/etc/jupyter
cp -p ipython_config.py ${CONDA_DIR}/etc/ipython/
cp -p jupyter_notebook_config.py ${CONDA_DIR}/etc/jupyter/

# Set up notebook-as-pdf dependencies
export PYPPETEER_HOME=${CONDA_DIR}
pyppeteer-install

# pre-generate the font cache
python font-cache.py
