#!/bin/bash
set -euo pipefail

# Set up nbpdf dependencies
export PYPPETEER_HOME=/srv/app
pyppeteer-install
jupyter bundlerextension enable nbpdfexport.bundler --sys-prefix --py

cp -p ipython_config.py ${APP_DIR}/etc/ipython/

cp -p jupyter_notebook_config.py ${APP_DIR}/venv/etc/jupyter/

# pre-generate the font cache
python font-cache.py
