jupyterhub:
    hub:
        config:
            CanvasOAuthenticator:
                client_id: ENC[AES256_GCM,data:XEThbgYoHLSa8GQ0gLMFmNo=,iv:IkkGPj0MczxsR7hpciP34aBajgqLv0cPSbuP5qDsFS0=,tag:F8QuoK1uiF3aDyq2UZxkQQ==,type:str]
                client_secret: ENC[AES256_GCM,data:LeqcTTmhjuA636ffq9dslT8SGW76s9GgQ7ST778zoLVfjqDLSWEDJjR6wK2DTQniVBOpe63UVGCgMqEUYHFaBA==,iv:ybMWps+/bgFhQRMeIdQRiW9Nwq6dvp7Gu8gs9e3V6fA=,tag:Ya9/U9ymnxiDuDZeQCLs+g==,type:str]
                oauth_callback_url: ENC[AES256_GCM,data:d7OPcGlgGc9lyyrlcbfhxlZAn1pWeQ6KDHWES4SsDboc1ZAC/zlhfc8p+SCYnCKoIu7ogTA=,iv:bG879yOR5nbEqD96vPXEhEhdBMXuVCL1zzwNuAlGhy8=,tag:5TS6kSD8yi0VWGkAyCge0g==,type:str]
        services:
            grouper-sync:
                name: ENC[AES256_GCM,data:iaPKDjEf7eUVSStl,iv:FX834HG2FM+oJhZ9KRqwnxzvNnYmO72tBRD5PEFnOhA=,tag:DvvVk11zjihQYllAILPiGA==,type:str]
                command:
                    - ENC[AES256_GCM,data:OinNOd3BEgAAQ5zR,iv:GRl7XPcrvlXScTUlX9WdeDxnRNJ2GzErJwoI0tWEZEY=,tag:4KlMQyJfNfpzoaYjxNtc3w==,type:str]
                    - ENC[AES256_GCM,data:E+7S9/aW1h6r9HLkvECIVXaiwTtVTWUjjik=,iv:Ah7dqDaBvN2SkAgFXUt86xbv0jxxkflUnmM2oj2xx1w=,tag:WXe3ZSz10DO7yWwZ2CQGiw==,type:str]
                    - ENC[AES256_GCM,data:e/vODjUR738a9fwonl1nWtGLmS8o/af08hxkBWAAEoU=,iv:csRbgDYFoSVocN12V532FoB1qBkMVE4x8qsxegBGYhM=,tag:+K3cSswdYFP0WdvILbE9bQ==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/ucb-datahub-2018/locations/global/keyRings/datahub/cryptoKeys/sops
          created_at: "2026-05-08T23:32:13Z"
          enc: CiUA67O9AK1ux9DykzO7vHQaK2+tls6bNTnJCnRkMRqUs6U4vmkdEkkAdEnSzl2eMBcVr+sGYXwH8FsrfZXrQS483n91tFKHuMTSZGPc5Q5ocirr4ZFKtZKr38MoZH+thYIskOM34umNs/zfF1zYkyDI
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-05-08T23:32:14Z"
    mac: ENC[AES256_GCM,data:/giJu3ttqohkdOCJcLBPWCwBNYT6IxNW9miwJmiegh+/3e6nXr3QheY6xNcvxmKUXYiuy7/7g6SmtCKMiqDZXktw6hlfYTsvqHcQYaSNwDf29PvOyo3GQlqnHDWP8DsoHUIsANphza76KY5EPfjgP+mc5K0hRSDKpnXV3ceAM4Y=,iv:2fjk+nF0gIg3AR6nyLcsSzWGATt7Z2GMGcA1+qVR7z0=,tag:8D/uhnqJ2wI2N/diPRrMxQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
