jupyterhub:
    hub:
        config:
            CanvasOAuthenticator:
                client_id: ENC[AES256_GCM,data:YprI+fUpzIKb8yxQxYLt1EE=,iv:kqh+FG5F3owR8ERvanxu4M8xQEwquXXPGgfQKVw2G9Q=,tag:5FW5f9xzLqNVeVnuResUbQ==,type:str]
                client_secret: ENC[AES256_GCM,data:woASLdQWL/gBd5qD9g09mXeQXZkleYpL9i6FtHsf/ziJz/KPSRGBXKw8M3SlV24J6KgouDv29ocF73ln7RxT7g==,iv:qUIxnR0SRbRvawFZdNn0MF8KMISVZeqcmX/nlUtIma4=,tag:7dbjNUrViUwLZnf6vTDZtA==,type:str]
                oauth_callback_url: ENC[AES256_GCM,data:ocWfq9zQkOWJ2HstLRrGG6YqJ8dIvXTofrYKujL1XJ40mgNV3uFmkXdk66+6ySTz4m17/bJNZPLspP4+9A==,iv:uO3AxKncETVK4ozKcQfzgzdhwiMYNoEv9UkyKO4vtdw=,tag:ttcA28D6Y/nRdnN5HTqDHw==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/ucb-datahub-2018/locations/global/keyRings/datahub/cryptoKeys/sops
          created_at: "2026-05-08T23:31:44Z"
          enc: CiUA67O9AJgztk327DtmvUX/OeODyiQOoAbPThzf94+kGfx2zIrUEkkAdEnSzr79GGpi5excvEch+j1tKXDHlCLeaVg96FchF8FRUQgJVIKg6K8yIex6ynsJv7IV6IuZBhbd4iwBQOo6hl9I/xhuXNI9
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-05-08T23:31:45Z"
    mac: ENC[AES256_GCM,data:vK9kMKqNmzdPamb3I0gjgQaDRwd8XTtqTt9O+V/D2PJugh35cBOBEYrqnPMwG5nFbywanQLbb6BiGm2tyPKyXeK2FkReuvH1TP5iOtd3zOWe6rsKAMGJCm2tchNvmxpgAGYJAuCWfsWc3wAJHgtWppqEDdXhgWcPJmikViLuWi0=,iv:K9jC4hOtFu/Xk7+HYtG/pu2mC/y0VpslDPhMEiJSQY0=,tag:N9GZHbkBS5oppym/+xmb+w==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
