jupyterhub:
    hub:
        config:
            CanvasOAuthenticator:
                client_id: ENC[AES256_GCM,data:c/puicIWqXVqoJ9W0vQcZGg=,iv:xqaG4uIZIRenE14f0MVMwTJoMclRXIZ84ufAND+0rZY=,tag:aBy+jd4pFk1SOly/xdLYDw==,type:str]
                client_secret: ENC[AES256_GCM,data:wcfDSVUQ0CSTH39tp/lAt8GRXs01ReFOYrEKmBC4gsT5t3Z9f34GCanSAyyKXEog+dIyUqNt6i7EfVgnzl3idg==,iv:Z6Wk2yTey8C2Hen/Z6DmOxmnMhhVCQDkKVYLVO7i2ug=,tag:HA4ocI+LSYIffAblaU6UgQ==,type:str]
                oauth_callback_url: ENC[AES256_GCM,data:qrtyuh8HtQSUjJLP2140WQ8Iw0z6K4/r2AT61Jzro3gGIiXaToeStI8DKSXvVi0wa2t1v1XS,iv:9n4HMA30OxWmEpS4Yxki/3OdxYUm5BWADmo7jTs+D6U=,tag:JGxSHXX9fCRxHkRAUvV80w==,type:str]
        services:
            grouper-sync:
                name: ENC[AES256_GCM,data:+wFf9+ZYGK+zfMz2,iv:iQ0KRBzSSzgZw2cv2erNzfI9UdhwYuJqffnb1/b7WtU=,tag:LggiFjwqj+K+Q9FN1++nGA==,type:str]
                command:
                    - ENC[AES256_GCM,data:vQjSViUDJi5fClwT,iv:bwsQyPXxVu9EKLN62GQs6b+Fus+RCyRIK4Nn69sLgnk=,tag:Ayd2+mOCo/OGoRskSyj8ng==,type:str]
                    - ENC[AES256_GCM,data:yAD6z3b8d/jTDMAWfexoJG2aridrDu70UCk=,iv:nmwLoKf8mJyP2HvSmF/JtRT0tUDuf8c5nnM7M4MpNrA=,tag:oecYFFtuP+A6e3oBYvHIzQ==,type:str]
                    - ENC[AES256_GCM,data:xQO1fAYriI+GXux1yewxs0Z9CU9NuaIQC9FNIq01K5Y=,iv:ecqPaKOMQPA3YvAhOwruQPQ/XHKrtXKyx/xb4JczN+o=,tag:LDKMGzYYaChRqk0PjMY90Q==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/ucb-datahub-2018/locations/global/keyRings/datahub/cryptoKeys/sops
          created_at: "2026-05-08T23:32:16Z"
          enc: CiUA67O9AFrimJmWrNRCk5SLQpMdCn/2M8661bT2V6wuX95crkDHEkkAdEnSzhuR6aDFK+XTdtnYfGr0BdK3iLBQhtDbiBqrx70/AAb2V6Sy9D5vGC5OOiuOPryDiWugK4DUQTlNMZfYFBGxDOKRo9WG
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-05-08T23:32:16Z"
    mac: ENC[AES256_GCM,data:tbNx99prdI+GBWWzJ1FWF5sPKiPaHbgXDSKjGy9SBSnOA+8u5+3UMA7EQiXu7Kzgv7/59vImw3GJh6aWmjS147wSxVpEX1z1qN+nrMLr3J0CkXYKPem88jm0UXbVu4pYgp8rY2ma+3p/SNeyqDuveLEaV9y3bS5rj4ZGrS1VLiQ=,iv:rToTW90dPlldaSvX2ZZyhGdd9bEbbGJTaCMKLiAdWls=,tag:EeKTG1WLzmtJCmsLSk3rXQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
