jupyterhub:
    hub:
        config:
            CanvasOAuthenticator:
                client_id: ENC[AES256_GCM,data:uewG8i+kXbr7Pz24bG1gl4s=,iv:Mfp+iCZs1tM+NJLItnSZfteu7oO1ikGBe7JRbPMh1a8=,tag:uCWwPyCOe+dg6iMB8CmcLg==,type:str]
                client_secret: ENC[AES256_GCM,data:x6MsPQK17x1icQBGRIH4d+Xv3lE/ikM/AuiWmQkDKeuVSFcwM+DEef6nO+F0ja8tmHpBL4I/d0GM8FZ7x7bAeA==,iv:64M5fbhDtPL1nBZABE5AYFMEtWUMepxuJOA2cx0vMC4=,tag:FiW7jaIHeEODPEwVmQxbbg==,type:str]
                oauth_callback_url: ENC[AES256_GCM,data:2l5BzdfkMesFCQuc7rkqI+JRXdsaN8AQg2JZtlTnOaeBdAIdex5b2dTS8N3k8jhNI/01TmxsHekPMwabHNE=,iv:jUGHGiwjlF/mX9ZCRHkqE3nMbEdSFV+L4fzvCH1R9sc=,tag:ois1HnvBvjVtWzbAqYHfTA==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/ucb-datahub-2018/locations/global/keyRings/datahub/cryptoKeys/sops
          created_at: "2026-05-08T23:31:47Z"
          enc: CiUA67O9AJJ4vQiTMDM4zfGdj3pP4Z1f9s5PZqFCIFDUTOKhYSkTEkkAdEnSztvOiWuxBmj2B9v43Y42nv4udKzt4VDq2aq8Yf6JktoTamEKjGV4DLHSy5P8iywGv3Kl8nRULV/4JxsmNe1ggdyDCpwh
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-05-08T23:31:47Z"
    mac: ENC[AES256_GCM,data:UtVbeNrPsYOeN0N/IbmEVlUqak1ZuPHv+DjY9osVZVZsfPQXQAu8EpOl08B9/MDsfFDCOW6nRZZbU8ZBjcSltKjvY1KiurwLbXXsNFhTf6UBOUtWrVhpr5JlpFfkbZwr6rN0Ag++iB5/nIxthR+1DaVBlPsTP8iPfiEfDb0LD1I=,iv:sNVMHxb+7Hr/+vk4IRuJQ4mjFMM1HLX7VTgfnfhEmEU=,tag:8xNIXUf2FDQRoftJzh8w6w==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
