nfsPVC:
  enabled: true
  nfs:
    serverIP: 10.49.181.18

etcGitConfig:
  enabled: true
  gitconfig: |
    [credential "https://github.com"]
      helper = !git-credential-github-app --app-key-file /etc/github/github-app-private-key.pem --app-id 94386
      useHttpPath = true

jupyterhub:
  ingress:
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod

  scheduling:
    userScheduler:
      nodeSelector:
        hub.jupyter.org/pool-name: core-pool-2024-05-08
  proxy:
    service:
      type: ClusterIP
    chp:
      nodeSelector:
        hub.jupyter.org/pool-name: core-pool-2024-05-08
    traefik:
      nodeSelector:
        hub.jupyter.org/pool-name: core-pool-2024-05-08
  hub:
    nodeSelector:
      hub.jupyter.org/pool-name: core-pool-2024-05-08
    config:
    loadRoles:
      # datahub staff
      datahub-staff:
        description: Enable admin for datahub staff
        # this role provides permissions to...
        scopes:
          - admin-ui
          - admin:groups
          - admin:users
          - admin:servers
          - read:roles
          - read:hub
          - access:servers
        # this role will be assigned to...
        groups:
          - course::1524699::group::all-admins

  singleuser:
    image:
      name: us-central1-docker.pkg.dev/ucb-datahub-2018/user-images/datahub-user-image
      tag: f2a50e230a12
    extraFiles:
      # DH-544
      jupyter-lab-overrides:
        mountPath:  /srv/conda/share/jupyter/lab/settings/overrides.json
        stringData:  |
          {
            "@jupyterlab/notebook-extension:tracker": {
              "windowingMode": "defer"
            }
          }   
      # DH-305
      remove-exporters:
        mountPath: /etc/jupyter/jupyter_notebook_config.py
        stringData: |
          c.QtPDFExporter.enabled = False
          c.QtPNGExporter.enabled = False
          c.WebPDFExporter.embed_images = True
      # DH-532
      # nbgitpuller links should set `targetPath` to the site_dir value,
      # followed by the repo name, e.g. `targetPath=ShinyApps/stat555-fall-2025`
      jupyter-shiny-proxy:
        mountPath: /etc/jupyter/jupyter_server_config.py
        stringData: |
          c.JupyterShinyProxy.site_dir = "ShinyApps"
    extraEnv:
      # Unset NotebookApp from hub/values. Necessary for recent lab versions.
      JUPYTERHUB_SINGLEUSER_APP: "jupyter_server.serverapp.ServerApp"
    nodeSelector:
      hub.jupyter.org/pool-name: r-pool
    storage:
      type: static
      static:
        pvcName: home-nfs-v3
        subPath: "{username}"
      extraVolumes:
        - name: etc-gitconfig
          secret:
            secretName: user-etc-gitconfig
      extraVolumeMounts:
        - name: etc-gitconfig
          mountPath: /srv/conda/etc/gitconfig
          subPath: gitconfig
          readOnly: true
        - name: etc-gitconfig
          mountPath: /etc/github/github-app-private-key.pem
          subPath: github-app-private-key.pem
          readOnly: true
        # RStudio can't write session files to anywhere except ~/.rstudio -
        # only way to change that is by setting $HOME. So instead, we just
        # bind mount a fresh directory on top of ~/.rstudio!
        - name: home
          mountPath: /home/jovyan/.rstudio
          subPath: '{username}/.r-hub-rstudio'
    defaultUrl: "/rstudio"
    memory:
      guarantee: 512M
      limit: 1G
    image: {}

  custom:
    group_profiles:
      # DataHub Infrastructure staff
      # https://bcourses.berkeley.edu/courses/1524699/groups#tab-80607
      course::1524699::group::all-admins:
        mem_limit: 2048M
        mem_guarantee: 2048M
      course::1547015::enrollment_type::teacher:
      ## Course Name: bcourses-1547015 Bcourses ID: 1547015 End Date: 12/31/2025
      ## See issue https://github.com/berkeley-dsep-infra/datahub/issues/7528 for details.
        extraVolumeMounts:
          - name: home
            mountPath: /home/jovyan/_shared/bcourses-1547015-readwrite
            subPath: _shared/2025-fall/courses/1547015
            readOnly: false
      course::1547015::enrollment_type::ta:
      ## Course Name: bcourses-1547015 Bcourses ID: 1547015 End Date: 12/31/2025
      ## See issue https://github.com/berkeley-dsep-infra/datahub/issues/7528 for details.
        extraVolumeMounts:
          - name: home
            mountPath: /home/jovyan/_shared/bcourses-1547015-readwrite
            subPath: _shared/2025-fall/courses/1547015
            readOnly: false
      course::1547015::enrollment_type::student:
      ## Course Name: bcourses-1547015 Bcourses ID: 1547015 End Date: 12/31/2025
      ## See issue https://github.com/berkeley-dsep-infra/datahub/issues/7528 for details.
        extraVolumeMounts:
          - name: home
            mountPath: /home/jovyan/_shared/bcourses-1547015-readonly
            subPath: _shared/2025-fall/courses/1547015
            readOnly: true
