apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "node-placeholder-scaler.fullname" . }}
  labels:
    {{- include "node-placeholder-scaler.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "node-placeholder-scaler.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "node-placeholder-scaler.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "node-placeholder-scaler.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      volumes:
      - name: config
        configMap:
          name: {{ include "node-placeholder-scaler.fullname" . }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - --config-file=/etc/scaler/config.yaml
            - --placeholder-template-file=/etc/scaler/placeholder-template.yaml
            - --namespace={{ .Release.Namespace }}
            - --node-pool-selector-key={{ .Values.nodePoolSelectorKey | default "hub.jupyter.org/pool-name" }}
            - --placeholder-pod-label-selector={{ .Values.placeholderPodLabelSelector | default "app=node-placeholder-scaler,component=placeholder" }}
            - --cpu-threshold={{ .Values.cpuThreshold | default 0.2 }}
            - --memory-threshold={{ .Values.memoryThreshold | default 0.2 }}
            - --strategy={{ .Values.scalingStrategy | default "balanced" }}
            - --node-grace-period={{ .Values.nodeGracePeriod | default "600" }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
          - name: GRAFANA_API_KEY
            value: {{ .Values.grafana.apiKey }}
          volumeMounts:
          - name: config
            mountPath: /etc/scaler
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
