jupyterhub:
    hub:
        config:
            CanvasOAuthenticator:
                client_id: ENC[AES256_GCM,data:S2B+wd3MAgWKxMn4RImn288=,iv:jaKvldSXFiZ5Z/GXIKHD53ivXKd1nebSjk7ZASnITTg=,tag:57zD8EnMKnJk9mPa4AnbQw==,type:str]
                client_secret: ENC[AES256_GCM,data:D+7fzVLRCGNVYAb2rKGnJRcLU/qXOuqR5CDxbEQDdNuwzBSE/Y0peX7BoqwCS0J/KFtyUxo/TxbULx+29w7zdQ==,iv:MLVknl2JhqHuTQ5Av8pQ75h3pZOSwA2Jl+9EMOt9klM=,tag:Cs60/7as19p6gMzbAvjMOw==,type:str]
                oauth_callback_url: ENC[AES256_GCM,data:4BXnJvk8EaxWHKvO3B8KeSLjCNBk46DP36i1RDBzoBi4f/2yZqVnnkAgyQLKU+KOhnWclfYPow==,iv:AeN+uRIpCycuI8+puN+cHQErBF/vqo0Uo/8CZby9bX0=,tag:yzKy8hp/gdRH5BTh0DCPtA==,type:str]
        services:
            grouper-sync:
                name: ENC[AES256_GCM,data:v+yZYyBkHV7UQWyg,iv:mpPwVRoPZYebdQcHuYZXtlzTKEN3LAKWoKrAEcMGf4k=,tag:i1cCDwLC3xzsSD+4HNYPxg==,type:str]
                command:
                    - ENC[AES256_GCM,data:meoVS+K7itjJNAmJ,iv:PYkfRzTuBVx1QXcfyRdaYQEnmZAew9eYc9MJo5snANQ=,tag:WtRrTcx++xl9bMjiZlHHbA==,type:str]
                    - ENC[AES256_GCM,data:7K/uK2MD2D3TCACIwmvF4odhIvADQzxZEuQ=,iv:N6iSjaK3zPtd9dWkxYIcwi4SRXkS433xSPPmxATJa/I=,tag:C6Pyl6fTQXFngOPwRNVX5A==,type:str]
                    - ENC[AES256_GCM,data:71lBOummagzbLf5Hl8JO7c5rfHOkv8tQxdR2Z53GzNs=,iv:BnqMV+kcI9nOKKhyxaxRYWMR2ioSonH3qsXhsTmFniM=,tag:jzshyg4qbOb8f2HZ+M6zFg==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/ucb-datahub-2018/locations/global/keyRings/datahub/cryptoKeys/sops
          created_at: "2026-05-08T23:32:27Z"
          enc: CiUA67O9AOap+3LhVbu1zDvC7N6txoxMnwa/Sn8E8uY25UBcHNJ2EkkAdEnSzqr28LL0fU4NoTyTDlKzFgqG+FUrqcK0wZ3Zmk3C91glB1APSeZ/6M/pJK5Ko7wDajMDqa2jxSmxI5NUdSrNNWW0xf5D
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-05-08T23:32:28Z"
    mac: ENC[AES256_GCM,data:jiWg2bKq4ncET5/ABm5/5BmVlJY8Ik4ZL23Mlawu9Xc4XgWxtEul6iwZVeCOV1AWM9D8PDX9Ijtzrlc5hHX+CYZ/To2glQ3BB5e0p54DYTjrhIOZUEnaqIEiModYyeDwP9St+qSkWg0zvmTDCFwJPVRQhBsdZGgH2ZUyK7bv6ME=,iv:mLmUzrgAMUdX5yMqX9a/MkhzYmMnIn5IXFQkQGfI81M=,tag:JYKAyTYGjJD05gNh8F60Rg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
