jupyterhub:
    hub:
        config:
            CanvasOAuthenticator:
                client_id: ENC[AES256_GCM,data:r3XNC36r8FYku8d17uUcpEg=,iv:QjGXLP4NmmWRALpAkK4wvKKh238OpDDs6SDSaA4KgDw=,tag:+NG61J7qhQ277AhSE1kS7Q==,type:str]
                client_secret: ENC[AES256_GCM,data:f5ZpMyOmVSbAITGklmeQ20yxraEUhjguS/hP5WxZjwneiI5IKx3JJacLiiHRfUdxtK5WKz5VuvN2FNzgsYb/mQ==,iv:gHJ4ntVgFBH4Ef9yi/Q81K9qE7cE2HozK5ePz0dN/VM=,tag:zXpcMiJA8q1BiHE05p85aw==,type:str]
                oauth_callback_url: ENC[AES256_GCM,data:sRjAP0/GUzynp1/fLfr/IKSVSKe71okJBefnBs6OlcjYXPuyc+EvRPF2ObsBGzaIvbCH3xaNhz5Pw19mtktx,iv:J8G88Cu7t8HfQP3N7CNvHMV741B265OyijRdHSS6iP8=,tag:VRTJKREh41wthGwaP80igw==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/ucb-datahub-2018/locations/global/keyRings/datahub/cryptoKeys/sops
          created_at: "2026-05-08T23:31:58Z"
          enc: CiUA67O9AEPUB24RtfQTBw995ApckMwyWkUkPYw+xlWwmPky4pl3EkkAdEnSznLLzE91E/AsEQHE+UIb8COHxnUeYpQgY/cG0b5PG5HxR8YfeXuzyxVNNYcE19RAyCmr/d0t9qcYOvTz5+buvIb34hp2
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-05-08T23:31:59Z"
    mac: ENC[AES256_GCM,data:LLr09mlIpyKef4U7gWPy4nJj2cu7n/7YbjDKcgt81jrpKJDfJKppivtXGWdIDw7BYycct5uDkr1UcpTC+RiGejkFjI4leO2zqLUvIX/PLTdSXDSEECVfcSK9kjJG7jIOuFYhl77SWF8DPbLGK9zVsBAfnGZ6stFqmbNuZZX8s5o=,iv:E0s9yNrg1XFqdKYxDDFnpoj5suEMezo5u2MXFRybV/Q=,tag:XTVWqHMpyTcZPK5TFwj07Q==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
