#!/bin/bash -l
set -euo pipefail

# Code Server needs nodejs 16+ but nodejs is pinned in 
# repo2docker working this out
conda activate /srv/conda/envs/notebook
conda install -c conda-forge nodejs==16.*
conda install -c conda-forge code-server==4.5.1

# Create ipython config directory if it doesn't exist
mkdir -p ${CONDA_DIR}/etc/ipython
cp ipython_config.py ${CONDA_DIR}/etc/ipython/ipython_config.py