#!/bin/bash
set -euo pipefail

# Create ipython config directory if it doesn't exist
mkdir -p ${CONDA_DIR}/etc/ipython
cp ipython_config.py ${CONDA_DIR}/etc/ipython/ipython_config.py


# Allow users to stop / start servers from JupyterLab
jupyter labextension install @jupyterlab/hub-extension

# Install Spark
SPARK_HOME=/home/jovyan/spark
SPARK_VERSION=2.4.2
HADOOP_VERSION=2.7
wget -q https://www-us.apache.org/dist/spark/spark-${SPARK_VERSION}/spark-${SPARK_VERSION}-bin-hadoop${HADOOP_VERSION}.tgz -O spark.tgz
tar -xzf spark.tgz
rm spark.tgz
mv spark-${SPARK_VERSION}-bin-hadoop${HADOOP_VERSION} ${SPARK_HOME}-${SPARK_VERSION}
ln -s ${SPARK_HOME}-${SPARK_VERSION} ${SPARK_HOME}

cd $SPARK_HOME/python
python setup.py install


# install Spark GCS connector
#rm $SPARK_HOME/jars/guava-*.jar
#wget --quiet http://central.maven.org/maven2/com/google/guava/guava/23.0/guava-23.0.jar $SPARK_HOME/jars
#wget --quiet https://storage.googleapis.com/hadoop-lib/gcs/gcs-connector-latest-hadoop2.jar $SPARK_HOME/jars

