jupyterhub:
    hub:
        config:
            CanvasOAuthenticator:
                client_id: ENC[AES256_GCM,data:njINic+Ii1DvHkwQqQjh/NU=,iv:MQdaJIGXI6tfoh7zqpFL/nfPzgNNhJtOogth2MCsxQE=,tag:Wi01dt6xw9VE++1uy3MGSA==,type:str]
                client_secret: ENC[AES256_GCM,data:SwX3qRLs/TmO7ezw4OA5XYWK+fDSTiVoieHEPuf1DSFvIpBhnyUo9/LqSjTWeocvf5ZNmpn8WSNh5fM2/CuroQ==,iv:BDo+uA22KfHKiP2xa/i9phVxBDxwKj6KI9AtkfalesU=,tag:mCgN0YippA7NNSf9C051Bw==,type:str]
                oauth_callback_url: ENC[AES256_GCM,data:4fHgQHS2fbG1zu4EfSLBYmdf5yOlfrCj/YLDyaIkdxeGrgonWmE2BbmUM87/tEOvKsrts3ya66zwKfpF0lo=,iv:dxdNk/2knpuvKRN7zQeOBVEPCFzAYckf3DGJWjfoHVE=,tag:hLecWaWVadueso0IQPN4mQ==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/ucb-datahub-2018/locations/global/keyRings/datahub/cryptoKeys/sops
          created_at: "2026-05-08T23:32:20Z"
          enc: CiUA67O9AFif7UQkdPGFFRH9zm13QNAt0861qkqiICXWmcQ82fV0EkkAdEnSzrfaSMXUY6eIFfWfJRoq7nrm3nImIlnKLRMXaudVPXWe3tmTHPogytLZ1D7J8+qE1yNA79hJrvIcsUFvOo8IwhQVBfkL
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-05-08T23:32:21Z"
    mac: ENC[AES256_GCM,data:LSsP6aU99aKbrY51oTyOVyCtKWlwgi8vUoEGDdOheW7b4rcPBpx0u+Z4PmTtCeLc2pihfcosy/sj49THGHUSSz+i1d/bKqV9bFqiNsSSFlYUePNC2sCcyUiAY8g2k7b8NUw5xC2XiT3h/QTKLjBhg7vWI0j0VdrjSe/tF8byW74=,iv:8+s7Z84N6neD/ysD9y8iHwV2cHleLuVZFyTn23yPwIQ=,tag:leSwzmMZJwLpAA0RiAQWNA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
