jupyterhub:
    hub:
        config:
            CanvasOAuthenticator:
                client_id: ENC[AES256_GCM,data:jpyNTFza/Zxp+/uh/rA3e14=,iv:8bYayYdhei+cyKBXTmaJvz5zpSBuI7Jy8ZcXcfMvstY=,tag:y3jmVVZCmbHdSSE8ubB8rQ==,type:str]
                client_secret: ENC[AES256_GCM,data:5k30ahPU0/wrKGYmIJHYmeONHdTLKxSq7Sni9lBlLC5Y4aEYHSczGq4afqcWFJb7Jm7ipQG9k+WZhhnjQbPNng==,iv:86q9TieBy+89n+wvtJDrwopEFxE4w3/xeuMJld8onhA=,tag:TPQ5betd9PlLF7b+Gy7txg==,type:str]
                oauth_callback_url: ENC[AES256_GCM,data:WvLB2xvZ0nzP0+LNHYb+F8AN4z2RwVLVjbet8jArHqs/i3HC3OQLIdf10LgGnxJXlJrPbd9Qvn0DF24D0rjXC2fOGzF6bA==,iv:4PF/Z1u0K+YPKnRQnswpuG5f4/dBDTQ2QkbVZNPp9Es=,tag:Epc6Xxyl+LTgcOmJWLEVzA==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/ucb-datahub-2018/locations/global/keyRings/datahub/cryptoKeys/sops
          created_at: "2026-05-08T23:31:51Z"
          enc: CiUA67O9ACecKqBaeC6Ku4oAU3D4FzWahGPXPmm19sPz7kWd9cbwEkkAdEnSzq98KdCRyKIa8dCyxj1U1TWGwlWoh4xSfhG5zG+mmYpwe7nI6RaqGQOnrZdZFo+Gm87F70xSSQrAK0d8wpzu3VjJXFsD
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-05-08T23:31:52Z"
    mac: ENC[AES256_GCM,data:lyeiKW38EZoC9rwHncRaj5gX5aPau+rQPz6r0gnQieWhvYNZ8TQFMT4llIewOH+gJ9gVNNgKSJNFYXL0Hp+hkueAmyyI3tMnYo2UXxnQRVRwt2qPLSqXAhImaCKivBXDMg8bNxSCpdL2TZe7P3+9Xs0/3S9NJSXilVbpKTPwIJs=,iv:+qzb7CK3Kg7HqY4/bAdOvHuB4RUT4/Lx+GmRwrnsyPI=,tag:bDzTnaaaj88hXg9+SvZJaQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
