jupyterhub:
    hub:
        config:
            CanvasOAuthenticator:
                client_id: ENC[AES256_GCM,data:4mq387NU2TshC7mu1uvXqQU=,iv:h5EAKjY9JDe9fxlBAkS0JKoldFntShorMn44PIGNQd4=,tag:HW7uj5Yu+yyMmxvkUB4pvA==,type:str]
                client_secret: ENC[AES256_GCM,data:+E/UZMTY5JnuZFBe6en3JX6DW85ZlsUzbfiSpKV4DKQCOEt+xksmSSkWCicF11Lv9qO/+DtEhSek3uYAWed4xg==,iv:+rQZP1+lUcsThg/oenfTPJn55PPOzbooQM6iK8OBOOw=,tag:kc5/iJoAwTKqptVFNP7dkw==,type:str]
                oauth_callback_url: ENC[AES256_GCM,data:HeqpGOkg1mowzgggxEGi2tz4QNkFOgOZk3bC0nDiNXfjrHtJTyj7ZoR8vq9yFyNQQ7s51L4=,iv:vjtpKT6olo6bDlFcEVoWaOFYJaWPWw4k1W9ZYzuO5rQ=,tag:0RW2CtcAAVhD1fXmHbvcAg==,type:str]
        services:
            grouper-sync:
                name: ENC[AES256_GCM,data:V3cFqBWRL04rVVg5,iv:/vUKnPuzf99+RUSMmvDdIz1imuuYVIMbvrirKqmj5KA=,tag:RfjkVZUb0pIOzFAO0mvjaQ==,type:str]
                command:
                    - ENC[AES256_GCM,data:VKSlANxDFAT0cpNl,iv:nqrzh/Y9Z6vxJEaO+2ECZC5I3lZc5qdS56QreP2VsoY=,tag:ijClJnXQW7mWIwiQiVlAOg==,type:str]
                    - ENC[AES256_GCM,data:4FKHrIW5jgFDHCpJLHmaiEuHEcYxOyXVxs0=,iv:gEUdKoKtKfU0+6pN/th4YT5BALBG/DueAuqTBypm4io=,tag:oLF6W3yGYaw/6967tho85g==,type:str]
                    - ENC[AES256_GCM,data:kdg+VAa0TUs1Sf5RnZjiOJg23vKmRnCPE818gCAYL2I=,iv:PY4wh9mOFD0rrA8rYGgcIQ7SzbcO3x5tLOD4XFPrUzA=,tag:tp8TebRJlBKsNU0qiT1gew==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/ucb-datahub-2018/locations/global/keyRings/datahub/cryptoKeys/sops
          created_at: "2026-05-08T23:32:26Z"
          enc: CiUA67O9AJOOvgCJ8KTJdwJpW7iIHQumQJpFjgywpQqp741Xzc7QEkgAdEnSzjBR/xPYBHeNuNZznleVl57Fg9GYN2rsTatWxPAT477easc59nERDKRZgjCqnt+KmVas4vMP3bFMBqTwthWhHj1dkiM=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-05-08T23:32:27Z"
    mac: ENC[AES256_GCM,data:pnLnR+xRLmrlVZJVz86vGjLM5JcQxFILezPxGTZGNfxcBFDcQmkC0/bxcxWxp7KboT6rxpH35TK6lAlMY19xBZSp5KzPffgM14ipGeGjpPHulH0TWyrxSv0fAxs/ymhZPbIRpgSXbPBeuz28w0gskwN9HErrv77o53U+owvJHvo=,iv:baWM0gak/+c3SqcsTbRcBq0B3eoXO5xVh0YWB3RXoEg=,tag:t/70gEIyMXnDr/9Om4aq/g==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
