jupyterhub:
    hub:
        config:
            CanvasOAuthenticator:
                client_id: ENC[AES256_GCM,data:PDX3rbw97svIoAj0sTxMJFU=,iv:0/ypu5UZuQ5tho8YGIcqGk8iskqHQV11k/nuwFAFQ90=,tag:qgaDl70pD9mrF/cmxDQLrQ==,type:str]
                client_secret: ENC[AES256_GCM,data:+C3nw02g24tkClex1nWmAmtODAh5ZWSr42RCPjiu7IJs2nqq9oxQ40tIzNtcGDWsRuq+/bxtfkOuIlHNFS0Iwg==,iv:GbCTnJuz99fr7uAoMW437GOy/55R4RV6r7JZ8RJHhnk=,tag:kn+1/MnNz1vwAKChP8upLQ==,type:str]
                oauth_callback_url: ENC[AES256_GCM,data:4PBAp10xS4b6hFbtpW6Y5OAZPgxqbNn0eKi7UtK92w2Y1HUPNmBaH2srWAUh63RN7zBrrwGfJfqmDgpy8g==,iv:4NeuZsxdJY6H1d1+ykFj6/NMmY1YuP//JPuLloRYEto=,tag:3WRZtrKD5GyGP5SjNM7ZWA==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/ucb-datahub-2018/locations/global/keyRings/datahub/cryptoKeys/sops
          created_at: "2026-05-08T23:31:57Z"
          enc: CiUA67O9APasSEqL8MXD3c4Sd6ewcp1XvG3T5i3DxSpNj0wiwGilEkgAdEnSznPKPIoN3yRCE966/VeYqw6KzKSDpFA5NRqTUXxN6ZsF4xBJ/pC/Iu7CwCi8RHoWIF6mHe8DTAug8/CKX/UQD55TlqQ=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-05-08T23:31:58Z"
    mac: ENC[AES256_GCM,data:huDfIp15/s48HUMELFwVcMOFPwdKvfiScAwxD7lSk07UwQBU5htxEtl649X4wJlZ0IBcjWxkYy4djEac7hI55h/0TLoeoMvs3AoIi0DH+Dor8EatpznYz195nYbWF/20tgKh0DmE2RT33GUks/bCSr0ZRxJS3VIcifj7T8mpCZY=,iv:gdKirwrgvOqBIYRS30NUWuhhyMrGTqcx1KsFZQYp0H8=,tag:3MFErceoPPSWKA5tN+stjA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
