---
title: User Authentication
---

Most of our hubs use a [Canvas](https://www.instructure.com/canvas/) instance,
[bcourses.berkeley.edu](https://bcourses.berkeley.edu), for authentication. The hubs not using `CanvasOAuthenticator` are edx (`LTI1Authenticator`), highschool (`GoogleOAuthenticator`), and workshop (`dummy`).

## Authorization

Anyone who can log in to bCourses can log into our Canvas-based hubs. This
includes all Berkeley affiliates. If you have a working berkeley.edu
email account, you can most likely log in to bCourses, and hence to
our JupyterHubs.

Students have access for 9 months after they graduate. If they have
an incomplete, they have 13 months of access instead.

## Non-Berkeley affiliates

If someone who doesn't have a berkeley.edu account wants to use
the JupyterHubs, they need to obtain a [CalNet Sponsored Guest
account](https://calnetweb.berkeley.edu/calnet-departments/calnet-sponsored-guests) and get added to a bCourses course.

## Troubleshooting

If you can log in to [bCourses](https://bcourses.berkeley.edu) but
not to any of the JupyterHubs, please contact us.

If you can not log in to bCourses, please [contact bCourses support](https://dls.berkeley.edu/services/bcourses-0).
