---
title: Policy considerations for creating a new hub
---

We have lots of prior experience creating 10+ new hubs catering to the diverse instructional needs of the campus audience. Our decisions to create a new hub were made with a lot of intuition about solving instructors' immediate needs effectively. The objective of this policy document is to codify these heuristics used while creating a new hub. Our policy should guide our decisions with regard to creating new hubs in the future. 

Below are 5 key criteria (listed in the order of importance) to be considered while making a decision to create a new hub. Satisfying any one of the below-mentioned criteria creates the opportunity for a new hub.

- **Image Customization**: Course needs image customization beyond what we currently have in the main datahub image. (Eg: Astro hub, Stat 159 hub)
- **Testbed**: Testbed for deploying new features which post maturity can be enabled across other major hubs (Eg: Stat 159 hub)
- **Large Computation**: Course is computationally intensive requiring a large amount of CPU/Memory because of the nature of the use case (Eg: biology hub) or larger user base with 300+ students (Eg: Data 8 and Data 100 hubs). These courses may require additional compute through calendar-based scheduling.
- **Admin Access**: Course has undergrad students acting as GSIs while simultaneously requiring admin access (Eg: Data8 hub)
- **Organizational Reasons**: Hub is created for organizational/strategic reasons to build institutional buy-in from specific departments (Eg: Public Health and ISchool Hubs) and/or evangelize a specific service (Eg: Julia or R hub)
