#!/bin/bash
set -euo pipefail

#    Copy over Jupyter configuration files
mkdir -p ${CONDA_DIR}/etc/ipython
cp ipython_config.py ${CONDA_DIR}/etc/ipython/ipython_config.py
mkdir -p ${CONDA_DIR}/etc/jupyter
cp jupyter_notebook_config.py ${CONDA_DIR}/etc/jupyter/jupyter_notebook_config.py

# run matplotlib once to generate the font cache
python -c "import matplotlib as mpl; mpl.use('Agg'); import pylab as plt; fig, ax = plt.subplots(); fig.savefig('test.png')"
test -e test.png && rm test.png

#    Install necessary JupyterLab extensions
jupyter labextension install --no-build		       					            \
     @jupyter-widgets/jupyterlab-manager  							    \
     @jupyterlab/plotly-extension  								    \
     jupyter-matplotlib  									    \
     plotlywidget                                                                                   \
     @jupyterlab/latex
jupyter lab build
jupyter lab clean
