#!/bin/bash
set -euo pipefail

export TZ=America/Los_Angeles
export LC_ALL=en_US.UTF-8
#    Copy over Jupyter configuration files
mkdir -p ${CONDA_DIR}/etc/ipython
cp ipython_config.py ${CONDA_DIR}/etc/ipython/ipython_config.py
mkdir -p ${CONDA_DIR}/etc/jupyter
cp jupyter_notebook_config.py ${CONDA_DIR}/etc/jupyter/jupyter_notebook_config.py

#    Get up-to-date version of JupyterHub
pip uninstall --yes jupyterhub sqlalchemy python-oauth2 urllib3 mako alembic
conda install --yes -c conda-forge jupyterhub=1.1.0

#    Install necessary JupyterLab extensions
jupyter labextension install								            \
     @jupyter-widgets/jupyterlab-manager  							    \
     @jupyterlab/plotly-extension  								    \
     jupyter-matplotlib  									    \
     plotlywidget
jupyter lab clean
