#!/bin/bash

export JUPYTERLAB_SETTINGS_DIR=$HOME/.jupyter/lab/user-settings
mkdir -p $JUPYTERLAB_SETTINGS_DIR/@jupyterlab/apputils-extension
echo '{"theme": "JupyterLab Dark"}' > $JUPYTERLAB_SETTINGS_DIR/@jupyterlab/apputils-extension/themes.jupyterlab-settings

exec "$@"
