etcGitConfig:
  enabled: true
  gitconfig: |
    [credential "https://github.com"]
      helper = !git-credential-github-app --app-key-file /etc/github/github-app-private-key.pem --app-id 131611
      useHttpPath = true

nfsPVC:
  enabled: true
  nfs:
    serverIP: 10.185.238.42

jupyterhub:
  ingress:
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod

  scheduling:
    userScheduler:
      nodeSelector:
        hub.jupyter.org/pool-name: core-pool-2024-05-08
  proxy:
    chp:
      nodeSelector:
        hub.jupyter.org/pool-name: core-pool-2024-05-08

  hub:
    loadRoles:
      # datahub staff
      datahub-staff:
        description: Enable admin for datahub staff
        # this role provides permissions to...
        scopes:
          - admin-ui
          - admin:groups
          - admin:users
          - admin:servers
          - read:roles
          - read:hub
          - access:servers
        # this role will be assigned to...
        groups:
          - course::1524699::group::all-admins
      course-staff-1544584:
        ## Course: PH142 - Introduction to Probability and Statistics in Biology and Public Health Bcourses ID: 1544584 End Date: 08/20/2025 
        ## See issue https://github.com/berkeley-dsep-infra/datahub/issues/7257 for more details.
        description: Enable course staff to view and access servers.
        scopes:
          - admin-ui
          - list:users!group=course::1544584
          - admin:servers!group=course::1544584
          - access:servers!group=course::1544584
        groups:
          - course::1544584::enrollment_type::teacher
          - course::1544584::enrollment_type::ta
    extraConfig:
      # Use 1x-<title> in `common.yaml` extraConfig values.
      # We want these to come *after* the extraConfig values
      # in `values.yaml`. Since these are ordered alphabetically,
      # 1x-<title> used in `common.yaml` will come after
      # 0x-<title> used in `values.yaml` - so config set here
      # will override config set in `values.yaml`
      11-working-dir: |
        c.KubeSpawner.working_dir = '/home/jovyan'
    nodeSelector:
      hub.jupyter.org/pool-name: core-pool-2024-05-08

  singleuser:
    image:
      name: us-central1-docker.pkg.dev/ucb-datahub-2018/user-images/publichealth-user-image
      tag: 33f2822a00e7
    extraFiles:
      # DH-305
      remove-exporters:
        mountPath: /etc/jupyter/jupyter_notebook_config.py
        stringData: |
          c.QtPDFExporter.enabled = False
          c.QtPNGExporter.enabled = False
          c.WebPDFExporter.embed_images = True
    extraEnv:
      # Unset NotebookApp from hub/values. Necessary for recent lab versions.
      JUPYTERHUB_SINGLEUSER_APP: "jupyter_server.serverapp.ServerApp"
    defaultUrl: /rstudio

    nodeSelector:
      hub.jupyter.org/pool-name: publichealth-pool
    storage:
      homeMountPath: /home/jovyan
      type: static
      static:
        pvcName: home-nfs-v3
        subPath: "{username}"
      extraVolumes:
        user-etc-gitconfig:
          name: etc-gitconfig
          secret:
            secretName: user-etc-gitconfig
      extraVolumeMounts:
        gitconfig:
          name: etc-gitconfig
          mountPath: /srv/conda/etc/gitconfig
          subPath: gitconfig
          readOnly: true
        private-key:
          name: etc-gitconfig
          mountPath: /etc/github/github-app-private-key.pem
          subPath: github-app-private-key.pem
          readOnly: true
    memory:
      guarantee: 512M
      limit: 1G

  custom:
    group_profiles:
      # https://bcourses.berkeley.edu/courses/1524699/groups#tab-80607
      course::1524699::group::all-admins:
        mem_limit: 2G
        mem_guarantee: 2G
