nfsPVC:
  enabled: true
  nfs:
    serverIP: 10.185.238.42

jupyterhub:
  debug:
    enabled: true
  ingress:
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod

  scheduling:
    userScheduler:
      nodeSelector:
        hub.jupyter.org/pool-name: core-pool-2024-05-08
  proxy:
    chp:
      nodeSelector:
        hub.jupyter.org/pool-name: core-pool-2024-05-08
      resources:
        limits:
          memory: 4Gi
      extraEnv:
        DEBUG: "http-proxy-3:ws-incoming"

  hub:
    resources:
      limits:
        memory: 4Gi
    nodeSelector:
      hub.jupyter.org/pool-name: core-pool-2024-05-08
    config:
    loadRoles:
      # datahub staff
      datahub-staff:
        description: Enable admin for datahub staff
        # this role provides permissions to...
        scopes:
          - admin-ui
          - admin:groups
          - admin:users
          - admin:servers
          - read:roles
          - read:hub
          - access:servers
        # this role will be assigned to...
        groups:
          - course::1524699::group::all-admins
  singleuser:
    extraFiles:
      jupyter_server_config.json:
        mountPath: /usr/local/etc/jupyter/jupyter_server_config.json
        data:
          FileContentsManager:
            always_delete_dir: true
          #YDocExtension:
            #disable_rtc: true
      remove-exporters:
        mountPath: /etc/jupyter/jupyter_notebook_config.py
        stringData: |
          c.QtPDFExporter.enabled = False
          c.QtPNGExporter.enabled = False
          c.WebPDFExporter.embed_images = True
      jupyter-lab-overrides:
        mountPath: /srv/conda/envs/notebook/share/jupyter/lab/settings/overrides.json
        data:
          "@jupyterlab/notebook-extension:tracker":
            scrollPastEnd: false

    extraEnv:
      # Unset NotebookApp from hub/values. Necessary for recent lab versions.
      GH_SCOPED_CREDS_CLIENT_ID: Iv23liGBW8jtMBP0inyw
      GH_SCOPED_CREDS_APP_URL: https://github.com/apps/uc-berkeley-nature-hub-git-access
      JUPYTERHUB_SINGLEUSER_APP: "jupyter_server.serverapp.ServerApp"
      JUPYTER_PATH: "/srv/conda/envs/shared-1546503/share/jupyter"
    nodeSelector:
      hub.jupyter.org/pool-name: nature-pool
    storage:
      type: static
      static:
        pvcName: home-nfs-v3
        subPath: "{username}"
    memory:
      guarantee: 4G
      limit: 4G
      
    profileList:
      - display_name: "Default Profile"
        description: "This profile is for general users. It uses the default nature single user image, default CPU and memory."
        default: true
        slug: "default-profile"   
        kubespawner_override: {
          image: us-central1-docker.pkg.dev/ucb-datahub-2018/user-images/nature-user-image:e8a8cfb91ec3            
        }
        profile_options:
          interface:
            display_name: "Launching Interface"
            description: "Select the interface to launch"
            choices:
              vscode:
                display_name: "VSCode"
                default: true
                kubespawner_override:
                  default_url: "/vscode"  
              lab:
                display_name: "JupyterLab"
                kubespawner_override:
                  default_url: "/lab"


      - display_name: "Profile for ESPM-288 Instructors and TAs"
        description: "This profile is for the instructors and TAs in ESPM-288."
        slug: "course-1551740-instructors-tas"
        allowed_groups:
          - course::1551740::enrollment_type::teacher
          - course::1551740::enrollment_type::ta
          - course::1524699
        profile_options:
          image:
            display_name: "Docker Image"
            description: "Select a Docker image (You can also enter a custom image below)"
            choices:
              nature:
                display_name: "Nature Image"
                kubespawner_override:
                  image: us-central1-docker.pkg.dev/ucb-datahub-2018/user-images/nature-user-image:e8a8cfb91ec3
            unlisted_choice:
              enabled: true
              display_name: "Publicly Accessible Custom Image (e.g. quay.io/my-project/my-image:tag)"
              display_name_in_choices: "Choose a Custom Image"
              validation_regex: "^.+:.+$"
              validation_message: "Must be a publicly available Docker image"
              kubespawner_override:
                image: "{value}"
          memory:
            display_name: "Memory"
            description: "Select memory"
            choices:
              2G:
                display_name: "2 GB"
                kubespawner_override:
                  mem_limit: 2G
                  mem_guarantee: 2G
              4G:
                display_name: "4 GB"
                kubespawner_override:
                  mem_limit: 4G
                  mem_guarantee: 4G
              6G:
                display_name: "6 GB"
                kubespawner_override:
                  mem_limit: 6G
                  mem_guarantee: 6G
              8G:
                display_name: "8 GB"
                kubespawner_override:
                  mem_limit: 8G
                  mem_guarantee: 8G
          interface:
            display_name: "Launching Interface"
            description: "Select the interface to launch"
            choices:
              vscode:
                display_name: "VSCode"
                default: true
                kubespawner_override:
                  default_url: "/vscode"
              lab:
                display_name: "JupyterLab"
                kubespawner_override:
                  default_url: "/lab"

 

      - display_name: "Profile for ESPM-288 Students and Observers"
        description: "This profile is for the students in ESPM-288."
        slug: "course-1551740-students"
        allowed_groups:
          - course::1551740::enrollment_type::student
          - course::1551740::enrollment_type::observer
          - course::1524699
        profile_options:
          image:
            display_name: "Docker Image"
            description: "Select a Docker image (You can also enter a custom image below)"
            choices:
              nature:
                display_name: "Nature Image"
                kubespawner_override:
                  image: us-central1-docker.pkg.dev/ucb-datahub-2018/user-images/nature-user-image:e8a8cfb91ec3
            unlisted_choice:
              enabled: true
              display_name: "Publicly Accessible Custom Image (e.g. quay.io/my-project/my-image:tag)"
              display_name_in_choices: "Choose a Custom Image"
              validation_regex: "^.+:.+$"
              validation_message: "Must be a publicly available Docker image"
              kubespawner_override:
                image: "{value}"

          interface:
            display_name: "Launching Interface"
            description: "Select the interface to launch"
            choices:
              vscode:
                display_name: "VSCode"
                default: true
                kubespawner_override:
                  default_url: "/vscode"
              lab:
                display_name: "JupyterLab"
                kubespawner_override:
                  default_url: "/lab"



      - display_name: "Profile for CSOL-208 Instructors and TAs"
        description: "This profile is for the instructors and TAs in CSOL-208."
        slug: "course-1551739-instructors-tas"
        allowed_groups:
          - course::1551739::enrollment_type::teacher
          - course::1551739::enrollment_type::ta
          - course::1524699
        profile_options:
          image:
            display_name: "Docker Image"
            description: "Select a Docker image (You can also enter a custom image below)"
            choices:
              nature:
                display_name: "Nature Image"
                kubespawner_override:
                  image: us-central1-docker.pkg.dev/ucb-datahub-2018/user-images/nature-user-image:e8a8cfb91ec3
            unlisted_choice:
              enabled: true
              display_name: "Publicly Accessible Custom Image (e.g. quay.io/my-project/my-image:tag)"
              display_name_in_choices: "Choose a Custom Image"
              validation_regex: "^.+:.+$"
              validation_message: "Must be a publicly available Docker image"
              kubespawner_override:
                image: "{value}"
          memory:
            display_name: "Memory"
            description: "Select memory"
            choices:
              2G:
                display_name: "2 GB"
                kubespawner_override:
                  mem_limit: 2G
                  mem_guarantee: 2G
              4G:
                display_name: "4 GB"
                kubespawner_override:
                  mem_limit: 4G
                  mem_guarantee: 4G
              6G:
                display_name: "6 GB"
                kubespawner_override:
                  mem_limit: 6G
                  mem_guarantee: 6G
              8G:
                display_name: "8 GB"
                kubespawner_override:
                  mem_limit: 8G
                  mem_guarantee: 8G
          interface:
            display_name: "Launching Interface"
            description: "Select the interface to launch"
            choices:
              vscode:
                display_name: "VSCode"
                default: true
                kubespawner_override:
                  default_url: "/vscode"
              lab:
                display_name: "JupyterLab"
                kubespawner_override:
                  default_url: "/lab"



      - display_name: "Profile for CSOL-208 Students and Observers"
        description: "This profile is for the students in CSOL-208."
        slug: "course-1551739-students"
        allowed_groups:
          - course::1551739::enrollment_type::student
          - course::1551739::enrollment_type::observer
          - course::1524699
        profile_options:
          image:
            display_name: "Docker Image"
            description: "Select a Docker image (You can also enter a custom image below)"
            choices:
              nature:
                display_name: "Nature Image"
                kubespawner_override:
                  image: us-central1-docker.pkg.dev/ucb-datahub-2018/user-images/nature-user-image:e8a8cfb91ec3
            unlisted_choice:
              enabled: true
              display_name: "Publicly Accessible Custom Image (e.g. quay.io/my-project/my-image:tag)"
              display_name_in_choices: "Choose a Custom Image"
              validation_regex: "^.+:.+$"
              validation_message: "Must be a publicly available Docker image"
              kubespawner_override:
                image: "{value}"

          interface:
            display_name: "Launching Interface"
            description: "Select the interface to launch"
            choices:
              vscode:
                display_name: "VSCode"
                default: true
                kubespawner_override:
                  default_url: "/vscode"
              lab:
                display_name: "JupyterLab"
                kubespawner_override:
                  default_url: "/lab"


                  
      - display_name: "Profile for DataHub Admins"
        allowed_groups:
          - course::1524699
        description: "This profile is only visible to DataHub Admins."
        slug: "course-1524699"  
        profile_options:
          image:
            display_name: "Docker Image"
            description: "Select a Docker image (You can also enter a custom image below)"
            choices:
              nature:
                display_name: "Nature Image"
                kubespawner_override:
                  image: us-central1-docker.pkg.dev/ucb-datahub-2018/user-images/nature-user-image:e8a8cfb91ec3
            unlisted_choice:
              enabled: true
              display_name: "Publicly Accessible Custom Image (e.g. quay.io/my-project/my-image:tag)"
              display_name_in_choices: "Choose a Custom Image"
              validation_regex: "^.+:.+$"
              validation_message: "Must be a publicly available Docker image"
              kubespawner_override:
                image: "{value}"
          memory:
            display_name: "Memory"
            description: "Select memory"
            choices:
              2G:
                display_name: "2 GB"
                kubespawner_override:
                  mem_limit: 2G
                  mem_guarantee: 2G
              4G:
                display_name: "4 GB"
                kubespawner_override:
                  mem_limit: 4G
                  mem_guarantee: 4G
              6G:
                display_name: "6 GB"
                kubespawner_override:
                  mem_limit: 6G
                  mem_guarantee: 6G
              8G:
                display_name: "8 GB"
                kubespawner_override:
                  mem_limit: 8G
                  mem_guarantee: 8G
          interface:
            display_name: "Launching Interface"
            description: "Select the interface to launch"
            choices:
              vscode:
                display_name: "VSCode"
                default: true
                kubespawner_override:
                  default_url: "/vscode"
              lab:
                display_name: "JupyterLab"
                kubespawner_override:
                  default_url: "/lab"
  
  custom:
    conda_shared:
      - bcourse_group: "course::1546503"
        staff_overrides:
          mem_limit: 8G
          mem_guarantee: 8G
