jupyterhub:
    hub:
        config:
            CanvasOAuthenticator:
                client_id: ENC[AES256_GCM,data:/5aT7sChwqxPwiPiZBrR9ak=,iv:XY8Ufm2gDKWWAru704zhC4qkJ+ByGdjphj7TAohUknQ=,tag:75+VRAi4Naxkdp/c0xxvKQ==,type:str]
                client_secret: ENC[AES256_GCM,data:126ItFdZyieR6qcb4NHcmxbowx/mF1Ywg501hNfDs1598E27bUSzkBzvfUQ4zMBoXOOkxHziydEmmyoSc/O2yg==,iv:FIu3HZhzhepGp/7EbXAF3G87eLLxjVx4XHXd17HvOkw=,tag:PAKfdA38tN+iVItQah4QPw==,type:str]
                oauth_callback_url: ENC[AES256_GCM,data:y9/G7FObCifTisaku1WC/vrakSgEG51w/8klEZO43jYZ/VE3G5uhkxRof1E0ZZ5bSjACD/cGGA==,iv:oX3cnHcVjkk9wAVUAffYFwG+UW51P9ppJ2uMJZLJFDY=,tag:5RrRrBA2rhPPhlTqTCh43A==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/ucb-datahub-2018/locations/global/keyRings/datahub/cryptoKeys/sops
          created_at: "2026-05-08T23:32:06Z"
          enc: CiUA67O9APlCfbZ3eDcCccDud39owp4r/uKJv8SUG/UA6dWNT5muEkgAdEnSzpAnfB8Xe48TOlRQGMWPXjRn30Hu4hKgFDq+CM384elwqjwk26R0IXiSWbEThkxAn7UT8ADfISjushVzxLDmdIBZNlo=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-05-08T23:32:07Z"
    mac: ENC[AES256_GCM,data:wINW5UJ4Z690mvrPrT8SRpI893Mj5FxwFam4jQqC7w2/+HuBrVQdlKfZl7jFLYztFcJXnjqTdpR2eVg0JJBrGINAPbYuud6sd1pV/w/tCsl+eu/BzmhonYBsQZN/CSjmO3O3+8raz+nxc1TE8wVkwV816EPNCW5lCC6RllaI524=,iv:o2EDZpOST9USHqbqM179/TmT/9AK/DMkWaZ7lRY/Okc=,tag:9DQmXd04N4Mxv64FQ9V5vg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
