jupyterhub:
    hub:
        config:
            CanvasOAuthenticator:
                client_id: ENC[AES256_GCM,data:QBgb+wFpGI3F+9J8az7yaxI=,iv:UTrowKBj1bemgWB3sz26iFODr1nJbZ9DSBcCVCQHO28=,tag:wN9t4psUbcP4osZrlMbzeg==,type:str]
                client_secret: ENC[AES256_GCM,data:e/2S2edMbias0Iq8FYRDhu8jlHg5BYDLfKSqylW1v7gCEtVyEoJ1LC3mn/hcyeiIsDfay22/LOpV6AyoyErnrA==,iv:mM208+hYcMScQrVghpmSb3BjI+IKzQeDsqS7uw+tDUc=,tag:4xDlaNnfnfI6APTsZSWqLw==,type:str]
                oauth_callback_url: ENC[AES256_GCM,data:WSaCYY1VY5h9SOFvzSFbmllH+fzDCL7qTsEvWU7cNmSGp0OdNlqWYDu2N2DWc+hsnIoexZhiGQ==,iv:aDiNWEwyFYQoT3aRpiv25Y5jny9UcDMvDLZv5kryYDE=,tag:DBc90yk1QAAtqr4NdpR1Qw==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/ucb-datahub-2018/locations/global/keyRings/datahub/cryptoKeys/sops
          created_at: "2026-04-21T21:39:04Z"
          enc: CiUA67O9AL0JUMLP49Wt1ogZvrwJY+oOvAHv+X4zbDZ/VB68XsskEkkAdEnSzpy8XUCw4WQiFXT4vdt2ruE/Xv85duk/fkiyIqKLp0HGnlZ0PS6K4+ifsrYcgKFYw3XnXlPEFmIxIgy71R08gKJD5gi5
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-04-21T21:39:05Z"
    mac: ENC[AES256_GCM,data:0w2RuYRvEIjOhnkr66LmEL3HPg7l/U3YdISQ9SGMz4hQOWurDNVz7VXo0LQOOXrjRgGXn86wXJQPm6TO6d9Z9OLlucBYB+cp0bziD/AWC9DnAaEqVD20n+aTfbohxFM+LP1yBRaUJWgv5v78pF9PW3W18I9tMNSeOOIKBQvy8dA=,iv:3BvsXQl5H4SZzUlu91FeJsrjC0BD1GsCqawMyEgxN8Q=,tag:H7yQBxC5Fk7VDrcvsec1mQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
