jupyterhub:
    hub:
        config:
            CanvasOAuthenticator:
                client_id: ENC[AES256_GCM,data:4bVc4EwMQKMLRtz9knYE0Lg=,iv:eV6qBq7cJ4F5/zXC9mBDyaet+m7O83xZ6XK3fEtGKBM=,tag:1chCmGQPMO/d6/DmuqT1YQ==,type:str]
                client_secret: ENC[AES256_GCM,data:Ubv2hfO77myBie9Y04iTfhMw5CjP40FifX1ji8bgKOhE50sl+bjxpEjGjbmPL6DGfdD8W7qolPBEzfY/zIV5Sg==,iv:rl6Eft3AKcPaMNSqWgsxa0GeiJcDkLHOjxrk7446csA=,tag:/Q4yjZMsmxdPCq8OhzJ7qw==,type:str]
                oauth_callback_url: ENC[AES256_GCM,data:nmJPU85xxM1EYlGa/18LPpSsQcVdk7vI2vZPO5WtiovUJmeXbFkxEAuqZePt4bsig6jL9FAiVQ==,iv:ADAfx89GkNxt2u0yosSX4l/xL0niC3DpKBr0PI+9khI=,tag:Yrq2xbscaPbnfTtFz9qWWQ==,type:str]

sops:
    kms: []
    gcp_kms:
        - resource_id: projects/ucb-datahub-2018/locations/global/keyRings/datahub/cryptoKeys/sops
          created_at: "2025-04-24T23:33:20Z"
          enc: CiUA67O9AOF94R1xQsU4Tgwic04UN7KX7qcXFKfiDPBhk9W3x0wxEkkA1heVYbwRQxT7x/mEObpJmvGs+JL8D404VXBF0anpDRIFGPxYa9n1zH5GAcBo9k5jHSPA+SzwGMtWfGAO2PLBNabZIq5R3iKK
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-04-24T23:33:20Z"
    mac: ENC[AES256_GCM,data:2PKa9f7IUe3tG3VJ7BjwjWfgJJhwMheNkttJW7srG9zJICha0xNCjqtR7pxjg6yswDtoIIViY2JlggEedgKmPGxzxwl4tML3IADaRtUfu8ZDm+QhFnolsb8EtG412VaB16qRSIbgHRn61+cgVbtmNsK1UqqEnmlBRcPDdNMNH9s=,iv:nCSTOddFYIV2Yd6JudaLpYt+DaVHPnqfvCoyupXebOQ=,tag:Fm5CnH0hBT3Zz1Jl+a8vsQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
