jupyterhub:
    hub:
        config:
            CanvasOAuthenticator:
                client_id: ENC[AES256_GCM,data:7tZa0h0tecSk5Ybd/YkjGV8=,iv:VjSVHbwY7OfyTgMc+HlDpiZNt7xU7VZKI8B0UQjpLQs=,tag:Vm2zFFj8uYnVRjzPtSmn9A==,type:str]
                client_secret: ENC[AES256_GCM,data:2f250ni+RssVwYA4OzkU1H5nGvyTPfNqZL/lxeuTdsHxlpCoNSgKgCfOeJZlhdmm9VcbG00GRv5YTmjiL9S9VA==,iv:UlZxTqEg9jjoNklf0dep63WeMa5nXRR+/8xL6DkqR4I=,tag:aGgg7SAOxO5quli2pzjD+g==,type:str]
                oauth_callback_url: ENC[AES256_GCM,data:rQ+ud8fBL7jslc5fRsB63aRYVXK8RXdYF3U2ST21B2xTVfsx0YXT6s5Q1cye/QH3lpDSmimLm9ITWLAaJEd7,iv:QVo+xhFh9d1NJhuwKQQwrNkPKSw/+75ioFOHk6h9yS4=,tag:z8VZWsfEWLO0yUTvifCBqA==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/ucb-datahub-2018/locations/global/keyRings/datahub/cryptoKeys/sops
          created_at: "2026-05-08T23:31:37Z"
          enc: CiUA67O9AMaOmQRS6xvYDzp3n59dhOVQLQiiV6/lwLH2FugY3TpAEkkAdEnSzvMgsXpmluj32FS1+dyDqFx5Js2hG5eLEgjOP1rgskQgIUCqFK1YeedAdG0FyY463Et/L7bvZjc5PlZRqaDPrehrQbyA
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-05-08T23:31:38Z"
    mac: ENC[AES256_GCM,data:B+u/xie31i+lfOFVvi5ClL87bkXlY3FK3l2rIJwSFn+yvUZvp66lmEnk4lyzQOgVBCgB4ZTRSWFXyJV/41hlY0XvJlbWtUbrUfoda1Qo2LmUYCtBd3VNrCDORltzW+0GhC7LG+C1MNt0PMbJjIyN4JgkyDlgEYl0JlGU9vtZKV4=,iv:5IEPILwe5hAWnhYgytySuTzop6dReTRhDK29qhqycoc=,tag:8RLqb30V606h4cC+VNhGUQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
