#!/bin/bash
set -euo pipefail

# 2024-01-13 sknapp: incompatible due to notebook 7
# jupyter contrib nbextensions install --sys-prefix --symlink
# jupyter nbextensions_configurator enable --sys-prefix
