#!/bin/bash

# Pull and run the Ollama Docker images - https://hub.docker.com/r/ollama/ollama
docker pull ollama/phi3
docker pull ollama/tinyllama

# Start the Ollama containers
docker run -d --name phi3_container ollama/phi3
docker run -d --name tinyllama_container ollama/tinyllama

