#!/usr/bin/env bash
set -eux

mkdir -p ${NB_PYTHON_PREFIX}/share/jupyter/lab/settings
cp -p overrides.json ${NB_PYTHON_PREFIX}/share/jupyter/lab/settings

# Install the MyST CLI - https://github.com/executablebooks/mystjs
npm install -g myst-cli
