jupyterhub:
    hub:
        config:
            CanvasOAuthenticator:
                client_id: ENC[AES256_GCM,data:yYqCC0Q/vOC6NpapeizwEGY=,iv:3ObI5WFyGVCWZ2uf0vsTF7lejieRsdARw3QePT9E+3s=,tag:+JMAp3aCa0KTxKyud7YvqQ==,type:str]
                client_secret: ENC[AES256_GCM,data:zN8f1ydVG4Tto4Oef2ua8quEiYGVL6UCZpoYVD22OLeUYUor7hxpuogGdGOK2O/f1eQgQLEvviE19fgDzkfwNA==,iv:VDqfUJHFH7OlIeplN3RfDX2ooPoHn3LvFjGj0J5n87w=,tag:apmlUaKD5u/9IM5TeZN7NQ==,type:str]
                oauth_callback_url: ENC[AES256_GCM,data:dDJAEEMk/7p/4vwHyXSCI7E6W26ucbZ9cQfG59HeTNjFTm8YOQBIumP/IPoZHSRBcBqYUg==,iv:sIn31EvpFmFHucXQSEF2nM/QRy2+ega2SxbD5V658yI=,tag:q9olnzleZvIPqwM+YV6xgg==,type:str]
        services:
            grouper-sync:
                name: ENC[AES256_GCM,data:HCHaLVLQrdMBelsG,iv:Z2oqIfZbBqwbL1wqEhLAnyGsQao/pWReopWaNnkXZ/E=,tag:VA9MuKcrsAb3LWm6yzFPFg==,type:str]
                command:
                    - ENC[AES256_GCM,data:kDVU+4PbjK93rTL6,iv:9SToU0L4R6DnoQb7qcCzhaqVs1ephqmgjmJEWgzFsJE=,tag:jl615i9KhJlzQmxx9ek7nw==,type:str]
                    - ENC[AES256_GCM,data:0OlPC82Vq0QFoAUfR7YAxAX0y/TLfDorRzg=,iv:+Lf/M/K5nSbBuausj4Bz831pcUpOzM4ToV7zwPCIfY0=,tag:kzJ0mdAIIwgpx3CQwjzOxA==,type:str]
                    - ENC[AES256_GCM,data:hBK4ivyr2LHxyeXXtWWqJgggbeW5YdINAezIWfCxX20=,iv:eePEAS+WTVwEy6z1H0GvKxQqeXmkCOCO4U86RR7+NnA=,tag:p7p1dSJk0y2OLuqQ8OnQYw==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/ucb-datahub-2018/locations/global/keyRings/datahub/cryptoKeys/sops
          created_at: "2026-05-08T23:32:10Z"
          enc: CiUA67O9AD3cIHmRBYy64LsAiOursSO3R1wg9e3Rd67rPXXOVvWLEkkAdEnSzm1R3v02svvEyh1Cv7MIFWZX0gx1xctlXHGOhv0+AYnWOCZxqLBulAu41HhoeWSCw6Htbo8Cj9qhPXTqm3xVsUXiqhiB
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-05-08T23:32:10Z"
    mac: ENC[AES256_GCM,data:sR06Bjw141Al19VZvvEUG7kpeQh0NPMfF6DLBua1d+aMiX2CbERw/MTPtgFgT7WuUN8lw+rGQqcGMskGSq5rAnROsgBA5jA/9NY7sy+6IQbtt4db+Qf/VGNrhHvlQGywqEgcJk3MgpEWLkdxZKXvSltKkJ+IuHyjfjs37feFjQM=,iv:XbpUWAkjiSuNcyZVOAobqM2THf7uuuZqJpJD0aWHyWI=,tag:p/ntX9qDyov7fc0lLtlEEw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
