jupyterhub:
    hub:
        config:
            CanvasOAuthenticator:
                client_id: ENC[AES256_GCM,data:CPUBFWkyVXYyAXz9dv9lrdM=,iv:PTV7J/21vOf+Up+rkxr03c1OozD2vZ7Y7d2mOwmWhM4=,tag:9nAiVxEXoDEL662EtrjpMw==,type:str]
                client_secret: ENC[AES256_GCM,data:TLKqOeV9/O5HVebdfS86MvY+sVSEQc6Pae6w+iJ7Kv0THusjMhZKy+YLLBWqmwBtW3KO0eAdEsE6kl69oN3j/Q==,iv:YsQBCPIyQFLc2/s9G07qIWy6hRX48iQKR67ORj24/AU=,tag:UOwBSEt+XLll5S4Gx36MMQ==,type:str]
                oauth_callback_url: ENC[AES256_GCM,data:NPbVHzCyb007Qbivfv13J71g57IXG3sZtzuG6IVx8943l2ZKHw+abXu0rMho44Xbk8TZ/Yhn5U9YSc0i,iv:4VSLVNEDxCBK9pUfov1ou5l+Lw/acal9mpKhVCDOg1I=,tag:wwjGOA4hl6uZJ5E4yT+HFA==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/ucb-datahub-2018/locations/global/keyRings/datahub/cryptoKeys/sops
          created_at: "2026-05-08T23:31:40Z"
          enc: CiUA67O9AHy81y3hhdNekPRj119PCio/uv1a3IPkz4UO+OGgaU9NEkkAdEnSzmEli7gjEsyh9kV+jcZG1hv8EX/93y1de16WLCsGMGtqV5UZpPEiJIlXiGTCNg/4L7nXsJZhGYDGK8MfVkLsrmfXkV0j
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-05-08T23:31:41Z"
    mac: ENC[AES256_GCM,data:6aqe+wZwUXy6y2ZeaBo5gQHtWS7abPspRg5C4PRORvhO5pnJyAkGv9mP+K44uQwWpRD8Ceq4jXR7XT4kJY/A5YY9OYhQC0YfjzwRqhtiVvgdRTQCcFg8vcox8tqwZoR7Qb13GlStRoomhcghGYuVxx5Fc+hRFgqU3uUH2rSNuvU=,iv:KmIcX2RWiWSc9dVI+lFximWM2pgtMRIRSyZlxhU8ENQ=,tag:i9E2iZYHFqzFpKr/vn7FbA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
