jupyterhub:
    hub:
        config:
            CanvasOAuthenticator:
                client_id: ENC[AES256_GCM,data:hIZFGUMgXdZ8YsCVpDvUoYQ=,iv:k0g545CbBaz2yyrCXqW67ZvysgF7oLBQ5XhhTDHAzW0=,tag:+MBdjg2yTOOpPFT89DSSrQ==,type:str]
                client_secret: ENC[AES256_GCM,data:WfyLdPW2EVPNZeOaYYmZQw4exD3BmwYqEMiXhzBTB0rF+JyTbSwnRi1W4mB0cUDyoZrPDPwW2PoGtM6+2jh81g==,iv:xFBLCiXsoCmyopGBvrTsVe5wxpIMaN+Eqt+92Y//0OA=,tag:ft1DX4WWTt9qRtRO6Bh36w==,type:str]
                oauth_callback_url: ENC[AES256_GCM,data:PRSNS+aVhboNp1HNi59k3pFOyNajQe5nEyD2kPy56vDW5LaugUu80tabDRTnWXNd8o64,iv:Jl/6P98Rn40h9cJaLTlmcX4sBgPzS41O6jyMvLTgOYU=,tag:iRoADM9Xusd3aTdL8ROHpw==,type:str]
        services:
            grouper-sync:
                name: ENC[AES256_GCM,data:Q3GiDLHx3bqbaP4G,iv:2cg1v68HCXiOy4/NmtL12+lZPvfCLKik+0I57aB7Lqo=,tag:d6/RcNp7AEC18eoaDvAYnQ==,type:str]
                command:
                    - ENC[AES256_GCM,data:wWQZo2y86WO9ktmj,iv:6U9CLJs5IfvdropKRO7JEUo0JFlWR1Zpd9yzHtPZwLs=,tag:zjLB258dTzIcnDJoxJLT1Q==,type:str]
                    - ENC[AES256_GCM,data:yTiRXmjcOk6479rZ+JselLl9/Uc6KR1Zcys=,iv:/2GsWVrlfof8XuD+GuhDQuCF/IHwr/VpkahhpmUw6lU=,tag:8CjYRdgCPIm4eUQFPBI1Sw==,type:str]
                    - ENC[AES256_GCM,data:CC2+jl1dEkRKyGACDVYiCBBdvFrNOM5OzMguauJSDek=,iv:CQSt1BdqBQma/d9S0C1h84Ul6fqzl/LxBp3RnCacE6c=,tag:O8wAFBfukVo+s77e82oEEQ==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/ucb-datahub-2018/locations/global/keyRings/datahub/cryptoKeys/sops
          created_at: "2026-05-08T23:32:24Z"
          enc: CiUA67O9AAIKKKfH4SSSC2TtRFIDNmztcX1U9h6nKs6UDQguFoj8EkkAdEnSzijbICwj08Bp3oJoZhNnoeLi04flzwD2PKTchESREZrT0rTSyz28D8rmF5D/CKC8FBQY4teR/gXn9fd/VUMX44wARl9C
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-05-08T23:32:24Z"
    mac: ENC[AES256_GCM,data:H4vhTdEJ1czgpD3Ot6BZzSD4q6nLYVVapN6HmkWaYdB5Ls3uz9ny6WvTejJfVCmWn0ZVkBs2Tv/6tiIVEg+fTV/L6gTvYfjawGiDL2FWBuWp2LMaBYD5Amw32cLUUiq+y9TuDg5tlk9GJM4edtDZLE9SrdjjdrkmT7SJluXsIYs=,iv:s2uYDvTamGBtr3Xgq207qoRMjZ1y65PoAZZcwHyGCZU=,tag:H7KH7W8NXRoemeq/fBo+UQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
