jupyterhub:
    hub:
        config:
            CanvasOAuthenticator:
                client_id: ENC[AES256_GCM,data:G1v06zL+rsz2hlMLLsrobLI=,iv:/kBFn4Qyxr6JnFfbEGgRkcgbJeGf0bxc5kVi/Pjzyf4=,tag:Di+OlR0/d5cjkg4jOj9jNg==,type:str]
                client_secret: ENC[AES256_GCM,data:5bJjwp5wx3LRysmBIhIKxhj5iezTmuDQPugfUtoxbMhth8ByhhxSh78JtnclI1lBNNTFL4VC3BU5Zno4RCgSAQ==,iv:IM41d9+1JIFeXRKR14MBzNW8/1HZvcthGy7ypbmuStk=,tag:gjILQx5HU4xWrOveAZAs1g==,type:str]
                oauth_callback_url: ENC[AES256_GCM,data:wFwGNx5gtnHelXwzTDWheMvvv+c9KWB0iXXcuzibhmRgeoNrpRTZxz4hCqTkbTUjWac4qR474XuBLRo=,iv:MmDu9//QCKOqjS0wmw1jCGkKBprjB0RzkTMJj8QZSik=,tag:2ygovogmj+jyVP3C4lHCbw==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/ucb-datahub-2018/locations/global/keyRings/datahub/cryptoKeys/sops
          created_at: "2026-05-08T23:31:55Z"
          enc: CiUA67O9AMHAaGMeEiwdymOF7lHyGAsHv2e5bRTw00AO+bb3W1UGEkkAdEnSzgclGpNpQauX1g1lWULL1hn/0f/17OWqivh+U2YJSXEnqkYBKbhTpXBvi1DIuE6cTNJyYQi4maIoxaJEF5UNKz3T47d2
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-05-08T23:31:55Z"
    mac: ENC[AES256_GCM,data:NcbQOabwQ7sgr1PQnGAiJUSCTk+ugm/jqMcbhtDo084kuIApLwRimx6FXLdDzi6KeNSUkJwuXp5JNpKM4dLYII5iCWTVWhWr7sfhfGOjK0Ndkl0HeIkWmR6nYQSRGawe+O0Y3eHo36oIogEvYU6uck4esYMGzte2YbeD2bw3BqA=,iv:j9tXQAIQQ96C5McrqI6cDqPE9UxHZflKVaQkZZvhI/w=,tag:GBSczxkIrymZTuMxxxkPGA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
