jupyterhub:
    hub:
        config:
            CanvasOAuthenticator:
                client_id: ENC[AES256_GCM,data:M0I5X90Cq1hErG0eC+4Ftaw=,iv:tU66GiOnB6ul+30+mRZ/KC878F1+I3+vIvDL2Hk7c7s=,tag:9qS9OffIBC6JKBlpPJSoUA==,type:str]
                client_secret: ENC[AES256_GCM,data:j/82Mh8Kpf0THKKVWXzDPnHL6uE99yFJeXbjEehGA96eRksZI0Z5CIpMk+SBC5dV59G9mx9fcxvLZ6mfYnPlPQ==,iv:c5mEUqHdqNfqTuPtRr5NVCg92IBo+93UiGEonFJcaas=,tag:Qu1zRaSJ948BfD5I0GuDrg==,type:str]
                oauth_callback_url: ENC[AES256_GCM,data:C4C4hEXdV9o+bUiqJ402Lqp/kMRzeqHhGGR0nscvg5EOa+rHxf3us1WmkrB+dx8nMc6KaWkTEA==,iv:1N7rnvYEWN/7/JPMzs9p3JbKzhNFBBX1upxkyHTfsi4=,tag:zdeRx46FwuaJm8jYhyIgOg==,type:str]
        services:
            grouper-sync:
                name: ENC[AES256_GCM,data:Q6dWiphCHpIQsGKh,iv:ss60TMnquk+W21wzr9YBqQ21RvYCbswA7nfIZgy2iYY=,tag:Q/LXHM5A4dGlo+IrrnrIag==,type:str]
                command:
                    - ENC[AES256_GCM,data:FiSSEd/Qo45msOr0,iv:7vG8mR9wiD/yvFnj3i/UBMy2oTO5gYAJ1lbpOkO3470=,tag:+nIalGfT7TQ+jLkGVlIf0w==,type:str]
                    - ENC[AES256_GCM,data:NgWHCr7QIhogcqxNrhZLYmklApiBSptrYPE=,iv:murFQnyM1PnNFCiNhBRCbzW52GOtLNQ9/OIw5R8TnTY=,tag:4mkncecttSeIaJ+DXkYCOQ==,type:str]
                    - ENC[AES256_GCM,data:c2A0iTeVJ66+SCbCkZWcISgIMfiWlmbcdqD/WOhmnjI=,iv:eJ1glZgGqkYFF+p/ySgC2GybutUiGNaSEH04FGWGdX4=,tag:BTYNoUCCrTCd2ynq/R9K+g==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/ucb-datahub-2018/locations/global/keyRings/datahub/cryptoKeys/sops
          created_at: "2026-05-08T23:32:19Z"
          enc: CiUA67O9ACOAxsLvK4neJ6YJHjdR6zfcZls2HkH5n3Fv58R2+sniEkkAdEnSzmG7qduF7WVVSS//sxjql2iT1Ty83px7LbbC0s/QRnY7n8ffVwXu+tkHf2oau6HVdDsDJs37C+nkqZg29MwUFxFMyquB
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-05-08T23:32:20Z"
    mac: ENC[AES256_GCM,data:VUaMT18fQSJAEj/dTSFWnGBpPZ8Wbp7rlaeFYog0hWj5OPA+NZEVsXG/VQ2hRvEgOz/AjVgYHqS+4CfQxTIiyLoSySgToTShjXzPQbXEy1zwugLbPeqIrehU+02IGsNrAwg8ZeqjW/heWypZ94wUb7BY6cI7GN2k4+LKmOxkAJY=,iv:DiyQwP73yNt5oIBWeCduiuR1VfkAAIzPhU7/Y5b6ZiI=,tag:vRGVs4OmHLlIGRlGjb3nig==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
