jupyterhub:
    hub:
        config:
            CanvasOAuthenticator:
                client_id: ENC[AES256_GCM,data:iYxNt3qDA8+4qR2oFDSHR4c=,iv:4YsaCG2hkn8NrLaCPcBFSnbU5xEwa5mUDaf1RLIwsxw=,tag:bN8MOx8DOc+20hUGEHnhgg==,type:str]
                client_secret: ENC[AES256_GCM,data:EsIK6HytIMz+O/uabT6YkJ0nWL32mzOSvGsMyhpyLNIJpVarPtH+LOFQA7volbFtpSjeZEi5fAvxoGU1BPnlzA==,iv:Drf7QIdxKVoiiJpvzC/gsCh3bnmtVoATlMKZy8G7LHw=,tag:y4qR6EzuCHIzbj6baNySfQ==,type:str]
                oauth_callback_url: ENC[AES256_GCM,data:8cZZm/1iTE3zbLUPz3Ny4C1OYDTd5hoV5/SzKjVmIGpO9YZ6YhN3FXylzC2n9NU+B6fvFo2iS8uVJuHvxYiT,iv:qPDryPtHX1Mvq/5fuFiCHmWVKbgonJ+vjt42p3fy+Is=,tag:Zsa5hwpuSdFs45/VYGhHpA==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/ucb-datahub-2018/locations/global/keyRings/datahub/cryptoKeys/sops
          created_at: "2026-05-08T23:31:50Z"
          enc: CiUA67O9ACksouonyrm2Fj+JbR9bxtSvi74uS8ynkLN9Fh/jMeaREkkAdEnSzj1ctctCBopMgLP1moNigpymh8jd7JxsGfEn1CNyLyWLcylrGMQq7AB9rGlY43ub1r+ODeCkyDxvfHm2TgrwmJZFAd2V
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-05-08T23:31:51Z"
    mac: ENC[AES256_GCM,data:oknUmP4aqN3unCfpQSFDtIuhT0Pc6F4tIH1jclYhXcdQumoXeJSLIK9ebc+zNODRBn4vKUq2n9oeTS+N1BbYtLkvA5qrL+vuIv4CjAIuwVtyYxUmnLDccuHjkcxzIpqBg9EydFH2+xwlJ1d34qfNosJKD5VEJL6kwQS7hQCHBG0=,iv:b7pm9D+IUU6rqAe9vwRWUyD1FHpZuKMkqjw/qO8Vvf8=,tag:eoRxsCOfGTF8rA9iY1/F6A==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
