nfsPVC:
  enabled: true
  nfs:
    serverIP: 10.247.79.74

jupyterhub:
  custom:
    group_profiles:
      # DataHub Infrastructure staff
      # https://bcourses.berkeley.edu/courses/1524699/groups#tab-80607
      course::1524699::group::all-admins:
        extraVolumeMounts:
          shared-readwrite:
            name: home
            mountPath: /home/jovyan/shared-readwrite
            subPath: _shared


  ingress:
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod

  scheduling:
    userScheduler:
      nodeSelector:
        hub.jupyter.org/pool-name: core-pool-2024-05-08
  proxy:
    chp:
      nodeSelector:
        hub.jupyter.org/pool-name: core-pool-2024-05-08
      resources:
        requests:
          # FIXME: We want no guarantees here!!!
          # This is lowest possible value
          cpu: 0.001
          memory: 3Gi
        limits:
          memory: 3Gi

    traefik:
      nodeSelector:
        hub.jupyter.org/pool-name: core-pool-2024-05-08

  hub:
    nodeSelector:
      hub.jupyter.org/pool-name: core-pool-2024-05-08
    config:
      OAuthenticator:
        allow_all: False
        allowed_groups:
          # Data 8, Summer 2025
          # https://bcourses.berkeley.edu/courses/1544818
          - "course::1544818"
          # Data 8, Fall 2025
          # https://bcourses.berkeley.edu/courses/1544818
          - "course::1547037"
          # Data 8, Spring 2026
          # https://bcourses.berkeley.edu/courses/1551541
          - "course::1551541"
          # DataHub staff
          - "course::1524699::group::all-admins"
    loadRoles:
      # datahub staff
      datahub-staff:
        description: Enable admin for datahub staff
        # this role provides permissions to...
        scopes:
          - admin-ui
          - admin:groups
          - admin:users
          - admin:servers
          - read:roles
          - read:hub
          - access:servers
        # this role will be assigned to...
        groups:
          - course::1524699::group::all-admins
      course-staff-1544818:
        ## Course: DataC8 Bcourses ID: 1544818 End Date: 08/15/2025 
        ## See issue https://github.com/berkeley-dsep-infra/datahub/issues/7262 for more details.
        description: Enable course staff to view and access servers.
        scopes:
          - admin-ui
          - list:users!group=course::1544818
          - admin:servers!group=course::1544818
          - access:servers!group=course::1544818
        groups:
          - course::1544818::enrollment_type::teacher
          - course::1544818::enrollment_type::ta
  singleuser:
    image:
      name: us-central1-docker.pkg.dev/ucb-datahub-2018/user-images/data8-user-image
      tag: e4ac1bdd3dcd
    extraFiles:
      # DH-596
      jupyter-lab-overrides:
        mountPath:  /srv/conda/share/jupyter/lab/settings/overrides.json
        stringData:  |
          {
            "@jupyterlab/notebook-extension:tracker": {
              "windowingMode": "defer"
            }
          }
      # DH-305
      remove-exporters:
        mountPath: /etc/jupyter/jupyter_notebook_config.py
        stringData: |
          c.QtPDFExporter.enabled = False
          c.QtPNGExporter.enabled = False
          c.WebPDFExporter.embed_images = True
    extraEnv:
      # Unset NotebookApp from hub/values. Necessary for recent lab versions.
      JUPYTERHUB_SINGLEUSER_APP: "jupyter_server.serverapp.ServerApp"
    nodeSelector:
      hub.jupyter.org/pool-name: data8-pool
    defaultUrl: /tree
    storage:
      type: static
      static:
        pvcName: home-nfs-v3
        subPath: "{username}"
    cpu:
      # https://github.com/berkeley-dsep-infra/datahub/issues/2966
      guarantee: 0.05
      limit: 1
    memory:
      guarantee: 1G
      limit: 1G
