nfsPVC:
  enabled: true
  nfs:
    serverIP: 10.240.85.114

jupyterhub:
  ingress:
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod

  scheduling:
    userScheduler:
      nodeSelector:
        hub.jupyter.org/pool-name: core-pool-2024-05-08
  proxy:
    chp:
      nodeSelector:
        hub.jupyter.org/pool-name: core-pool-2024-05-08

  hub:
    extraConfig:
      # Use 1x-<title> in `common.yaml` extraConfig values.
      # We want these to come *after* the extraConfig values
      # in `values.yaml`. Since these are ordered alphabetically,
      # 1x-<title> used in `common.yaml` will come after
      # 0x-<title> used in `values.yaml` - so config set here
      # will override config set in `values.yaml`
      11-working-dir: |
        # Rocker based images have 'rstudio' as user id 1000
        # so let's stick to that, and use /home/${NB_USER}
        # consistently.
        c.KubeSpawner.working_dir = '/home/rstudio'
    nodeSelector:
      hub.jupyter.org/pool-name: core-pool-2024-05-08
    config:
      OAuthenticator:
        allow_all: False
        allowed_groups:
          # Stat 20, Summer 2025; https://bcourses.berkeley.edu/courses/1545303
          - "course::1545303"
          # Stat 20, Fall 2025; https://bcourses.berkeley.edu/courses/1548266
          - "course::1548266"
          # Stat 20, Spring 2026; https://bcourses.berkeley.edu/courses/1551619
          - "course::1551619"
          # DataHub staff
          - "course::1524699::group::all-admins"

    loadRoles:
      # datahub staff
      datahub-staff:
        description: Enable admin for datahub staff
        # this role provides permissions to...
        scopes:
          - admin-ui
          - admin:groups
          - admin:users
          - admin:servers
          - read:roles
          - read:hub
          - access:servers
        # this role will be assigned to...
        groups:
          - course::1524699::group::all-admins
      course-staff-1551619:
        ## Course: Stat20 Bcourses ID: 1551619 End Date: 5/15/2026 
        description: Enable course staff to view and access servers.
        scopes:
          - admin-ui
          - list:users!group=course::1551619
          - admin:servers!group=course::1551619
          - access:servers!group=course::1551619
        groups:
          - course::1551619::enrollment_type::teacher
          - course::1551619::enrollment_type::ta

  singleuser:
    image:
      name: us-central1-docker.pkg.dev/ucb-datahub-2018/user-images/stat20-user-image
      tag: 8163bd4738e1
    extraFiles:
      # DH-216
      remove-exporters:
        mountPath: /etc/jupyter/jupyter_notebook_config.py
        stringData: |
          c.QtPDFExporter.enabled = False
          c.QtPNGExporter.enabled = False
          c.WebPDFExporter.enabled = False
    extraEnv:
      # Unset NotebookApp from hub/values. Necessary for recent lab versions.
      JUPYTERHUB_SINGLEUSER_APP: "jupyter_server.serverapp.ServerApp"
    nodeSelector:
      hub.jupyter.org/pool-name: stat20-pool
    defaultUrl: /rstudio
    storage:
      # Rocker based images have 'rstudio' as user $1000
      # so let's stick to that, and use /home/${NB_USER}
      # consistently.
      homeMountPath: /home/rstudio
      type: static
      static:
        pvcName: home-nfs-v3
        subPath: "{username}"
      extraVolumeMounts:
        shared-readonly:
          name: home
          mountPath: /opt/shared
          subPath: _shared
          readOnly: true
    memory:
      guarantee: 1024M
      limit: 2048M

  custom:
    group_profiles:
      # DataHub Infrastructure staff
      # https://bcourses.berkeley.edu/courses/1524699/groups#tab-80607
      course::1524699::group::all-admins:
        mem_limit: 12G
      # Shared directory to read logs data from every semester
        extraVolumeMounts:
          admins-shared:
            name: home
            mountPath: /home/jovyan/admins-shared
            subPath: _shared-admins
            readOnly: true
