jupyterhub:
    hub:
        config:
            CanvasOAuthenticator:
                client_id: ENC[AES256_GCM,data:xBn597X2gfVC6qy+9A8hThg=,iv:Qm6jO99yveDg0/NIM0RvyV7rdZ+vnZMoetqJeHAIRvk=,tag:Xcpcke5B94um4bPVr5KsrQ==,type:str]
                client_secret: ENC[AES256_GCM,data:bUJZxRRT+nchsUzfS1MmoUPpKoLkHREImHW9IlxHXTVff+SXIx5lOnFFWoUHoIZQAjhG0vBAd3rm5IpHBe6U8g==,iv:Pjx4MrGD09zYUk4haTfyH0q9LKP8piQZHEiaX0UhMxU=,tag:NP1Xx897/yEZMjr775hCXQ==,type:str]
                oauth_callback_url: ENC[AES256_GCM,data:S8VubrafMaL2H4XXTIeQYJ5jSwhBxfkXkivdU+zOZNGNk+HrO0tmMIrTNAGytcc5hhaf8/dbeFQnp5t+uLSY4urUHugFlz22zQ==,iv:4GSA1f/u83Yg79LmT8qmxAeSSZ1kpp1OfOdDf01TOeE=,tag:6qHLWynFIP2PdUrUFTHPeg==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/ucb-datahub-2018/locations/global/keyRings/datahub/cryptoKeys/sops
          created_at: "2026-05-08T23:32:11Z"
          enc: CiUA67O9AIun4U8VZ+YbxH2ZNpQ7H16Nj8aX0yr5oH2Cylg8XA7kEkkAdEnSziQJSGq7E3n4xJ6GvCY9ZQfsVgxdVfXXp9suM9Jh+bdilvPeC1CVMwW84RdnybAb3EAzW3FtKvZ7fPHIt/m711G9zg4Z
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-05-08T23:32:12Z"
    mac: ENC[AES256_GCM,data:booEVSBzZBSc0FfOTOnpeGiVIrtf10LtU7ep7XNvK2DffMuaKG4JMHd0VM5NjQ2JYWqQKuscsqk/g4QjKb9JZuPpLTSx903oOUJ3MLdr+pYEjCZPIf8LayorPONxUWdCve8h+NrNWmULKJcem/WgfnYm8GKDiokghXWotAEEZbY=,iv:yFHEQMBue6BjJH24T3PP4Us2sKjHY6LpHR7HxPTqKz8=,tag:MmzTbpDQ6gcxA0eaHvFdQg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
