jupyterhub:
    hub:
        config:
            CanvasOAuthenticator:
                client_id: ENC[AES256_GCM,data:dn8UvfgRbNDv7GVBtQLWiMs=,iv:xVqD6MZ/nGtzx4rip1ziwHtuXy8UQbA2ontcVrf3ufw=,tag:NeWvDKKU5B+q4g2fyjqOww==,type:str]
                client_secret: ENC[AES256_GCM,data:AZzVxke803Z+r79pivXB3rqYqsTabWMjH4lRtx3n8ccjX0JJAe6AatMAKY/1qVTK0Pel2q4bo9SCZlJ9W1gZHQ==,iv:Go+DkU+DOUHYb5QfdCYSJbQxqhbx+2R1LYHSNH4xjn0=,tag:Mto9bocvp41lUrmQaXg3Iw==,type:str]
                oauth_callback_url: ENC[AES256_GCM,data:OeWUB7i/OexP6Pym7OvTXKA68NYNwKnCJ6lsvNS9D9DNc9GEf0gtIoVHp679cwwf4Nbcw7e9JSNIogVKpXxhWuHLHgnEXL53xqrsL8cHgWAS,iv:9K1zrKDPnlSNLGanb3JmnvJ4aaOlwXoXrvlcboixI9Q=,tag:evbJrDjnhhDrnXDxFYE4eA==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/ucb-datahub-2018/locations/global/keyRings/datahub/cryptoKeys/sops
          created_at: "2026-05-08T23:31:42Z"
          enc: CiUA67O9AFYF6XvD9Kpl3g4IG1dB4fTdvSsK0lxTW4PKstoZYXWWEkkAdEnSzk6/pBCoV+JNgTMyvjcl4Mv8S6Vo8oIiOoFVrdV7yehQC7HE0P3d34ipbTC9suX+cpKkt9GE51pZaqUALlh7R3hyiqKE
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-05-08T23:31:42Z"
    mac: ENC[AES256_GCM,data:pxuOIstpwuoGKkffiEcMOYWhslPkuvKuIgKTWbV+C4n6WHEovD6+Uo1tvBVuVE6d5xIEe57qv3tX2LDW+UetDIhb4aKWVvdBpi0DdVMokev85c75uOAtwEc6pHNNzZ4wGlJtXxJ6TV5Oh9ADprX10hF53Jc6ggMRyh+V6pQZHc8=,iv:ra2gwCGi/9gkxPO+V2NHIJ3G1NB3eraC4T+wKmOX9Eo=,tag:BFVCWYD8+5YnzuT+0w9eHQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
