
nfsPVC:
  enabled: true
  nfs:
    serverIP: 10.49.181.18

etcGitConfig:
  enabled: true
  gitconfig: |
    [credential "https://github.com"]
      helper = !git-credential-github-app --app-key-file /etc/github/github-app-private-key.pem --app-id 94384
      useHttpPath = true

jupyterhub:
  ingress:
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
  scheduling:
    userScheduler:
      nodeSelector:
        hub.jupyter.org/pool-name: core-pool-2024-05-08
  hub:
    config:
      Authenticator:
        auto_login_oauth2_authorize: True
    loadRoles:
      # datahub staff
      datahub-staff:
        description: Enable admin for datahub staff
        # this role provides permissions to...
        scopes:
          - admin-ui
          - admin:groups
          - admin:users
          - admin:servers
          - read:roles
          - read:hub
          - access:servers
        # this role will be assigned to...
        groups:
          - course::1524699::group::all-admins

   # Linguistics 243, Configs required till July 1, 2026, https://github.com/berkeley-dsep-infra/datahub/issues/6604
      course-staff-1541622:
      #  description: Enable course staff to view and access servers.
      #  # this role provides permissions to...
        scopes:
          - admin-ui
          - list:users!group=course::1541622
          - admin:servers!group=course::1541622
          - access:servers!group=course::1541622
      #  # this role will be assigned to...
        groups:
          - course::1541622::enrollment_type::teacher
          - course::1541622::enrollment_type::ta

   # Econ 140, Summer Session C, https://github.com/berkeley-dsep-infra/datahub/issues/7128
      course-staff-1545078:
      #  description: Enable course staff to view and access servers.
      #  # this role provides permissions to...
        scopes:
          - admin-ui
          - list:users!group=course::1545078
          - admin:servers!group=course::1545078
          - access:servers!group=course::1545078
      #  # this role will be assigned to...
        groups:
          - course::1545078::enrollment_type::teacher
          - course::1545078::enrollment_type::ta
      course-staff-1551226:
        ## Course: There are two related courses: Computational modeling of language, Computational linguistics Bcourses ID: 1551226 End Date: 06/01/2026 
        ## See issue https://github.com/berkeley-dsep-infra/datahub/issues/7822 for more details.
        description: Enable course staff to view and access servers.
        scopes:
          - admin-ui
          - list:users!group=course::1551226
          - admin:servers!group=course::1551226
          - access:servers!group=course::1551226
        groups:
          - course::1551226::enrollment_type::teacher
          - course::1551226::enrollment_type::ta
      course-staff-1551190:
        ## Course: There are two related courses: Computational modeling of language, Computational linguistics Bcourses ID: 1551190 End Date: 06/01/2026 
        ## See issue https://github.com/berkeley-dsep-infra/datahub/issues/7822 for more details.
        description: Enable course staff to view and access servers.
        scopes:
          - admin-ui
          - list:users!group=course::1551190
          - admin:servers!group=course::1551190
          - access:servers!group=course::1551190
        groups:
          - course::1551190::enrollment_type::teacher
          - course::1551190::enrollment_type::ta
      course-staff-1551764:
        ## Course: Econ 148 Bcourses ID: 1551764 End Date: 05/15/2026 
        ## See issue https://github.com/berkeley-dsep-infra/datahub/issues/7925 for more details.
        description: Enable course staff to view and access servers.
        scopes:
          - admin-ui
          - list:users!group=course::1551764
          - admin:servers!group=course::1551764
          - access:servers!group=course::1551764
        groups:
          - course::1551764::enrollment_type::teacher
          - course::1551764::enrollment_type::ta
    nodeSelector:
      hub.jupyter.org/pool-name: core-pool-2024-05-08
    initContainers:
      # There's another sidecar, specified in `secrets/staging.yaml` and `secrets/prod.yaml`
      # that keeps this up to date. https://github.com/jupyterhub/kubespawner/issues/468
      # should help us move that back here.
      - name: templates-clone
        image: alpine/git
        args:
          - clone
          - --depth=1
          - --single-branch
          - --
          - https://github.com/berkeley-dsep-infra/datahub-homepage
          - /srv/repo
        securityContext:
          runAsUser: 1000
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
        volumeMounts:
          - name: custom-templates
            mountPath: /srv/repo
    extraVolumes:
      - name: custom-templates
        emptyDir: {}
    extraVolumeMounts:
      - mountPath: /usr/local/share/jupyterhub/custom_templates
        name: custom-templates
        subPath: "templates"
      - mountPath: /usr/local/share/jupyterhub/static/extra-assets
        name: custom-templates
        subPath: "extra-assets"
    extraConfig:
      04-custom-theme: |
        c.JupyterHub.template_paths = ['/usr/local/share/jupyterhub/custom_templates/']
        # following two lines fixes DH-558
        c.JupyterHub.tornado_settings = {'headers': {'Content-Security-Policy': "frame-ancestors *;"}}
        c.Spawner.args = ['--NotebookApp.tornado_settings={"headers":{"Content-Security-Policy": "frame-ancestors *;"}}']

  proxy:
    chp:
      nodeSelector:
        hub.jupyter.org/pool-name: core-pool-2024-05-08
      resources:
        requests:
          # FIXME: We want no guarantees here!!!
          # This is lowest possible value
          cpu: 0.001
          memory: 3Gi
        limits:
          memory: 3Gi

  singleuser:
    image:
      name: us-central1-docker.pkg.dev/ucb-datahub-2018/user-images/datahub-user-image
      tag: b82c68dd2433
    extraEnv:
      GH_SCOPED_CREDS_CLIENT_ID: Iv23ct7Qx1mAotaIIYx9
      GH_SCOPED_CREDS_APP_URL: https://github.com/apps/berkeley-datahub-git-access
      # Unset NotebookApp from hub/values. Necessary for recent lab versions.
      JUPYTERHUB_SINGLEUSER_APP: "jupyter_server.serverapp.ServerApp"
    nodeSelector:
      hub.jupyter.org/pool-name: datahub-pool
    storage:
      type: static
      static:
        pvcName: home-nfs-v3
        subPath: "{username}"
      extraVolumes:
        etc-gitconfig:
          name: etc-gitconfig
          secret:
            secretName: user-etc-gitconfig
      extraVolumeMounts:
        gitconfig:
          name: etc-gitconfig
          mountPath: /srv/conda/etc/gitconfig
          subPath: gitconfig
          readOnly: true
        private-key:
          name: etc-gitconfig
          mountPath: /etc/github/github-app-private-key.pem
          subPath: github-app-private-key.pem
          readOnly: true
        # RStudio can't write session files to anywhere except ~/.rstudio -
        # only way to change that is by setting $HOME. So instead, we just
        # bind mount a fresh directory on top of ~/.rstudio!
        rstudio-home:
          name: home
          mountPath: /home/jovyan/.rstudio
          subPath: '{username}/.datahub-rstudio'
    extraFiles:
      # DH-305
      remove-exporters:
        mountPath: /etc/jupyter/jupyter_notebook_config.py
        stringData: |
          c.QtPDFExporter.enabled = False
          c.QtPNGExporter.enabled = False
          c.WebPDFExporter.embed_images = True
    memory:
      guarantee: 512M
      limit: 1G


  custom:
    group_profiles:
      # DataHub Infrastructure staff
      # https://bcourses.berkeley.edu/courses/1524699/groups#tab-80607
      course::1524699::group::all-admins:
        mem_limit: 4096M
        mem_guarantee: 4096M
      course::1552265:
        ## Course Name: LEGALST 123 Data Prediction & Law Bcourses ID: 1552265 End Date: 05/16/2026
        ## See issue https://github.com/berkeley-dsep-infra/datahub/issues/7843 for details.
        mem_limit: 4G
        mem_guarantee: 2G
      course::1552731:
        ## Course Name: Envecon 153 Bcourses ID: 1552731 End Date: End of Spring semester
        ## See issue https://github.com/berkeley-dsep-infra/datahub/issues/7898 for details.
        mem_guarantee: 2G
        mem_limit: 4G
      course::1551764:
        ## Course Name: Econ 148 Bcourses ID: 1551764 End Date: 05/01/2026
        ## See issue https://github.com/berkeley-dsep-infra/datahub/issues/7902 for details.
        mem_limit: 4G
        mem_guarantee: 2G
      course::1550885:
        ## Course Name: DEMOG-130: Demography of Deaths, Diseases, and Disasters Bcourses ID: 1550885 End Date: May/8/2026
        ## See issue https://github.com/berkeley-dsep-infra/datahub/issues/8001 for details.
        mem_limit: 2G
        mem_guarantee: 1G

    bcourses_shared:
      2026-spring:
        - "course::1551764"
