name: Deploy node placeholder helm chart

permissions:
  contents: read
  id-token: write

on:
  workflow_dispatch:
  push:
    branches:
      - staging

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get PR labels
        id: pr-labels
        uses: irby/get-labels-on-push@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Check out the image repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # OR "2" -> To retrieve the preceding commit.

      - name: Check if the node placeholder helm chart needs to be deployed
        run: |
          echo "PR labels: ${{ steps.pr-labels.outputs.labels }}"
          for label in $(echo -e "${{ steps.pr-labels.outputs.labels }}"); do
            if [[ "$label" == node-placeholder-* ]]; then
              echo "Deploying node placeholder charts!"
              echo "DEPLOY=1" >> $GITHUB_ENV
            fi
          done

      - name: Authenticate to Google Cloud
        if: ${{ env.DEPLOY }}
        uses: google-github-actions/auth@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          workload_identity_provider: projects/${{ secrets.GCP_PROJECT_NUMBER }}/locations/global/workloadIdentityPools/github-pool/providers/github-provider
          service_account: ${{ secrets.HUBPLOY_SA }}@${{ secrets.GCP_PROJECT_ID }}.iam.gserviceaccount.com

      - name: Install Google Cloud SDK
        if: ${{ env.DEPLOY }}
        uses: google-github-actions/setup-gcloud@v2
        with:
          install_components: 'gke-gcloud-auth-plugin'

      - name: Install SOPS
        if: ${{ env.DEPLOY }}
        run: |
          mkdir -p ${HOME}/bin
          curl -sSL https://github.com/getsops/sops/releases/download/v3.9.0/sops-v3.9.0.linux.amd64 -o ${HOME}/bin/sops
          chmod 755 ${HOME}/bin/sops
          echo "${HOME}/bin" >> $GITHUB_PATH

      - name: Store SOPS secret in a file
        if: ${{ env.DEPLOY }}
        run: |
          cat << EOF > ${HOME}/sops.key
          ${{ secrets.SOPS_KEY }}
          EOF
          echo "GOOGLE_APPLICATION_CREDENTIALS=${HOME}/sops.key" >> $GITHUB_ENV

      - name: Install Helm
        if: ${{ env.DEPLOY }}
        run: |
          helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
          helm repo update

      - name: Get GKE credentials
        if: ${{ env.DEPLOY }}
        run: |
          gcloud container clusters get-credentials spring-2024 \
            --region=us-central1 \
            --project=${{ secrets.GCP_PROJECT_ID }}

      - name: Deploy node placeholder helm chart
        if: ${{ env.DEPLOY }}
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ runner.temp }}/sops-key.json
        run: |
          cat > "$GOOGLE_APPLICATION_CREDENTIALS" <<'EOF'
          ${{ secrets.SOPS_KEY }}
          EOF

          sops -d -i node-placeholder/secrets.yaml

          rm -f "$GOOGLE_APPLICATION_CREDENTIALS"

          helm upgrade \
            --install --wait \
            --namespace=node-placeholder \
            node-placeholder node-placeholder \
            -f node-placeholder/secrets.yaml
