# This workflow will determine if the base hub image and/or single-user server
# image for any or all hubs has has changed, and if so, deploy accordingly.
#
name: Deploy staging and prod hubs
on:
  workflow_dispatch:
  push:
    branches:
      - staging
      - prod

jobs:
  deploy-hubs-to-staging:
    if: github.event_name == 'push' && github.ref == 'refs/heads/staging'
    runs-on: ubuntu-latest
    steps:
      - name: Get PR labels
        id: pr-labels
        uses: irby/get-labels-on-push@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Check for hubs that need deploying from the labels on the merge commit to staging
        run: |
          echo "PR labels: ${{ steps.pr-labels.outputs.labels }}"
          # If the PR labels "hub-images" or "jupyterhub-deployment" are
          # present, this means the base hub image has changed, and all hubs
          # (staging or prod) need to be redeployed.
          #
          if [[ -n ${GITHUB_PR_LABEL_HUB_IMAGES} || -n ${GITHUB_PR_LABEL_JUPYTERHUB_DEPLOYMENT} ]]; then
            echo "DEPLOY=1" >> $GITHUB_ENV
          # Otherwise, check to see if the PR labels contain any hubs, and 
          # deploy just those hubs to staging.
          #
          else
            for label in $(echo -e "${{ steps.pr-labels.outputs.labels }}"); do
              if [[ "$label" == hub-* ]]; then
                echo "DEPLOY=1" >> $GITHUB_ENV
              fi
            done
          fi

      - name: Check out the image repo
        if: ${{ env.DEPLOY }}
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # OR "2" -> To retrieve the preceding commit.

      - name: Setup python
        if: ${{ env.DEPLOY }}
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        if: ${{ env.DEPLOY }}
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Google Cloud SDK
        if: ${{ env.DEPLOY }}
        uses: google-github-actions/setup-gcloud@v2
        with:
          install_components: 'gke-gcloud-auth-plugin'

      - name: Install SOPS
        if: ${{ env.DEPLOY }}
        run: |
          mkdir -p ${HOME}/bin
          curl -sSL https://github.com/getsops/sops/releases/download/v3.9.0/sops-v3.9.0.linux.amd64 -o ${HOME}/bin/sops
          chmod 755 ${HOME}/bin/sops
          echo "${HOME}/bin" >> $GITHUB_PATH

      - name: Store SOPS secret in a file
        if: ${{ env.DEPLOY }}
        run: |
          cat << EOF > ${HOME}/sops.key
          ${{ secrets.SOPS_KEY }}
          EOF
          echo "GOOGLE_APPLICATION_CREDENTIALS=${HOME}/sops.key" >> $GITHUB_ENV
      
      - name: Check for 'add shared directories' label and extract info
        id: check-add-shared-label
        run: |
          LABELS="${{ steps.pr-labels.outputs.labels }}"
      
          # Check for 'add shared directories'
          if echo "$LABELS" | grep -qw "add-shared-directories"; then
            echo "Label 'add shared directories' is present."
            echo "add_shared_directories=true" >> $GITHUB_OUTPUT
      
            # Extract all 'hub-<name>' labels
            HUB_NAME=$(for label in $LABELS; do
              [[ "$label" == hub-* ]] && echo "${label#hub-}"
            done | xargs)
      
            if [ -n "$HUB_NAME" ]; then
              echo "Extracted hub name(s): $HUB_NAME"
              echo "hub_name=$HUB_NAME" >> $GITHUB_OUTPUT
            fi
      
            # Extract all 'bcourses-id-<id>' labels
            BCOURSES_ID=$(for label in $LABELS; do
              [[ "$label" == bcourses-id-* ]] && echo "${label#bcourses-id-}"
            done | xargs)
      
            if [ -n "$BCOURSES_ID" ]; then
              echo "Extracted Bcourses ID(s): $BCOURSES_ID"
              echo "bcourses_id=$BCOURSES_ID" >> $GITHUB_OUTPUT
            fi
          else
            echo "Label 'add shared directories' is NOT present."
            echo "add_shared_directories=false" >> $GITHUB_OUTPUT
          fi


      - name: Get shared directories paths
        if: ${{ env.DEPLOY && steps.check-add-shared-label.outputs.add_shared_directories == 'true' }}
        id: create-shared-dirs
        env:
          STAGING_OR_PROD: prod
          HUB_NAME: ${{ steps.check-add-shared-label.outputs.hub_name }}
          BCOURSES_ID: ${{ steps.check-add-shared-label.outputs.bcourses_id }}
        run: |
          python3 .github/scripts/shared_directories/get_shared_dir_path.py

      - name: Create shared directories on the NFS server
        if: ${{ env.DEPLOY && steps.check-add-shared-label.outputs.add_shared_directories == 'true' }}
        env:
          SHARED_DIRS: ${{ steps.create-shared-dirs.outputs.shared_dir_paths }}
          GCP_SA_KEY: ${{ secrets.NFS_SA_KEY }}
          NFS_SERVER_NAME: ${{ secrets.NFS_INSTANCE_NAME }}
          GCP_PROJECT: ${{ secrets.GCP_PROJECT_ID }}
          GCP_ZONE: ${{secrets.GCP_ZONE}}   
        run: |
          set -e
          
          echo "$GCP_SA_KEY" > $HOME/gcloud-key.json
          echo "Installing gcloud CLI and components..."
          sudo apt-get update
          sudo apt-get install -y google-cloud-cli
          
          echo "Authenticating to Google Cloud..."
          gcloud auth activate-service-account --key-file=$HOME/gcloud-key.json
          gcloud config set project "$GCP_PROJECT"
          gcloud config set compute/zone "$GCP_ZONE"
          
          echo "Starting SSH tunnel to $NFS_SERVER_NAME..."
          
          REMOTE_CMD=$(for dir in $SHARED_DIRS; do
            echo "mkdir -p \"$dir\" && chown ubuntu:ubuntu \"$dir\" && chmod 755 \"$dir\";"
          done)
          
          echo "Creating shared directories on the NFS server..."
          gcloud compute ssh "$NFS_SERVER_NAME" \
            --zone="$GCP_ZONE" \
            --tunnel-through-iap \
            --command="sudo su - ubuntu -c '$REMOTE_CMD'"
          
          rm -f $HOME/gcloud-key.json
          
      - name: Install Helm Chart
        if: ${{ env.DEPLOY }}
        run: |
            helm repo add jupyterhub https://jupyterhub.github.io/helm-chart/
            helm repo update

      - name: Deploy hubs to staging
        if: ${{ env.DEPLOY }}
        run: |
          while read deployment; do
            echo "Deploying single-user image and hub config to ${deployment}"
            hubploy --verbose deploy --timeout 30m ${deployment} hub staging
            echo
          done < <(python .github/scripts/determine-hub-deployments.py)

  deploy-hubs-to-prod:
    if: github.event_name == 'push' && github.ref == 'refs/heads/prod'
    runs-on: ubuntu-latest
    steps:
      - name: Get PR labels
        id: pr-labels
        uses: irby/get-labels-on-push@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Check for hubs that need deploying from the labels on the merge commit to prod
        run: |
          echo "PR labels: ${{ steps.pr-labels.outputs.labels }}"
          # If the PR labels "hub-images" or "jupyterhub-deployment" are
          # present, this means the base hub image has changed, and all hubs
          # (staging or prod) need to be redeployed.
          #
          if [[ -n ${GITHUB_PR_LABEL_HUB_IMAGES} || -n ${GITHUB_PR_LABEL_JUPYTERHUB_DEPLOYMENT} ]]; then
            echo "DEPLOY=1" >> $GITHUB_ENV
          # Otherwise, check to see if the PR labels contain any hubs, and 
          # deploy just those hubs to prod.
          #
          else
            for label in $(echo -e "${{ steps.pr-labels.outputs.labels }}"); do
              if [[ "$label" == hub-* ]]; then
                echo "DEPLOY=1" >> $GITHUB_ENV
              fi
            done
          fi

      - name: Check out the image repo
        if: ${{ env.DEPLOY }}
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # OR "2" -> To retrieve the preceding commit.

      - name: Setup python
        if: ${{ env.DEPLOY }}
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        if: ${{ env.DEPLOY }}
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Google Cloud SDK
        if: ${{ env.DEPLOY }}
        uses: google-github-actions/setup-gcloud@v2
        with:
          install_components: 'gke-gcloud-auth-plugin'

      - name: Install SOPS
        if: ${{ env.DEPLOY }}
        run: |
          mkdir -p ${HOME}/bin
          curl -sSL https://github.com/getsops/sops/releases/download/v3.9.0/sops-v3.9.0.linux.amd64 -o ${HOME}/bin/sops
          chmod 755 ${HOME}/bin/sops
          echo "${HOME}/bin" >> $GITHUB_PATH

      - name: Store SOPS secret in a file
        if: ${{ env.DEPLOY }}
        run: |
          cat << EOF > ${HOME}/sops.key
          ${{ secrets.SOPS_KEY }}
          EOF
          echo "GOOGLE_APPLICATION_CREDENTIALS=${HOME}/sops.key" >> $GITHUB_ENV

      - name: Install Helm
        if: ${{ env.DEPLOY }}
        run: |
            helm repo add jupyterhub https://jupyterhub.github.io/helm-chart/
            helm repo update

      - name: Deploy hubs to prod
        if: ${{ env.DEPLOY }}
        run: |
          while read deployment; do
            echo "Deploying single-user image and hub config to ${deployment}"
            hubploy --verbose deploy --timeout 30m ${deployment} hub prod
            echo
          done < <(python .github/scripts/determine-hub-deployments.py)
